### ISSUE TITLE
UWP missing WithParentActivityOrWindow

### ISSUE THREAD

**Issue by dansiegel** [AzureAD/microsoft-authentication-library-for-dotnet#1104]
**Which Version of MSAL are you using ?**
3.0.6-pre

**Platform**
UWP

**What authentication flow has the issue?**
* Desktop / Mobile
    * [X] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

Other? - please describe;

**Is this a new or existing app?**
n/a

**Repro**

```csharp
var accounts = await _client.GetAccountsAsync();
var builder = _client.AcquireTokenInteractive(_configuration.Scopes)
    .WithAccount(accounts.FirstOrDefault());

#if __ANDROID__
builder = builder.WithParentActivityOrWindow(CurrentActivity.Activity);
#elif WINDOWS_UWP
// Does not contain the definition for WithParentActivityOrWindow
builder = builder.WithParentActivityOrWindow(Window.Current);
#endif
result = await builder.WithUseEmbeddedWebView(true)
                        .ExecuteAsync();
```

**Expected behavior**

An API that is meant specifically for Windows should exist on said platform... 

**Actual behavior**

The API does not exist on Windows

**Additional context/ Logs / Screenshots**

![image](https://user-images.githubusercontent.com/3860573/56529104-113d9080-6505-11e9-8d48-bf7cbaf308bd.png)

**Comment by bgavrilMS** [comment]
Hi @dansiegel - thanks for brining this up. Indeed, the API does not exist on UWP. The reason is that UWP provides a dispatcher object that lets us get back to the UI thread and also APIs that let us know the current window. So we have pretty much all we need to pop-up the browser. 

What would you expect the behaviour to be in this case? If you were writing code from a shared NetStandard assembly, you'd have a WithParentWindowOrActivity(object). But it looks like you're writing code from a multi-framework assembly (cool!), and we've done work to show only framework relevant APIs.

**Comment by dansiegel** [comment]
I will say I find it a little strange when the API is available on iOS where we don't care about the API... that said I think adopting a separate locator pattern as discussed in #1095 is probably the way to go so it all becomes a moot point as it would mean the API can go away entirely.
