### ISSUE TITLE
[Documentation] Documentation needed for how to handle Graph API with B2C

### ISSUE THREAD

**Issue by dansiegel** [AzureAD/microsoft-authentication-library-for-dotnet#1105]
### Documentation Related To Component:

Azure Active Directory B2C / Xamarin Mobile Apps / Graph API

### Please check those that apply

- [ ] typo
- [x] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in example
- [x] needs example

### Description Of The Issue

It's a very common thing to want to about /me and sometimes /users or /groups

There needs to be something to help show how you might get the proper scopes or otherwise work with the Graph API with B2C from a Xamarin Mobile App to perform these functions:

- Who am I
- Who are the users in the domain
- What groups am I a member of

**Comment by bgavrilMS** [comment]
As far as I know, you cannot access the graph using tokens from B2C. @jennyf19 can you confirm? Is there work being done to address this?

**Comment by dotnetgator** [comment]
Would this be what you are looking for (or at least a start in that direction)?
https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-devquickstarts-graph-dotnet

**Comment by bgavrilMS** [comment]
I am not familiar enough with the Azure Graph to give you a good answer. Perhaps @dkershaw10 can chime in?

**Comment by dansiegel** [comment]
@dotnetgator I'm actually familiar with that quickstart… the issue I have with it is that it's steering you towards using a client credential. The whole idea from mobile is that you're already working with an authenticated user so you should be able to see who your user is, what roles or groups they may have, beyond the claims that come back in the Token.

**Comment by jmprieur** [comment]
@valnav @parakhj : do you have a doc on this?

**Comment by valnav** [comment]
While this uses client credential, you can still query the groups using this [AD Graph Example](https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-devquickstarts-graph-dotnet) 

Alternatively, you can use [IDP Pass through token](https://docs.microsoft.com/en-us/azure/active-directory-b2c/idp-pass-through-user-flow)

**Comment by tmarkovski** [comment]
The above solutions use ADAL and Azure Graph in a .NET Framework projects and work fine.
It would be great to be use MSAL and Microsoft Graph to access B2C. Is this at all possible?

**Comment by bgavrilMS** [comment]
This is not MSAL docs.

**Comment by jmprieur** [comment]
and you cannot call Graph with social identities

**Comment by dansiegel** [comment]
@jmprieur that makes sense that Graph wouldn't work for social identities... but there is still AAD behind everything... so I would think you could ultimately use the backing AAD instance to assign users into groups and determine what group a user is in

**Comment by mmacy** [comment]
@dansiegel We're going to be putting together some clearer documentation on AAD and B2C token endpoints and what's possible with the tokens obtained from them, but until then, here's some cut-and-paste of info on the topic originally from @JasSuri.

---
There is only one pattern to access the Microsoft Graph API in AAD/B2C app scenarios, in general:

1. User logs in to B2C app via [B2C app registration](https://docs.microsoft.com/azure/active-directory-b2c/tutorial-register-applications)
2. App calls web API
3. Web API uses client credentials against an [AAD app registered](https://docs.microsoft.com/en-us/azure/active-directory-b2c/microsoft-graph-get-started#register-management-application) in the same tenant and sends a Graph API scope
4. Web API uses app token to do something in Graph

---
### Azure AD vs. Azure AD B2C endpoints

- AAD tenant - contains only AAD endpoints. It is a single token issuer.
- B2C tenant - contains AAD and B2C token endpoints. There are two token issuers.

A B2C tenant contains:

- AAD endpoint: `login.microsoftonline.com` (*not* being deprecated)
- B2C endpoint:
  - `login.microsoftonline.com` + B2C policyId parameter (this is being **deprecated**)
  - `tenantName.b2clogin.com` + B2C policyId parameter

Based on the authentication request, the request is routed to the two different token issuers.

The next key point:

- AAD endpoints allow you to obtain tokens to your applications protected by an AAD application registration.
- AAD endpoints allow you to obtain tokens to Microsoft APIs because they are also protected by AAD on the Microsoft side, for example the Microsoft Graph API.
- AAD endpoints _allow_ `client_credentials`.
- B2C endpoints allow you to obtain tokens to your applications only, protected by a B2C application registration.
- B2C endpoints _do not_ allow `client_credentials`

Now, when you use MSAL, based on the above rule set you _cannot_ use `tenantName.b2clogin.com` to obtain a token for the Microsoft Graph API.

This means a user's B2C authentication cannot be used to authorize to AAD-protected apps, or Microsoft APIs.

When you use `login.microsoftonline.com` and don't provide any policyId parameters against a B2C tenant, you hit the AAD endpoints of the B2C tenant, again it *works*. You can get tokens to Microsoft Graph API for example, using the user's context. This should work with MSAL, just configure it as you would for any other AAD tenant, instead use your B2C tenant name.

When you use `tenantName.b2clogin.com` and provide any policyId parameters against a B2C tenant, you hit the B2C endpoints of the B2C tenant, which cannot be used with Microsoft Graph.

---
Cc: @JasSuri @nickgmicrosoft @jmprieur

**Comment by dansiegel** [comment]
not sure if this issue should perhaps be reopened, there is a new issue that is tracking the Graph API for B2C, or I've just totally missed some existing docs.

Was hoping there could be some clarification at least. As of last year this issue was closed as using the Graph was considered not possible with B2C. In my latest dev environment with B2C I've noticed however that Graph seems to be there out of the box... 

![image](https://user-images.githubusercontent.com/3860573/93281245-92439a80-f780-11ea-8e70-a16900cb0351.png)

It also seems to be part of the templates with the Microsoft.Identity.Web project that's under development.

**Comment by tmarkovski** [comment]
I can confirm that B2C works with Microsoft Graph, have been using it production for about a year now using MSAL for authentication and Microsoft.Graph for user management.

**Comment by JasSuri** [comment]
> not sure if this issue should perhaps be reopened, there is a new issue that is tracking the Graph API for B2C, or I've just totally missed some existing docs.
> 
> Was hoping there could be some clarification at least. As of last year this issue was closed as using the Graph was considered not possible with B2C. In my latest dev environment with B2C I've noticed however that Graph seems to be there out of the box...
> 
> ![image](https://user-images.githubusercontent.com/3860573/93281245-92439a80-f780-11ea-8e70-a16900cb0351.png)
> 
> It also seems to be part of the templates with the Microsoft.Identity.Web project that's under development.

It is now possible to create a B2C app reg, and give it permission to Graph API. But the usage of that is still following AAD principals, ie you get the token from AAD endpoint, not the B2C endpoint.
I dont really recommend it right now due to confusion, just have AAD App reg for AAD workloads, and B2C App reg for your User Flows/Custom Policies.

**Comment by nickgmicrosoft** [comment]
Hi folks, adding to what Jas mentioned:

User tokens issued by the Azure AD B2C authentication service (tokens generated via user flows/custom policies) are not valid with MS Graph. MS Graph will not recognize these. 

In order to use MS Graph, there are two options: 
1. App to App using Azure AD’s OAuth client credentials (recommended) – use Application permissions. [Documentation](https://docs.microsoft.com/en-us/azure/active-directory-b2c/microsoft-graph-get-started?tabs=app-reg-ga).
2. User to App using Azure AD’s OAuth user authentication. This only works for admin users/guest users and does not authenticate a user using B2C’s user flows or custom policies. If this route, ROPC is typically the simplest route. This uses the delegated permissions.

To help with clarity here, as of this week, only offline_access and openid show under Microsoft Graph delegated permissions if the supported account type of the app is **"Accounts in any identity provider or organizational directory (for authenticating users with user flows)"**. These are the only two "MS Graph" delegated permissions relevant for B2C user flows (technicality).

If the support account type is one of the other two options, which can't be used with user flows, you'll see the full list of MS Graph delegated permissions for use with option #2 above.
