### ISSUE TITLE
IdentityModel Extensions

### ISSUE THREAD

**Issue by dbrownxc** [AzureAD/microsoft-authentication-library-for-dotnet#1106]
### Documentation Related To Component:
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet
vs MSAL

### Please check those that apply

- [ ] typo
- [ X] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

### Description Of The Issue
I don't think I 've seen this asked here, but I could just be missing the documentation.  What is the difference between MSAL and IdentityModel extensions?  To me, it looks like MSAL is built on top of IdentityModel extensions.  Is this correct?  

We are writing a new series of ASP.NET Core Web APIs and I want to understand the benefits of using MSAL vs IdentityModel Extensions.  I have my code working without MSAL for .NET, so I'm wondering if I'm missing out on something or doing more work than needed.`

**Comment by dbrownxc** [comment]
https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/aspnetcore2-2/WebApp-OpenIDConnect-DotNet.csproj

Here is the sample I am starting with, in case that helps.

**Comment by dbrownxc** [comment]
Also looks like the top level functionality we are using is in the base https://github.com/aspnet/AspNetCore repository, though Microsoft.AspNetCore.Authentication.AzureAD.UI, which looks like it uses the IdentityModel Extensions for .NET.  We started from this example: https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2

**Comment by bgavrilMS** [comment]
MSAL is about acquiring tokens, which can be used to call protected APIs, access protected resources etc. 
IdentityModel Extensions is about protecting APIs and validating tokens. 
We try to maintain the wiki on each library and those describe the scenarios more in depth. 

Note that for an ASP.NET Core website, you do not need to use MSAL to achieve login (because ASP implements OpenID Connect standard and AAD is OpenID Connect compliant). However you do need MSAL for more complex scenarios, such as obtaining more details about the user or calling protected APIs. Have a look at this multi-scenario sample: 

https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2

**Comment by dbrownxc** [comment]
Perfect.  That's a very clear explanation.  Thanks!
