### ISSUE TITLE
ROPC is always giving invalid_grant error when tried with httpclient

### ISSUE THREAD

**Issue by jashif** [AzureAD/microsoft-authentication-library-for-dotnet#1126]
I have followed the steps mentioned in the link to do the ROPC via HTTP client. I tried with the postman also

https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth-ropc

the error am getting is below , event hough username and password is correct., how ever the solution works with when using MSAL library , but not via httpclient.

{
    "error": "invalid_grant",
    "error_description": "AADSTS50126: Invalid username or password.\r\nTrace ID: 5c0e23b4-e687-4736-9673-9136872a1000\r\nCorrelation ID: d77a03d5-fbb9-447f-911e-b2630bb1d196\r\nTimestamp: 2019-04-30 09:46:18Z",
    "error_codes": [
        50126
    ],
    "timestamp": "2019-04-30 09:46:18Z",
    "trace_id": "5c0e23b4-e687-4736-9673-9136872a1000",
    "correlation_id": "d77a03d5-fbb9-447f-911e-b2630bb1d196"
}

**Comment by bgavrilMS** [comment]
Hi @jashif 

Firstly, let me say that you should generally not use this flow in production. It's ok for testing purposes and corner case scenarios, but OAuth2 is all about not having to touch passwords. 

The PostMan linked actually works for me when I try with a user that was created in AAD or a federated AD. It doesn't work for me with an MSA account (i.e. @outlook.com) - I believe this is by design. 

I wonder if your password contains special chars and if you can escape them correctly? The error message is essentially "bad password" :). Maybe try to capture a Fiddler trace and compare?

**Comment by jashif** [comment]
Hi @bgavrilMS 

Our use case is for specific service account scenario, as we don't want to send basic auth over HTTP,
I will try to trace via fiddler to see what's sending over http 👍

**Comment by bgavrilMS** [comment]
Yes, I understand that you do not want to use basic auth over HTTP. I am saying that ROPC is also something to be avoided.
