### ISSUE TITLE
Enhancement: ADAL to MSAL transition: setting Correlation Id.

### ISSUE THREAD

**Issue by msminski** [AzureAD/microsoft-authentication-library-for-dotnet#1211]
**Is your feature request related to a problem? Please describe.**
With ADAL, our current implementation of WebAuth library assigns our own correlation Id value to the AuthenticationContext instance before calling to AAD. This way, we could assure that one correlation Id is used throughout the flow. In our attempt to transition to MSAL, we've found out that ConfidentialClientApplication(or other related classes) class doesn't seem to have property CorrelationId anymore, while MsalServiceException class does have the property. 

**Describe the solution you'd like**
We'd like to know if this change(missing CorrelationId property in ConfidentialClientApplication class) is intended so that partners could only use the correlation ids came back from AAD side, or is this a feature that could be requested to be added back.

**Comment by bgavrilMS** [comment]
AFAIK a correlation ID is generated for each request and:

- MSAL will log it
- MSAL will send it to AAD, and if AAD encounters an error it will also display the correlation ID

This should be sufficient to track problems across both MSAL (client side) and the Identity Provider (AAD). 

@jmprieur to confirm

**Comment by jmprieur** [comment]
@msminski : can you describe your scenarios a bit more: do you need to trace things beyond authentication? 
you mention that you'd like the CorrelationId to be on ConfidentialClientApplication, do you really mean for the duration of the application? or would you need more something like .WithExternalCorrelationId(guid) on each AcquireTokenXX request?

**Comment by msminski** [comment]
@jmprieur: we definitely meant to ask for the latter, something like .WithExternalCorrelationId(guid) on each AcquireTokenXX request. The purpose of this is to provide our partners an option to trace their scenarios that involve authentication with single correlation Id. Previously we achieved it by setting CorrealtionId in AuthenticationContext instance, but now that I think about how ConfidentialClientApplication is representing application duration, it would make more sense to make the second approach you mentioned above(WithExternalCorrelationId(guid)).

Thank you

**Comment by jmprieur** [comment]
+ @MarkZuber  and @henrik-me  as maybe the right answer to the scenario is not the correlation id, but the telemetry API?

**Comment by henrik-me** [comment]
@jmprieur : I believe it would be ok to allow developers to specify a correlation id. I don't think the answer here is in the telemetry.

**Comment by jmprieur** [comment]
This makes sense @henrik-me.
The only question is: at the app building time? token aquisition time ? or both?

**Comment by jmprieur** [comment]
Proposed spec

### Scenario 1: developer wants to access the correlation ID (which is generated by MSAL.NET)

In that scenario, the developer does not want to set the correlation ID, but just get it from MSAL.NET. This is already possible in the case of service errors (through the  `MsalServiceException.CorrelationId` property), but not in the case of successful transactions. The proposal is to add a property (`CorrelationId`) to `AuthenticationResult`.

```CSharp
public async Task Scenario1()
{
    IConfidentialClientApplication app = ConfidentialClientApplicationBuilder.Create(clientID)
        .Build();

    Guid usedCorrelationId;
    try
    {
        AuthenticationResult result = await app.AcquireTokenForClient(scopes)
                                                .ExecuteAsync();
        usedCorrelationId = result.CorrelationId;
    }
    catch(MsalServiceException ex)
    {
        usedCorrelationId = Guid.Parse(ex.CorrelationId);
    }
}
```

### Scenario 2: developer wants to set the correlation ID (app session)
In this scenario the developer generates a Correlation at a request in a Web App / Web API, and wants to pass-it to MSAL.NET, which passes it to the service, to trace things.

```CSharp
public async Task Scenario2()
{
    IConfidentialClientApplication app = ConfidentialClientApplicationBuilder.Create(clientID)
        .Build();

    Guid myCorrelationId = Guid.NewGuid();
    try
    {
        AuthenticationResult result = await app.AcquireTokenForClient(scopes)
                                                .WithCorrelationId(myCorrelationId)
                                                .ExecuteAsync();
    }
    catch(MsalServiceException ex)
    {
    }
}
```

Additional design questions/remarks
- Do we want the CorrelationId property and the argument to `.WithCorrelationId()` be a `Guid` or a string? The `CorrelationId` property on the `MsalServiceException` is a string, contrary to the proposal above where it's a `GUID`. We probably want a string to be consistent?
- `.WithCorrelationId()` would of course apply to `AbstractAcquireTokenParameterBuilder<T>`
- I don’t think that we need to expose `CorrelationId` on `MsalClientException` as this error happens when things don’t even go to the service (typically when the application is not well coded). If we do that means moving `CorrelationId` to `MsalException` which is a binary breaking change => MSAL 5.0.0 :)

**Comment by jmprieur** [comment]
@msminski : this is now fixed and available in MSAL.NET 4.1
