### ISSUE TITLE
[Feature Request] HasTokens property on the Token cache serialization argument

### ISSUE THREAD

**Issue by TiagoBrenck** [AzureAD/microsoft-authentication-library-for-dotnet#1294]
**Is your feature request related to a problem? Please describe.**
As discussed on this thread, https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/issues/130, an empty `MsalCacheItemBase` JSON is generated when clearing the token cache. This is not that harmful but we could avoid saving this empty JSON structure.

**Describe the solution you'd like**
As suggested by the developer, we could have a property like `IsEmpty` on `TokenCacheNotificationArgs` that could be checked before saving the token in memory (or DB).

**Additional context**
https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/issues/130

**Comment by jmprieur** [comment]
Adding supportability as we can avoid questions like "why do we save empty caches" when an account is removed.

**Comment by jmprieur** [comment]
Requires more spec.

**Comment by bgavrilMS** [comment]
We discussed offline with @jmprieur about this. The term `is_empty` is probably too overloaded, since the cache can contain: 

- tokens, 
- accounts  
- app metadata.
- other artefacts in the future (extensibility)

Today, it makes sense to lower COGS of apps integrating with MSAL if there are no accounts. No accounts means no tokens. This holds even if an FRT is present, you still need an account to use it...

So I would propose that for the user cache, IsEmpty means "no accounts". 
The app cache is different - it only holds access tokens. There are not Accounts, IDTokens, RTs. So IsEmpty means "no **unexpired** access tokens". 

We still need to find a name for the flag that conveys these 2 meanings, but I think the semantics should be the ones I just mentioned.

**Comment by bgavrilMS** [comment]
user cache is empty if no accounts exist 
app cache does not matter

**Comment by bgavrilMS** [comment]
Impact: reduce COGS of apps

**Comment by bgavrilMS** [comment]
I'm working on this but I'm slightly concerned about the naming. So we can only tell the developer if the cache contains tokens in the notifications that comes AFTER the update (OnAfterUpdate). 

But what about the other 2 callbacks - `OnBeforeWrite` and `OnBeforeAccess`? Here we are firing the callback before the token is read from disk. Does it make sense to tell the user if there are tokens in the cache in memory?

**Comment by jmprieur** [comment]
yes, @bgavrilMS I think it's a good proposal.
