### ISSUE TITLE
Xamarin.Forms ClientSecret Authentication 

### ISSUE THREAD

**Issue by robiharid** [AzureAD/microsoft-authentication-library-for-dotnet#1316]
Confidential Client Credential flow is disabled on mobile platforms 
(https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Client-credential-flows#availability)

But the article does not even suggest an alternative way of doing it.

What options do I have to authenticate a service account for my Xamarin forms app.

**Comment by bgavrilMS** [comment]
You may only use Public Client Application, namely the Interactive flow, to get tokens. This is because on a mobile app, you cannot safely deploy a secret. 

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Acquiring-tokens-interactively

**Comment by robiharid** [comment]
> You may only use Public Client Application, namely the Interactive flow, to get tokens. This is because on a mobile app, you cannot safely deploy a secret.
> 
> https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Acquiring-tokens-interactively

Thank you.

I am not concerned with deploying secrets, this is a private app. 

I have acquired tokens interactively previously. Is there any way we can do it without user interaction? Passing a service account username and password seems to be much more unsecure than passing client secrets.

My end goal is to simply read a list of users in the current AD group. No admin permissions.

**Comment by bgavrilMS** [comment]
When you get a token interactively, MSAL will actually fetch a Refresh Token as well as an Access Token. The Refresh Token can be silently used to get fresh ATs, and it has a default expiration of 3 months (rolling). All you need to do is invoke `AcquireTokenSilent`. 

We don't expose Confidential Client flows on mobile because we want to guide developers to better security. If you know what you are doing, then consider implementing the OAuth calls yourself, for example: 

https://blogs.msdn.microsoft.com/softwaresimian/2017/10/05/using-postman-to-call-the-graph-api-using-azure-active-directory-aad/

**Comment by bgavrilMS** [comment]
Closing the question / issue
