### ISSUE TITLE
Nuget update to support netstandard2.0

### ISSUE THREAD

**Issue by JBaltika** [AzureAD/microsoft-authentication-library-for-dotnet#1362]
Hi guys,

Could it possible update nuspec and msbuild to support netstandard2.0. I understand that current netstandard1.3 library works can be added to any netstandard2.0 project. However, its few things to consider. The first projects pulling useless nugets and second more important probably  is run-time binding redirect section entries. For some enterprise solutions who has hundred projects to manage these bindings become major issue especially with config transform and support for different frameworks.

![decompiler](https://user-images.githubusercontent.com/1755340/63859380-3fc8ed80-c975-11e9-95b5-1d55bc58313b.jpg)

Thanks in advance Jim

**Comment by bgavrilMS** [comment]
Could you explain more about the binding redirects please? How is affecting you? 

MSAL is build for many, many platforms. I think the pure netstandard version is mainly used when referencing MSAL from shared projects like Xamarin shared. Is this your scenario? Otherwise, you'll pretty much use the .NET Core or .NET Classic version.
