### ISSUE TITLE
[Bug] In WPF client the social login stack in the redirecting state

### ISSUE THREAD

**Issue by TuroczyX** [AzureAD/microsoft-authentication-library-for-dotnet#1385]
**Which Version of MSAL are you using ?**
4.3.1

**Platform**
.NET 4.6.2

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ X ] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)

**Is this a new or existing app?**
The app is in production

**Repro**
_Currently does not work the library at all if you call it from WPF. Even the sample application does not work, even my application does not work._ 

Repo: 
Use any type of WPF application, like the sample app. 

1. Download and Build the Microsoft Azure Sample App: https://github.com/Azure-Samples/active-directory-b2c-dotnet-desktop 
2. Start it.
3. Click on the **Sign In** button.
4. Click any type of social provider. (Facebook, Google, Microsoft) 
5. The Window Title change to "Redirecting..." and stack in this state. 

_Same with **every** WPF applications._ 

Check the sample code, but here is the method that called. 
```csharp
 authResult = await (app as PublicClientApplication).AcquireTokenInteractive(App.ApiScopes)
                    .WithParentActivityOrWindow(new WindowInteropHelper(this).Handle)
                    .WithAccount(GetAccountByPolicy(accounts, App.PolicySignUpSignIn))
                    .ExecuteAsync();
```

**Expected behavior**
A clear and concise description of what you expected to happen (or code).

**Actual behavior**
A clear and concise description of what happens, e.g. exception is thrown, UI freezes  

**Possible Solution**
Maybe there is a problem on Microsoft B2C side, but the library does not handling this scenario.

**Additional context/ Logs / Screenshots**
<img width="426" alt="1" src="https://user-images.githubusercontent.com/7687174/64721701-528f0680-d4cd-11e9-9a75-3aa763f451e5.png">
<img width="426" alt="2" src="https://user-images.githubusercontent.com/7687174/64721702-528f0680-d4cd-11e9-80de-3ddfd9afb37a.png">

**Comment by foxyjess1** [comment]
We have been struggling with this since yesterday. We have a C++ desktop app that started suffering from this yesterday for many of our users. I have found if I create a new user on my machine and log in as that - it works ok so it lead me to look for user caches in the registry and I found this key with a reference to login.microsoftonline.com. Renaming the key immediately solves the problem for us and I am waiting to hear back from microsoft whether this is safe as a workaround whilst they address the issue  HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\AAD

**Comment by jennyf19** [comment]
thanks for the additional information @foxyjess1 and @xammob will update here as we learn more.

**Comment by foxyjess1** [comment]
Thanks @jennyf19 .... MS support have told us not to use the reg hack saying it’s unsafe - so we still have no solution for our users and re-deploying our desktop application using b2clogin.com is at least 2 weeks work.... we’re desperate for a resolution.......

**Comment by jennyf19** [comment]
@foxyjess1 can you email me the name of the support engineer you are working with? thx. jeferrie@microsoft.com

**Comment by jennyf19** [comment]
@foxyjess1 nevermind...we are all aligned on the MS side of things. hopefully we'll have an update here sometime today. Thanks for your patience.

**Comment by jennyf19** [comment]
@foxyjess1 @xammob @TuroczyX @jondmcelroy 
B2C should have a fix out by end of day today, will update here if that timelines changes.

**Comment by foxyjess1** [comment]
Thanks for the info! I hope this is the case and MS can address the issue. We can move to b2clogin - but we’d rather do it in a co trolled fashion than a massive rush to paper over MS’s cracks!!!

Appreciate the updates.

**Comment by jondmcelroy** [comment]
@TuroczyX Thanks for the direction, I finally figured out like you showed that I needed to update the app registration for the AD application. The documentation needs to be updated with pictures and better explanation.

@jennyf19 Thanks for being on top of this and all of the communication!

For anyone else thinking about making the switch to b2clogin, you will need to update all of your applications to use the b2clogin at the same due to needing to validate the issuer at the server.
So even if you properly authentication with the b2clogin at the client level, your server also needs to be updated to get metadata from the b2clogin.

I am hoping that the rollback happens soon so that I do not have to hotfix on a friday afternoon!

**Comment by mmacy** [comment]
@jondmcelroy Thanks for the call-out on exactly what you'd like to see in the docs, that's super helpful. I've added a work item to add an expanded explanation to the [Use b2clogin.com](https://docs.microsoft.com/azure/active-directory-b2c/b2clogin) doc. Will tag this issue in the PR once I get there.

**Comment by jennyf19** [comment]
@foxyjess1 @xammob @TuroczyX @jondmcelroy
The fix is out.
I have confirmed that I no longer hit the "redirecting..." page...can you please do so as well and let us know? Thank you.

**Comment by TuroczyX** [comment]
Now it is working ;)

**Comment by foxyjess1** [comment]
Confirmed! This is working for me now in our production app! Means we don’t have to rush out the change to b2clogin - although we’ll make sure we move to it soon!
Thanks for the comms here! It’s been a very stressful 48 hours!!!

**Comment by jmprieur** [comment]
Thanks @jennyf19 for driving this!
