### ISSUE TITLE
[Bug] AcquireTokenInteractive() fails about a missing 'client_assertion' or 'client_secret'

### ISSUE THREAD

**Issue by TestO2015** [AzureAD/microsoft-authentication-library-for-dotnet#1391]
**Which Version of MSAL are you using ?**
Microsoft.IdentityModel.Client 4.3.1

**Repro**
```csharp
var app = PublicClientApplicationBuilder.Create(clientId)
                .WithAuthority(authority)
                .WithRedirectUri(redirectUri).Build();
var authResult = app.AcquireTokenInteractive(scopes: new string[] { "user.read" })
                .WithPrompt(Prompt.SelectAccount)
                .ExecuteAsync().Result;
```

**Expected behaviour**
The user will be prompted for Credentials to connect to AzureAD, the user will be authenticated and a token returned.

**Actual behaviour**
AquireTokenInteractive() fails with the error:

> "AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'"

**Comment by jmprieur** [comment]
@TestO2015 : when you did your app registration, would you have registered the RedirectURI as a Web redirect URI, rather than a "Public client/Native (mobile & desktop)" one?
 
![image](https://user-images.githubusercontent.com/13203188/65118476-faaa4100-d99f-11e9-8b18-7cf84023e79e.png)

Do you need a redirect URI? (are you using .NET Core)? 

See also: https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-desktop-app-registration#redirect-uris
and https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-desktop-acquire-token#acquiring-a-token-interactively

**Comment by TestO2015** [comment]
@jmprieur The client Application is not .NET Core, however when I remove the Redirect URI I get an error: 

> AADSTS50011: The reply url specified in the request does not match the reply urls configured for the application: 'c6bb821e-3489-4edb-943f-0c93d6b7f8ea'. 

The app registration has:
"allowPublicClient": true,
https://login.microsoftonline.com/common/oauth2/nativeclient ticked

Is it possible to connect without a Redirect URI?

**Comment by bgavrilMS** [comment]
Is your application a web site? Or a fat client (mobile app, WPF app, console app) - aka public client? 

I think AAD requires a redirect URI even if MSAL does not need it. Can you confirm that the redirect URI is set as a "Public client / native (mobile & desktop)" ?

**Comment by TestO2015** [comment]
Thanks @bgavrilMS. It works with a "Public client / native (mobile & desktop)" RedirectURI.
