### ISSUE TITLE
[Feature Request] Allow out of band releases of the extension libraries

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#1457]
**Is your feature request related to a problem? Please describe.**
Today the MSAL repo hosts MSAL itself and MSAL extensions. The extensions take on the version of MSAL, suffixed by _-preview_

This model works for releasing both MSAL and the extensions (although we do not currently publish the extensions to nuget). But the model does not allow for releasing the extensions out of band from MSAL, i.e. if a change is required in an extension, we need to release MSAL as well.

**Describe the solution you'd like**

**Solution 1**: Do nothing and require an MSAL release for each extension release. 

Pros: extension always in sync with latest MSAL. Versioning is intuitive (e.g. extension ver 4.5 corresponds to MSAL 4.5)
Cons: no out of band releases of extension possible

**Solution 2**: Move the extension out of MSAL repo and support only package reference. 

Pros: release cycles are decoupled
Cons: we may forget to release extensions and customers of extensions will use old MSAL. Separate versioning (e.g. ext version 1.1 uses MSAL 4.5)

**Solution 3**: Hybrid - support both out of band and in sync. 

Pros: best of both worlds?
Cons: needs some work on the build system; will be harder to maintain; versioning will be un-intuitive for out of band releases (e.g. out of band extension version 4.6.1 takes a dependency on MSAL 4.6; there won't be an MSAL 4.6.1, we'll have to go to 4.6.2 afterwards)

**Comment by bgavrilMS** [comment]
CC @crmann1

**Comment by henrik-me** [comment]
@bgavrilMS 
I would assume that solution 2 be implemented in the same repo. With a "switch" to enable either project reference (for debugging/development) and nuget reference for releasing? It means though that if shipping both at the same time the msal nuget has to ship before the extensibility package can ship.

**Comment by rayluo** [comment]
Interesting. MSAL Python Extension happened to choose solution 2 since day 1 and did not really give much thoughts on other options. For what it's worth, in such a pilot run, we do see that:

* The extension version number (e.g. 0.1.1) does not have any visual hint on the MSAL Python version (e.g. 0.4.1) that it depends on. However that was not an issue at all, because, as a standalone package itself, MSAL Python Extension can declare its dependency in the usual way that was used by the entire eco-system (e.g. Project Foo 1.2.3 depends on Project Bar 4.5.6), and app developer don't even need to care. Package manager would figure it out.

* We do risk situation that "we forget to release extensions and customers of extensions will use old MSAL". (In fact, it is happening right now.) But that seems like easy enough to recover. We just bump its dependency version number and do a quick release.

**Comment by jmprieur** [comment]
The extension libraries are now released from their own repo
