### ISSUE TITLE
[Bug] B2C Sign-In with AppleID not redirecting back to application on iOS when using system browser and passcode

### ISSUE THREAD

**Issue by jennyf19** [AzureAD/microsoft-authentication-library-for-dotnet#1491]
**Which Version of MSAL are you using ?**
latest version

**Platform**
xamarin iOS

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

Other? - please describe;

**Repro**

@WilliamWatterson86 has shared a repro

**Expected behavior**
Use AppleID as an IdP for B2C.

**Actual behavior**
Using the repro provided by the customer,
- run the app
- Hit "sign in w/Apple"
- Resolve the MFA (passcode or face id)
- Create an account
- Successful log-in.
- Sign in again
- Hit "sign in w/Apple"
- Resolve the MFA (passcode or face id)
- Application hangs on a blank page and does not return to the application.

**Additional context/ Logs / Screenshots**
![image](https://user-images.githubusercontent.com/19942418/68261601-7e25fd00-fff5-11e9-9555-a84ee58f2c2b.png)

**Work Around**
Embedded webview works in the above scenario.

Not labeling this as a bug yet, as I need more time to investigate the issue, now that I am able to repro it locally. Will update the issue with progress.

**Comment by jennyf19** [comment]
waiting on lab team to get us an account for testing

**Comment by richp582** [comment]
We've hit the white screen on Apple Id Sign in as well.  Switching to embedded View works fine, but then breaks google.  This is a critical issue for us at the moment.

Any sort of work around or help would be appreciated...

Thanks,
Rich

**Comment by jennyf19** [comment]
Thank you for the additional information @richp582

**Comment by richp582** [comment]
So, what we ended up doing, which really stinks... is removing apple sign in from our default policies and creating an apple only idp policy.  Then in our app we have a separate ui button for Sign Up / Sign In for apple.

The "main" sign up / sign in button works well enough and covers email, facebook, and google... using the system browser... the Apple button uses the embedded view...  however, while it "works" it's not pretty.

The UX is definitely weird... instead of seeing our custom IDP page with background the user is treated to a white screen and then the little apple auth pop-up on the bottom shows "null" for the app name.  Previously when it was grouped in with the the rest of the providers it used to show our b2c domain.

Ideally I would like to see our app name and be able to have some sort of placeholder image instead of the blank white page.

FWIW, our Apple side stuff should be setup correctly, as I AM seeing the app icon in the apple auth pop-up... just "null" for the name.

I'd be glad to provide more info if it helps.

Thanks,
Rich

**Comment by jennyf19** [comment]
Thanks @rich3737 ...feel free to shoot me an email and i'll see if we can set you up with the right b2c people to share this feedback as well. jeferrie@microsoft.com

**Comment by jennyf19** [comment]
update: based on our testing, this is not working with passcode only and system browser

Repro:
Sign-in w/Apple. Use Passcode:
![image](https://user-images.githubusercontent.com/19942418/73477172-971a2200-4348-11ea-8a8d-7105b9334bfe.png)

Enter Passcode:
![image](https://user-images.githubusercontent.com/19942418/73477187-9ed9c680-4348-11ea-882e-30c06cf67d01.png)

Webview hangs:
![image](https://user-images.githubusercontent.com/19942418/73477210-aac58880-4348-11ea-8364-3c56d3c7e89d.png)

OR - Select "Use Different AppleId" and this works
![image](https://user-images.githubusercontent.com/19942418/73477222-b0bb6980-4348-11ea-8a1f-9fb07869fdea.png)

**Comment by ps-rpopola** [comment]
I guess passcode / face id would have the same experience.

Thanks for the update

**Comment by jennyf19** [comment]
@rich3737 @WilliamWatterson86 
This issue seems to be fixed in iOS 13.4. See linked issue for more details ->
"The original issue was an Apple bug and was caused by a race condition between Apple ID extension returning result and ASWebAuthenticationSession response handling (webkit was getting cancelled error -999)."

**Comment by WilliamWatterson86** [comment]
@jennyf19 - just tried this and you are right - working well now!  Thanks for all your help

**Comment by jennyf19** [comment]
Thanks @WilliamWatterson86 . Will close this issue. Thank you.
