### ISSUE TITLE
[Bug] Error AADSTS50011 when Application is configured for multi-tenancy

### ISSUE THREAD

**Issue by hausec** [AzureAD/microsoft-authentication-library-for-dotnet#1575]
**Which Version of MSAL are you using ?**
MSAL 3.0 Preview

**Platform**
net4.5 framework

**What authentication flow has the issue?**
* Desktop / Mobile
    * [X] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

Other? - please describe;

**Is this a new or existing app?**

c. This is a new app or experiment

**Repro**

```csharp
app = PublicClientApplicationBuilder.Create(ConfigurationManager.AppSettings["clientId"]).WithAuthority(AadAuthorityAudience.AzureAdMultipleOrgs).Build();
```

**Expected behavior**
Successful login

**Actual behavior**
AADSTS50011: The reply url specified in the request does not match the reply urls configured for the application:

**Additional context/ Logs / Screenshots**
Application is configured for multi-tenancy:
https://i.imgur.com/XwncoAm.png
https://i.imgur.com/0TtxAhi.png
However, when trying to use this application in a different tenant from which is was originally configured in, it produces that error. The goal of the application is for anyone to be able to use it without configuration on their end.

**Comment by jennyf19** [comment]
@hausec Can you try with the latest version of the MSAL (4.7.1) and see if the issue repros there as well? You should also use `.WithRedirectUri(string redirectUri)`

**Comment by bgavrilMS** [comment]
@hausec - when you don't specify a redirect URI (as @jennyf19 mentioned), MSAL will use the default one, which is smth like `urn:ietf:wg:oauth:2.0:oob` (it's in the OAuth spec ... doesn't even look like an url...)

However, the application registration no longer uses this url. So that's the reason for the mismatch. 

To fix this I suggest you to go to the Azure portal, and in your application configure: `https://login.microsoftonline.com/common/oauth2/nativeclient`

![image](https://user-images.githubusercontent.com/12273384/72429699-7bc7e800-3788-11ea-928f-3edad70984d4.png)

Then in MSAL, 

```csharp
app = PublicClientApplicationBuilder.Create(ConfigurationManager.AppSettings["clientId"])
.WithAuthority(AadAuthorityAudience.AzureAdMultipleOrgs)
.WithRedirectUri("https://login.microsoftonline.com/common/oauth2/nativeclient")
.Build();
```

**Comment by hausec** [comment]
Ah ok, that worked. Thank you!
