### ISSUE TITLE
Question - Why is it more secure to enter the password in Microsoft portal instead of custom login screen?

### ISSUE THREAD

**Issue by Diego251** [AzureAD/microsoft-authentication-library-for-dotnet#1588]
According to [this](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Username-Password-Authentication), it is not recommenced to have a custom login screen, but instead user should be redirected to Microsoft login screen. But if user is not yet logged, it is also required that he/she enters the password in there too. Why is that more secure than in a custom app, assuming app would not store the password and would encrypt communication?

**Comment by bgavrilMS** [comment]
With the Username / Password flow (ROPC), your users cannot benefit from multi-factor authentication. So if your tenant admin enables 2FA, for example getting a code via SMS, your users will not be able to login (since they need to interact with a browser. Multi-factor, passwordless authentication is more secure than ROPC authentication and by designing your app correctly from the beginning, you're more likely to switch to it ...

It's also a bit more secure because: 

- Developers tend to log a lot of info, sometimes they will log passwords and tokens.
- If I have access to your box, I can take a memory dump of your app and search for the password string. MSAL will try to store the secret in memory only for a few milliseconds, before sending it over the wire. This is more of a theoretical defense of course, if an attacker has access to your machine, they can sniff out the traffic anyway....

**Comment by Diego251** [comment]
@bgavrilMS Thank you for your feedback. I understand multi-factor authentication and the other arguments, I agree with that. From the articles I am reading, seems MS would like to promote Hello, Authenticator and other mechanisms, reasons for that are clear.

I just wanted to be sure that:
1. When I am redirected to the MS sign-in page to log in with my MS account, I need to enter my password in there (provided no other authentication mechanism is available or required) and this is not passwordless.
2. In this case a custom login screen could be used (similar to  [this](https://github.com/Azure-Samples/active-directory-dotnetcore-console-up-v2) sample), as in both cases users will need to enter their password and the redirection to MS portal is not much more secure that the custom login.

**Comment by bgavrilMS** [comment]
Yes, that is fair assessment for #1. Just note that performing interactive authentication, which means opening up a browser and letting AAD handle the UI screens, will provide a better user experience. For example, AAD uses a browser session store which remembers all the logged in users, and won't re-request the password in the majority of cases. 

For #2, I am not sure I fully understand the question. Some password flows do not require a password, for example if you use FIDO tokens etc. But strictly form a security perspective, if the user needs to enter a password, the password will have to be sent from the device to AAD via HTTPS. Either you do it via ROPC, or you let AAD collect it via a browser. AAD will collect it less often.

**Comment by rayluo** [comment]
On top of what Bogdan's answer, there is one more reason that makes signing-in via native browser on your Identity Provider's portal, intrinsically more secure than typing your password inside a 3rd-party app. In the latter case, a day-1 end user would have no way to make sure whether that new app is a phishing app. In that sense, the entire OAuth2 framework was largely designed to avoid end user needing to give out his/her password to an unknown app.

**Comment by Diego251** [comment]
> May I ask what you are trying to do ? Are you worried about branding / users being put off by seeing the Microsoft login screen?

Yes, this is exactly the problem. I need full custom branding (not only a logo). And after checking the options I started wondering why the redirection was required, as user will need to enter the password in MS screen anyway. For info the app will be a mobile app (Angular 8). To get familiar with MSAL, I started by trying to run the sample I linked above but I am getting the "no consent" issue (AADSTS65001), despite my admin having granted the permissions required... :/

**Comment by jmprieur** [comment]
@Diego251 : to summarize it's more secure because the user and Azure AD have a private conversation in the browser about entering credentials, doing multiple-factor authentication and other conditional access, and consenting for access to resources/web APIs.
about your white label need, did you consider Azure AD B2C? See https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-overview and in particular https://docs.microsoft.com/en-us/azure/active-directory-b2c/code-samples (which use MSAL)

**Comment by Diego251** [comment]
Thank you all for the feedback and @jmprieur for the links. I was sure it was not possible to have custom branding, will take a deeper look at that.
