### ISSUE TITLE
[Bug] Users reporting they keep having to log in

### ISSUE THREAD

**Issue by WilliamWatterson86** [AzureAD/microsoft-authentication-library-for-dotnet#1607]
**Which Version of MSAL are you using ?** 4.7.1

**Platform**
xamarin android, xamarin iOS 

**What authentication flow has the issue?**
* Desktop / Mobile
    * [X] Interactive

**Is this a new or existing app?**
The app is in production, and I have upgraded to a new version of MSAL

**Expected behavior**
Users should only have to log in once.     

**Actual behavior**
User are reporting they have to sign in again every few weeks.

**Additional context/ Logs / Screenshots**
Not sure if this is a bug or if I am missing some configuration somewhere.  Users are reporting that they keep having to sign in.  I have configured as follows in Identity Experience Framework:

`<DisplayName>Token Issuer</DisplayName>
      <TechnicalProfiles>
        <TechnicalProfile Id="JwtIssuer">
          <DisplayName>JWT Issuer</DisplayName>
          <Protocol Name="None" />
          <OutputTokenFormat>JWT</OutputTokenFormat>
          <Metadata>
            <Item Key="client_id">{service:te}</Item>
            <Item Key="issuer_refresh_token_user_identity_claim_type">objectId</Item>
            <Item Key="SendTokenResponseBodyWithJsonNumbers">true</Item>
			<Item Key="token_lifetime_secs">3600</Item>
            <Item Key="id_token_lifetime_secs">3600</Item>
            <Item Key="refresh_token_lifetime_secs">7776000</Item>
            <Item Key="allow_infinite_rolling_refresh_token">True</Item>
            <Item Key="IssuanceClaimPattern">AuthorityAndTenantGuid</Item>
            <Item Key="AuthenticationContextReferenceClaimPattern">None</Item>
          </Metadata>
          <CryptographicKeys>
            <Key Id="issuer_secret" StorageReferenceId="B2C_1A_TokenSigningKeyContainer" />
            <Key Id="issuer_refresh_token_key" StorageReferenceId="B2C_1A_TokenEncryptionKeyContainer" />
          </CryptographicKeys>
          <InputClaims />
          <OutputClaims />
        </TechnicalProfile>
      </TechnicalProfiles>
    </ClaimsProvider>`

From the config above I am expecting that if the user logs in once in the 90 days they will have a further 90 days.  So I am unsure why users are reporting that they are being forced to log in sooner than that.  Is there anything I need to do app side to enable users to stay signed in (ideally I don't even want them having to log in inside the 90 days)?  When linking Alexa to B2C I had to have the "offline_access" scope.  Is this something I need to add in here too?

**Comment by bgavrilMS** [comment]
You are right - a Refresh Token is issued with the "offline_profile" scope, which MSAL always adds. It has a lifetime of 90 days and a rolling window mechanism. So as long as your users access the app at least once in those 90 days, they should not have to re-login. 

However, please note that any changes such as the ones below will also force re-login:

- user resets password or password expires
- you increase security of your tenant (e.g. require MFA)
- conditional access policies are applied by the tenant admin
- refresh token is revoked by tenant admin

Otherwise, not really sure how to investigate this, I think we need to talk to the B2C folks to look at failed refresh_token for one of your users. @jennyf19 - any idea?

**Comment by jennyf19** [comment]
@WilliamWatterson86 This is with B2C, correct? the RT lifetime is based on policy, so maybe double check it's the right token w/the right policy that is or is not expiring on time.
Example for our su_si policy in the azure portal:
![image](https://user-images.githubusercontent.com/19942418/73694731-87bf0f80-468d-11ea-879e-6c2bebc6385c.png)

Otherwise, can you share your b2c tenant (i think you have my email) and we can check things on the aad b2c side?

**Comment by WilliamWatterson86** [comment]
Hi @jennyf19, yep this is B2C.  

We have our policies set up using Identity Experience Framework, so the XML in the original posting is how we configure the token.  

Thinking about it, it might be that we moved from policies to Identity Experience Framework in the last 2 months - so the token that was valid for the user previously would have been one from custom policies, and when they installed the new version of the app they were asked to sign in again.  

I will wait another few months and reopen this one if they continue to report it.

Thanks
