### ISSUE TITLE
OnActivityResult returning 2001/2004 instead of -1,0 or 1. Is this ok?

### ISSUE THREAD

**Issue by laurensbro** [AzureAD/microsoft-authentication-library-for-dotnet#1660]
**Which Version of MSAL are you using ?** 4.9.0 - preview with broker support for android

**Platform** xamarin android

**What authentication flow has the issue?**
* Mobile
    * [v ] Interactive
   
**Is this a new or existing app?**
c. This is a new app or experiment

**Repro**

```csharp
// Calling 
var app = PublicClientApplicationBuilder.Create(msalClientId)
                .WithAuthority(EndpointConfiguration.Authority)
                .WithRedirectUri($"msauth://********")
                .WithBroker()
                .Build();

var authResult = await app
                        .AcquireTokenInteractive(GetADScopes())
                        .WithParentActivityOrWindow(parentActivity)
                        .WithUseEmbeddedWebView(true)
                        .ExecuteAsync();

//In activity
protected override void OnActivityResult(int requestCode, Result resultCode, Intent data)
{
            base.OnActivityResult(requestCode, resultCode, data);
AuthenticationContinuationHelper.SetAuthenticationContinuationEventArgs(requestCode,
                    resultCode, //<-- should be -1, 0 or 1.
                    data);    
}
```

**Expected behavior**
resultCode is of type "Android.App.Result", should be -1, 0 or 1. 

**Actual behavior**
I'm getting values 2004 and 2001 respectively after successful or not successfully returning from "broker" (Authenticator).

Is this OK?

**Possible Solution**

**Additional context/ Logs / Screenshots**
![image](https://user-images.githubusercontent.com/19409753/75351189-ffa4e200-58a7-11ea-93a4-39adabda1d4e.png)

**Comment by bgavrilMS** [comment]
I think this is an implementation detail and you should not check the return code. MSAL will throw appropriate exceptions based on it. We have to expose this detail because the interface Android provides is `OnActivityResult(int requestCode, Result resultCode, Intent data)`

2004 in this case means OK
2001 means cancelled. 

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/ffa78894d2de58e5a1d9936f7d73cffcd254a715/src/client/Microsoft.Identity.Client/Platforms/Android/BrokerResponseCode.cs#L6

**Comment by laurensbro** [comment]
Thanks, that will do. Closing.
