### ISSUE TITLE
prompt to install broker from the store

### ISSUE THREAD

**Issue by harmjonker** [AzureAD/microsoft-authentication-library-for-dotnet#1698]
I found this (below) in the documentation, but what is needed to get Azure AD to install a broker ? We don't see that happening in our case.  

_How do you use brokers for your application?
You call WithBroker() at the construction of the application. When the user signs-in interactively, they will be prompted by Azure AD to install the correct broker from the store, depending on the conditional access policies in your organization. For subsequent sign-ins, the interactive authentication will directly use the broker instead of prompting the user for credentials._

**Comment by bgavrilMS** [comment]
This is a great question @harmjonker . There's supposedly a CA (conditional access) policy you can add that requires your users to authenticate with the broker. 

MSAL has following logic: 

- if broker is not installed, try to use a browser to login the user
- AAD will refuse this (based on CA) and will send a special message to MSAL via redirect url
- MSAL interprets this message and opens the App Store to the broker application (Broker or Company Portal) so that the user can install it

Code for this is [here](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/caf942e41670a8a1f12fe028b82654921c5aa49a/src/client/Microsoft.Identity.Client/Platforms/Android/AndroidBroker.cs#L74). 

I do not know how to add such a CA policy though and I'm not even sure this policy is generally available yet. We haven't managed to end to end test this logic, except by mocking the communication between msal and the broker. @trwalke @aiwangmicrosoft - do you know more?

**Comment by henrik-me** [comment]
@harmjonker are you using the broker in your flow?

AAD will not automatically install the broker, your app has to take advantage of the broker. If you do and the broker is not installed MSAL, will guide the user to install the broker.

@trwalke : please confirm.

**Comment by trwalke** [comment]
Yes, that is correct @bgavrilMS and @henrik-me, The broker application will not be automatically installed but MSAL should direct (Via app link) you to one of the android broker applications(either company portal or authenticator) in the app store when you try to authenticate with an account that requires conditional access. The last thing I remember regarding this was the service was not ready to perform this flow for MSAL.NET and it needed to be enabled so that AAD could send the proper app link for the broker install. @jennyf19

**Comment by jmprieur** [comment]
@trwalke @bgavrilMS : I believe this was fixed?

**Comment by trwalke** [comment]
yes
