### ISSUE TITLE
Back Button on Login oAuth throws access denied error code 

### ISSUE THREAD

**Issue by aprilPE** [AzureAD/microsoft-authentication-library-for-dotnet#1736]
**Which Version of MSAL are you using ? 
.Net 4.9

**Platform**
Net45

**What authentication flow has the issue?**
* Desktop / Mobile
    * [X] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

Other? - please describe;

**Is this a new or existing app?** B
The app is in production, I haven't upgraded MSAL, but started seeing this issue

**Repro**
From my app, calling AcquireTokenInteractive so the user can login to their microsoft account and grant access to my app.   If the user clicks the close button (X) then it returns error code 'authentication_canceled' and I know the user cancelled the action.    The problem is if the user hits the back button on the sign in to your account page or cancel on the page granting permssions, does not return the same error code.  Clicking back generates error 'access_denied' and clicking cancel generates error code 'consent_required'.   

```csharp
Calling AcquireTokenInteractive
```

**Expected behavior**
Both the back and cancel options are cancelled actions to me and would like to see those also return the error code 'authenication_canceled'.   I don't want to swallow the other errors on the app side as those could be legit errors for other reasons. 

**Actual behavior**
unexpected errors thrown

**Possible Solution**

**Additional context/ Logs / Screenshots**

**Comment by bgavrilMS** [comment]
This was discussed with the Identity leads a few days ago. It has been agreed that MSALs can translate the "access_denied" error into the "user_cancelled" error, since from the application consuming MSAL "access_denied" is not materially different than "user_cancelled", but it is confusing. The orginal intent of "user_denied" was to show that "the user denied authentication", e.g. by clicking "back". 

@jmprieur @henrik-me - not a breaking change in the strict sense of semver, I propose we take it without major version bump.

**Comment by aprilPE** [comment]
As long as I know access_denied and consent_required are not thrown in any other scenarios, then I am ok with looking for these specific error codes.

**Comment by bgavrilMS** [comment]
I believe `consent_required` can also be created if the user refuses to consent the scopes that you ask for. So it's a somewhat different use case ...

**Comment by aprilPE** [comment]
If they consent but then later remove that consent, is consent_required the error message thrown when next log attempt is made by my application?

**Comment by bgavrilMS** [comment]
I'm sorry @aprilPE , I don't know the answer to that question. Consent is handled by the AAD service itself, not by the SDKs. The SDKs only pop-up a browser. Perhaps you can experiment a bit with this yourself? 

I would expect that if a user removes consent, the following will happen: 

1. AcquireTokenSilent will continue to work for about 1h, since Access Tokens are not re-verified 
2. AcquireTokenSilent will throw `MsalUiRequiredException` after about 1h, since the refresh token cannot be used to acquire a new access token
3. AcquireTokenInteractive will guide the user to the consent screen again, so that they can re-consent.

**Comment by aprilPE** [comment]
thanks.  I'll try it out and let you know.

**Comment by jmprieur** [comment]
Closing as this was answered
