### ISSUE TITLE
[Question] Pre fill the last logged in user name while login in Xamarin forms

### ISSUE THREAD

**Issue by soooraj** [AzureAD/microsoft-authentication-library-for-dotnet#1784]
I am using **Microsoft.Identity.Client** in Xamarin Forms app for Azure AD b2C authentication.
I have a doubt related to this,

Is there anyway I can pre fill the last logged in user name in username field?

>   var result = await authenticationClient.AcquireTokenInteractive(_settings.Scopes)
>                     .WithParentActivityOrWindow(ParentActivityOrWindow)
>                     .WithPrompt(Prompt.ForceLogin)
>                     .WithUseEmbeddedWebView(true)
>                     .ExecuteAsync();

I am using the above code for login.

Please help.

**Comment by bgavrilMS** [comment]
Firstly, you need to remove `.WithPrompt(Prompt.ForceLogin)`. This causes the server to ignore the browser cookies and force re-authentication. In fact, with B2C, it is recommended that you do not try to customise the authentication experience using prompts. 

If this doesn't work, note that the embedded webview which you use isn't great at remembering user state. Do you need to use an embedded webview? A system webview (i.e. the default browser) will provide the best user experience, but it's a little bit more complicated to setup because you need to provide a redirect uri. All described [here](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Android-system-browser)

**Comment by soooraj** [comment]
Is it possible to pass as an additional parameter ? and assign the user name back to the field?

**Comment by bgavrilMS** [comment]
You can try to use `.WithLoginHint("soooraj@contoso.com")`. I am not sure this works on B2C, but it might.
