### ISSUE TITLE
[Bug] libc.dylib exception when authenticating on Mac

### ISSUE THREAD

**Issue by charlesroddie** [AzureAD/microsoft-authentication-library-for-dotnet#1834]
**Which Version of MSAL are you using ?**
Microsoft.Identiy.Client 4.13.0

**Platform**
Xamarin.Mac

**What authentication flow has the issue?**
Desktop / Mobile Interactive

**Is this a new or existing app?**
The app is in production

**Repro**

```fsharp
async{
    let pca // IPublicClientApplication
        = ... 
    let atipb = // AcquireTokenInteractiveParameterBuilder
        pca.AcquireTokenInteractive(scopes)
            .WithParentActivityOrWindow(parentActivityOrWindow) // null on mac
    let! ar = tokenBuilder.ExecuteAsync()
    ...
}
```

**Expected behavior**
Login flow starts in a popup.

**Actual behavior**
Exception is thrown, with message:
```
libc.dylib assembly:<unknown assembly> type:<unknown type> member:(null)
```

This error occurs on about 1/3 of end-user mac systems, making our product unusable on those systems. We have not reproduced it internally. It seems to be system-dependent.

**Comment by jennyf19** [comment]
@bgavrilMS can you take a look at this?

**Comment by bgavrilMS** [comment]
I'm not sure what is happening, it may be a Mono issue (so you can try to use the latest Xamarin SDK or enquire about this to the Xamarin folks). 

More [logs ](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging) would help to get a better idea of where the problem comes from.

I see some SO questions somewhat related to this: https://stackoverflow.com/questions/59986429/xamarin-mac-https-localhost-httplclient

**Comment by charlesroddie** [comment]
Thanks for the link.

We fixed the probem by adding to Entitlements.plist:
```
<key>com.apple.security.cs.allow-dyld-environment-variables</key>
```
and to Info.plist:
```
<key>LSEnvironment</key>
<dict>
	<key>DYLD_FALLBACK_LIBRARY_PATH</key>
	<string>/usr/lib</string>
</dict>
```

**Comment by bgavrilMS** [comment]
Thank you very much for following up @charlesroddie
