### ISSUE TITLE
Port handling in MSAL in case HTTP protocol is not enabled?

### ISSUE THREAD

**Issue by nimehta2010** [AzureAD/microsoft-authentication-library-for-dotnet#1842]
So I have been using MSAL library for authentication on netCore desktop app. Can you let me know how to handle following scenarios. I am using interactive auth which lands you on browser - 

1. What if the port is not available for communication
--
2. What if the HTTP protocol is not enabled in Windows Server machine

**Comment by jennyf19** [comment]
@bgavrilMS can answer this! thx.

**Comment by bgavrilMS** [comment]
1. If you configure a redirect uri of `http://localhost` then MSAL will automatically find a free port that you can use. If however you configure a redirect uri of `http://localhost:1234` then port 1234 will be used. Unless you have a specific requirement, I would let MSAL find a port. Otherwise, you can use the second option and do your own port management

2. OAuth2 protocol is designed to work over HTTP (HTTPS really) - to quote the [spec ](https://tools.ietf.org/html/rfc6749)

` This specification is designed for use with HTTP ([RFC2616]).  The
   use of OAuth over any protocol other than HTTP is out of scope.`

I'm not sure this is the question you were intending to ask though. Are you asking if it is possible for the OS to reject HTTP calls to localhost? I am not sure if this is possible, socket communication is a pretty basic communication mechanism. 

But if this is a concern, note that we do plan to bring an embedded browser to .net core, where the redirect uri doesn't really matter: 

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1398

**Comment by syedhamjath** [comment]
@bgavrilMS  I'm using Azure Data studio and I would like to know if we can specify the redirect port address for MSAL?
