### ISSUE TITLE
[Bug] On some tenants, AcquireTokenSilent makes 2 calls to AAD instead of 1 on Win10 because of PKAuth

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#1848]
**Which Version of MSAL are you using ?**
4.14

**Platform**
.net, .net core, probably the rest as well

**What authentication flow has the issue?**
ATS, probably other flows as well

**Repro**

This sometimes repros for accounts in the Microsoft tenants.

**Expected behavior**
When calling AcquireTokenSilent , MSAL should probably not advertise that it can perform PKAuth if on an unsupported OS like Win 10.

**Actual behavior**
- MSAL [always adds the "I can perform PKAuth" header ](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/5c318c0ce4b145dc273a9416d0540ddfeaf13c6b/src/client/Microsoft.Identity.Client/OAuth2/TokenClient.cs#L162) 
- AAD sometimes responds with a 401  (i.e. challenges MSAL to provide the key)
- MSAL can't find the key (because it can't extract it on Win 10) and sends a "Please bypass PKAuth, I can't handle this" message back to AAD
- Authentication continues

The problem is that we've performed an extra call just to tell AAD that we can't fetch the PKAuth key.

**Possible Solution**
Only advertise that MSAL can perform PKAuth on supported OSes (Win 8) ?

**Comment by bgavrilMS** [comment]
I'm not sure if this is the expected behavior on Win 10 ... I don't understand why we need to advertise that we can perform PKAuth just to respond with a "We can't perform PKAuth" when challenged.

**Comment by bgavrilMS** [comment]
@trwalke

**Comment by trwalke** [comment]
There are cases where conditional access policies require device authentication and the client is unable to perform them due to various limitations. Because of this, PKey auth has the ability to bypass the device auth challenge if the client is unable to perform it. Therefore, PKey auth will allow clients to attempt to bypass device auth challenges so that AAD can present another authentication path in these scenarios. 

Discussed offline with @bgavrilMS
