### ISSUE TITLE
Upgrade Web Authentication Broker internal rendering engine from IE11 to Edge

### ISSUE THREAD

**Issue by koenvd** [AzureAD/microsoft-authentication-library-for-dotnet#1858]
For UWP the WebAuthenticationBroker is used for authentication here https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/b2e974de7211a3749e48cb64fa70e6c05c3b40ff/src/client/Microsoft.Identity.Client/Platforms/uap/WebUI.cs#L86.

However when attempting an OAuth flow it seems like some platforms did start blocking IE11 as a secure client (an example is Salesforce Lightning Instances) which causes the OAuth flow to fail.

The user agent of the Broker is still `Mozilla/5.0 (Windows NT 10.0; Win64; x64; Trident/7.0; MSAuthHost/1.0; rv:11.0` which flags it as IE based.

Are there any plans to update the rendering engine of the broker to Edge?

**Comment by jmprieur** [comment]
The  WebAuthenticationBroker is a Windows component. It would evolve with Windows.
We are looking at using WAM.

**Comment by koenvd** [comment]
Are you aware of a better place to follow up a possible upgrade of WebAuthenticationBroker component by Microsoft @jmprieur ?

I think the same argument might hold for the .net implementation of this library where a `WebBrowser` control is used that is still running on IE11 ...

**Comment by bgavrilMS** [comment]
For .net classic, we use WebBrowser control, which is really old, but we need it because we target .NET 4.5. You CAN change the underlying browser engine used by setting a registry key (see details [here](https://stackoverflow.com/questions/38514184/how-can-i-get-the-webbrowser-control-to-show-modern-contents))

For .net core, we currently do not support webviews / embedded browser. But we are planning on using smth like WebViewControl (details [here](https://blogs.windows.com/msedgedev/2018/05/09/modern-webview-winforms-wpf-apps/))

For UWP, the plan is to move to WAM - tracking issue https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/643. It's a lot of work, but it is high priority. 

You could try to see if the registry trick works on UWP as well ?
