### ISSUE TITLE
[Feature Request] Make it easier for developers to enable "SSO" on UWP

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#1901]
**Is your feature request related to a problem? Please describe.**
By default, UWP web ui (WAB) does not remember the previous logged in user.
To enable this functionality, users have to perform the steps described [here](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/UWP-specifics).

**Describe the solution you'd like**
In addition to using "https://sso" redirect uri and registering the `WebAuthenticationBroker.GetCurrentApplicationCallbackUri()` in the app portal, developers should also be able to use `WebAuthenticationBroker.GetCurrentApplicationCallbackUri();` as redirect uri

**Comment by tipa** [comment]
Unfortunately the "https://sso" workaround did not work for me - I had to re-type my mail address.

Could you please evaluate the use of a custom dialog like the one attached below instead of `WebAuthenticationBroker`?
It does not have the limitations mentioned [here](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/UWP-specifics). Because it uses a `WebView` control (and not a Internet Explorer view as `WebAuthenticationBroker` does) it supports SSO and works more robustly in enterprise environments (no `We can't connect to the service you need right now. Check your network connection or try this again later` problem) or for users who have the Internet Explorer uninstalled/disabled. Also, no [occasional crashes](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1098) as with the `WebAuthenticationBroker`. 
I've been using this dialog in my apps for authenticating users to Google, Dropbox and other services and I haven't had any issues with it so far.

[AuthDialog.xaml.zip](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/files/5297998/AuthDialog.xaml.zip)

**Comment by jmprieur** [comment]
@tipa 
Thanks for your suggestion. We plan to move to use WAM, on Windows 10. Would that solve your issue? (I would think so).

cc: @bgavrilMS

**Comment by tipa** [comment]
I never worked with WAM so I don't know if that would solve all those problems - sorry.
If it solved the SSO problem, why is this issue still open? :)
When are you planning to move to WAM?

**Comment by bgavrilMS** [comment]
Hi @tipa - I am currently working on it, and would like to release a first version (in some sort of preview) pretty soon, 1-2 weeks.

**Comment by bgavrilMS** [comment]
I'm happy to send out a preview build if you'd like to try @tipa, things are more or less final on UWP.

**Comment by tipa** [comment]
Sounds great, would love to try it out and give feedback

**Comment by bgavrilMS** [comment]
Hi @tipa - I have published a [preview MSAL package with WAM support](https://www.nuget.org/packages/Microsoft.Identity.Client/4.20.0-wampreview1) and added some documentation and some questions to this page: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/WAM

Please let me know if this all works for you or not.

**Comment by tipa** [comment]
Thanks for the preview - I just tried it out. I had to call `WithBroker()` for the new UI to come up.
I was presented a login screen with the accounts available on my Windows installation. Once I clicked my main account, I had to enter my PIN, then an exception was thrown: 
```
MSAL.UAP.4.20.0.0.MsalServiceException: 
        ErrorCode: wam_msa_internal_error 
Microsoft.Identity.Client.MsalServiceException: Broker response returned error: WAM Error Microsoft.Identity.Client.Platforms.Features.WamBroker.MsaPluginThe application requesting authentication tokens is either disabled or incorrectly configured.
onecoreuap\shell\cloudexperiencehost\onecore\app\msa\core\TokenProviderExecutor.cpp(1060)\MicrosoftAccount.TokenProvider.Core.dll!00007FF9179323B7: (caller: 00007FF91796D71D) Exception(1) tid(3e9c) 80860003 The application requesting authentication tokens is either disabled or incorrectly configured.
```
Did I forget to configure something else?

Apart from that, I am unsure if I would switch to WAM for my apps because:
- when adding a new account, it will also be added into the accounts list on Windows. It could be that I only want to log in with that account into the app only and have no traces of it anywhere else. I also know of users who don't want to add any Microsoft account to their Windows so that could be an issue for them
- Users could remove the account from the "accounts" list in Windows (e.g. because of the reason mentioned above) in which case the login in my apps would stop working too, right?
- I could imagine that in enterprise environments, administrators could disable the option to add an additional (private) account to the Windows accounts list, preventing the user to use his private account in my apps. Or is that not the case?

It is very good to have the option to use WAM as an alternative login method and I will further evaluate if I will make it the default in my apps, but I would still suggest to have an alternative for the "traditional login" and use something like my suggested auth dialog instead of the faulty `WebAuthenticationBroker`

**Comment by bgavrilMS** [comment]
For the error ... did you register the redirect URI as described? Can you login with a work (AAD) account interactively?

For adding the account to Windows, this is interesting. I haven't tested this path. I only tried adding an AAD account, for which I can see this screen (basically asking me to add the account to Windows or use it just for this app).

![image](https://user-images.githubusercontent.com/12273384/94674574-4bbd7680-0310-11eb-847c-380a30db13f4.png)

**Comment by tipa** [comment]
Sorry, haven't seen your first comment before I started to test the new version. After adding the redirect uri and waiting ~10 minutes it worked.

This is the path I go through when adding a new account:

-------------
![image](https://user-images.githubusercontent.com/2863198/94675971-e02cd680-031a-11eb-93d9-2e82b6f0a8fc.png)

-------------
![image](https://user-images.githubusercontent.com/2863198/94675986-e58a2100-031a-11eb-8b3e-5a8f1571b1e8.png)

-------------
![image](https://user-images.githubusercontent.com/2863198/94676100-1b2f0a00-031b-11eb-9199-7a8e9c07cd10.png)

-------------
![image](https://user-images.githubusercontent.com/2863198/94676496-b7591100-031b-11eb-9b8f-fb500ad17cf4.png)

-------------
![image](https://user-images.githubusercontent.com/2863198/94676201-3f8ae680-031b-11eb-910b-00d165b3035a.png)

-------------
<<< Dialog asking for scopes >>>

**Comment by bgavrilMS** [comment]
Ok, great, thanks @tipa, this is very helpful. I'll talk to the WAM guys to see if there's a way to avoid adding the MSA account to Windows accounts (somehow I doubt it). And I'll rethrow that "internal" exception to give a better message.

Note that if you use "organizations" or a tenanted authority, you will not see the "add new MSA account" option.

**Comment by bgavrilMS** [comment]
As for adding a new browser control, we have it on our backlog to add support for https://docs.microsoft.com/en-us/microsoft-edge/webview2/ in .NET Fx / Core. I see that this control will also be available in WinUi 3, but I am not sure this helps you?

**Comment by tipa** [comment]
I am currently using the [WinUI NuGet package](https://www.nuget.org/packages/Microsoft.UI.Xaml) in my UWP apps so if that means the WebView2 will be available in MSAL for UWP, that would probably help.

**Comment by bgavrilMS** [comment]
Hi @tipa, coming back to this to better understand your concerns...

`when adding a new account, it will also be added into the accounts list on Windows. It could be that I only want to log in with that account into the app only and have no traces of it anywhere else. I also know of users who don't want to add any Microsoft account to their Windows so that could be an issue for them`

Please note that WAM does not add the account to Windows, but to the "Accounts Used by other Apps". The experience is a bit different between MSA accounts and Work and School accounts, but essentially when you use an MSA account, it becomes an "SSO account", i.e. users can utilize this account for logging in to other apps. Whereas with Work and School account, user has the option of saying "account is only for this app". 

![image](https://user-images.githubusercontent.com/12273384/96008482-84447080-0e37-11eb-8254-bb73fcaa1acf.png)


`Users could remove the account from the "accounts" list in Windows (e.g. because of the reason mentioned above) in which case the login in my apps would stop working too, right?`

When the app calls"RemoveAccount", we will sign out meaning - remove all access tokens etc. and removing non-SSO accounts. The other accounts (SSO accounts) cannot be removed by apps. 
In case the user removes the account from Windows (i.e. from "Accounts Used by other Apps"), you'll need re-login the user interactively. App code should not change.

`I could imagine that in enterprise environments, administrators could disable the option to add an additional (private) account to the Windows accounts list, preventing the user to use his private account in my apps. Or is that not the case?`

Good point, I need to follow this up. I would hope not. 

`When adding a new account which was not set up in Windows previously, the auth process can become very tedious. In my test, Windows showed numerous dialogs about setting up Windows Hello etc:`

Yes, the experience is tedious the first time. The thinking here is that most users will have this already set-up. Also, after going through all this process, the account becomes SSO account (unless user explicitly denies this), and other apps can login the user with a very light process.

`Next preview`
The major improvement that I want to add to WAM integration is to allow logging in with the DEFAULT Windows User. WAM has this concept of "default user" in most cases, whereas MSAL and other brokers (Authenticator etc.) do not have this concept. So the login flow could be smth like: 

- user opens app and finds themselves already logged in with Windows account (MSA or Work / School account, depending on how Windows is setup and depending on authority - "common", "organizations", "consumers")
- if user does not want to utilize this account, they can "switch" i.e. invoke the account picker where they can either choose another Windows account or enter a new one. 

Please keep the feedback coming.

**Comment by tipa** [comment]
Thanks for this explanation!

> In case the user removes the account from Windows (i.e. from "Accounts Used by other Apps"), you'll need re-login the user interactively. App code should not change.

I could image that this could lead to some confusion and users wondering why the app doesn't work any more, just because they changed something "in Windows". This could be a reason why I would rather stick with the WebView login where the credentials cannot be removed outside the app (I know there's still ways to invalidate the credentials, by changing the account password etc.)

> The major improvement that I want to add to WAM integration is to allow logging in with the DEFAULT Windows User. WAM has this concept of "default user" in most cases, whereas MSAL and other brokers (Authenticator etc.) do not have this concept. So the login flow could be smth like:
> * user opens app and finds themselves already logged in with Windows account (MSA or Work / School account, depending on how Windows is setup and depending on authority - "common", "organizations", "consumers")

In my app I have the requirement that the user is not automatically logged in to any account, he/she should always be able to pick an account manually. As long as this "auto-login" is optional, this would be no problem for me.

**Comment by bgavrilMS** [comment]
Thanks @tipa 

As for a better WebView, I don't think we'll get to this anytime soon as we need to finish WAM integration and then adding WebView2 on .NET classic and .NET core (the existing browser doesn't support FIDO keys). 

You could have a look at using the [extensibility point ICustomWebUi](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identity.client.extensibility.icustomwebui?view=azure-dotnet) to pop up a WinUI powered WebView2 browser yourself.

**Comment by tipa** [comment]
> You could have a look at using the [extensibility point ICustomWebUi](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identity.client.extensibility.icustomwebui?view=azure-dotnet) to pop up a WinUI powered WebView2 browser yourself.

Ha, I did not know about that possibility! Seems like this is exactly what I was looking for :)

**Comment by bgavrilMS** [comment]
Currently the general approach is to use WAM, which we will release shortly. This will become the recommended flow. A future major version will enable WAM by default.

#643
