### ISSUE TITLE
re-authenticate behavior

### ISSUE THREAD

**Issue by harmjonker** [AzureAD/microsoft-authentication-library-for-dotnet#1987]
We are rolling out multiple MSAL.net ( MS Authenticator broker based ) apps on Android to many users now and we see different behavior with respect to when users have to authenticate for apps:
- some people have to reauthenticate for every new MSAL.net converted app that is installed on their device, where we would expect one to have to authenticate only for the first app, but then the account is created and reauthentication for new apps should not be needed
- some people have to reauthenticate or reselect their account every day again, where we would expect this to happen only after password reset/change or  local account removal etc. but not every day again

What is the intendend behavior? Do we need admin consent for apps ? May Azure AD policies cause these behavior?

**Comment by bgavrilMS** [comment]
Hi @harmjonker, 

Because MSAL works with scopes, not with resources, consent may be required. You can however pre-consent, just log in as a tenant admin in the Azure portal, and you will have the option of preconsenting. 

As for the fact that users have to re-authenticate on a daily basis, there is a new CA policy that could explain this - the "sign in frequency" - this requires the user to actually re-authenticate every X hours / days, although I am not sure what the broker behaviour is.

![image](https://user-images.githubusercontent.com/12273384/90419832-0a01a500-e0af-11ea-9372-8f25cefc52db.png)
 
Barring this, I suggest you capture incident reports from an affected user from Authenticator and opening a support case (I believe they are free, although a bit hard to find in the portal), as this would no longer be an MSAL issue.

**Comment by timdriever** [comment]
Our issue can be reproduced on different Samsung smartphones and happens when both phone's power saving mode and Authenticator optimizations are enabled. Authenticator appears to be unable to retrieve a new token because network calls are blocked. There is wifi on the phone. Is there a workaround available for this?

Adb Logging:

```
08-26 08:38:35.640 13917 13943 I SharedPreferencesAccountCredentialCache:  [2020-08-26 06:38:35 - {"thread_id":"6268","correlation_id":"525e1bdc-ddbe-4b7e-8afe-721247d3fedc"}] Credential was removed? [true] Android 29
08-26 08:38:35.641  4710  5064 D ConnectivityService: filterNetworkStateForUid() uid: 10292, pi, nd: 13917
08-26 08:38:35.641  4710  5064 D ConnectivityService: filterNetworkStateForUid() uid: 10292, pid: 13917etworkInfo: [type: WIFI[], state: DISCONNECTED/BLOCKED, reason: (unspecified), extra: (none), failover: false, available: true, roaming: false]
08-26 08:38:35.642  4710  5064 D ConnectivityService: Returning BLOCKED NetworkInfo to uid=10292
08-26 08:38:35.642 13917 13943 I BrokerLocalController:acquireTokenSilent:  [2020-08-26 06:38:35 - {"thread_id":"6268","correlation_id":"525e1bdc-ddbe-4b7e-8afe-721247d3fedc"}] No access token found , but RT is available. Android 29
08-26 08:38:35.644 13917 13943 I BaseController:renewAccessToken:  [2020-08-26 06:38:35 - {"thread_id":"6268","correlation_id":"525e1bdc-ddbe-4b7e-8afe-721247d3fedc"}] Renewing access token... Android 29
........
........
08-26 08:38:35.690 13761 13901 I         : (False) MSAL 4.17.1.0 MSAL.Xamarin.Android 29 [08/26/2020 06:38:35] Android Broker Silent call result - success? False.
08-26 08:38:35.699 13761 13901 W         : (False) MSAL 4.17.1.0 MSAL.Xamarin.Android 29 [08/26/2020 06:38:35] Android Broker Silent call failed. This usually means that the RT cannot be refreshed and interaction is required. BundleResult: Bundle[{broker_result_v2={"cached_at":0,"broker_error_code":"device_network_not_available","broker_error_message":"Connection is not available to refresh token","broker_exception_type":"com.microsoft.identity.common.exception.ClientException","expires_on":0,"ext_expires_on":0,"http_response_code":0,"serviced_from_cache":false,"success":false}, broker_request_v2_success=false}] Result string: {"cached_at":0,"broker_error_code":"device_network_not_available","broker_error_message":"Connection is not available to refresh token","broker_exception_type":"com.microsoft.identity.common.exception.ClientException","expires_on":0,"ext_expires_on":0,"http_response_code":0,"serviced_from_cache":false,"success":false}
```

**Comment by harmjonker** [comment]
We are experiencing serious problems with the apps that use MSAL.net and Authenticator for getting access tokens due to this optimization functions. We are now telling the end users to turn off optimization in MS Authenticator to keep things working.  But we really would like to know what is happening and how to deal with this.
What is your advice on this power saving mode and the Authenticator optimization setting ?  And do you see any improvements through msal.net or is this entirely outside control of you?

**Comment by trwalke** [comment]
Hello @harmjonker , this is a well known issue for brokered authentication on android. The background communication can be impacted by the optimization settings in the OS. There should be a menu option in the authenticator to make this easy.

This is entirely outside the control of MSAL.NET and the mechanism that MSAL uses to communicate with the broker should not be affected by power optimization. However, you will still need to disable power optimization to allow the broker to connect to AAD I believe.

Unfortunately, there is no way around this at the moment so you will need to inform users to disable the power optimization.
@rpdome @kreedula any input on this or documentation that details this scenario further?

**Comment by trwalke** [comment]
@harmjonker  Please reopen if needed.
