### ISSUE TITLE
[Feature Request] More logging for IWA

### ISSUE THREAD

**Issue by willfiddes** [AzureAD/microsoft-authentication-library-for-dotnet#2011]
**Is your feature request related to a problem? Please describe.**
Troubleshooting issues during IWA are difficult. In most cases the federated service may return a error message or a firewall/proxy/gateway may return an error that is not in a format in which MSAL can interpret and throws a ParsingWsMetadataExchangeFailed or ParsingWsTrustResponseFailed

**Describe the solution you'd like**
MSAL verbose logging should output the response. In these scenarios, its always challenging to use a capture tool like Fiddler because Fiddler changes the interaction behavior with the federated service when using IWA. We should also log the successful SAML response for the same reason. We can't always use a Http Capturing tool and we need to see the response from the federated service after IWA fails or succeeds.

**Describe alternatives you've considered**
There are no alternatives. 

**Additional context**

**Comment by bgavrilMS** [comment]
@willfiddes - we are hesitant to log the requested messages because it may contain sensitive data. It's a big security problem to log tokens and other such pieces of data. 

We had an improvement to add the WS trust response in the exception message in case parsing fails - see https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/commit/761941679a620724b9ee2885d553ed24bcb33d24

Note that we do [expose ](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-net-provide-httpclient)the HttpClient so you can capture the interaction that way. Would it help?

**Comment by jmprieur** [comment]
@willfiddes : do you think that customers who need more details could leverage the HttpClient customization?

**Comment by bgavrilMS** [comment]
Please see the https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Integrated-Windows-Authentication troubleshooting for details. 

You can capture HTTP traffic via `WithHttpClientFactory`, we do it all the time in tests. 

Anyway recommendation is to use WAM instead. https://aka.ms/msal-net-wam
