### ISSUE TITLE
[Feature Request] Get rid of the ref assembly / bait and switch technique

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#2100]
# Why?

Ref assemblies are an exotic nuget feature which are unsupported by older tools and by custom build systems:

Example customer problems:

- Azure Web App service 
- NGen tool https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2099
- CoreXT build system

Internal problems: 

- build is slowed down (by how much ? TBD)
- most tools that integrate with build system do not work (some will not still not work because of msbuild.sdk.extras) - e.g. tool to detect API breaking changes

# How?

Throw `PlatformNotSupportedException` instead. This is not a breaking change as APIs will be added.

## What would we be giving up?

```csharp
var app = ConfidentialClientApplicationBuilder().WithSecret()...;
```

1. If your project is mobile, you won't be able to type this at all - it simply does not exist.
2. If your project is `NetStandard` but at runtime you use mobile, you get a nice `PlatformNotSupportedException` with an explantation

By removing the "Bait and Switch" / ref assembly trick, we give up point 1 above. On mobile, people would see all the CCA hierarchy and be able to call into it, experiencing `PlatformNotSupportedEx`. Point 2 above still holds.

## Affected areas:

- CCA builder on mobile (CCA object and all the AcquireToken* methods) - throw PlatformNotSupportedException
- some IAppConfig settings ... ignore the settings where not supported
- WithIosKeychainSecurityGroup ... ignore on other platforms
- WithBroker ... throw or ignore? probably ignore.
- WithUseCorporateNetwork - ignore on other platforms
- WithParentActivityOrWindow + object - expose on all platforms
- WithParentActivityOrWindow + Android.Activity / iOS.ViewController / IWin32Window / IntPtr - no change, keep as is.
- cache hooks on mobile - throw
- MigrationAid small changes - but is this really still needed? Can we remove it without incurring a breaking change? I imagine the number of people on MSAL 3.x is very small.

# Next steps

- evaluate if build tools can be better integrated into MSAL without ref assembly

**Comment by jmprieur** [comment]
Arguably:
- CCA build on UWP could be useful for the kiosk scenarios that is `AcquireTokenForApp` (probably on android and iOS as well. Think of a tablet that displays the weather?). However we'd probably not want customers to use `AcquireTokenByAuthorizationCodeFlow` or `AcquireTokenOnBehalfOf` which don't make sense in mobile/desktop
- cache hooks on mobile could be expose (we had some requests on Android so that customers can do their own encryption. This could be a workaround to doing the encrypt at rest)

Something we could possibly do is introduce new interfaces if exposing too much is a real concern for instance:
- `IDesktopOrMobileConfidentialClientApplication`, which would only expose `AcquireTokenForClient` (and would be implemented by the `ConfidentialClientApplication` class.
- `IApplePublicClientApplication`, which could expose Apple only members and hide the non-apple ones (they might have to have a set of companion interfaces for the IConfig etc ...

**Comment by bgavrilMS** [comment]
Fixed with https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/2183
