### ISSUE TITLE
IO_Error Unable to perform cloud discovery

### ISSUE THREAD

**Issue by shristikatiyar** [AzureAD/microsoft-authentication-library-for-dotnet#2116]
**Which Version of MSAL are you using ?**
4.17 (Also seen in 4.20)

**Platform**
Mobile android

**What authentication flow has the issue?**
* Desktop / Mobile
  Interactive 

**Is this a new or existing app?**
The app is in prduction and we have migrated from ADAL to MSAL

**Repro**
Few User are complaining  to us  that they are not able to signin , after investigating into logs, the error shown in the 
logs is with error code AzureAD graph Authentication error: Broker response returned error: Unable to perform cloud discovery. Exception : MSAL.Xamarin.Android.4.17.0.0.MsalServiceException: 
	ErrorCode: io_error
Microsoft.Identity.Client.MsalServiceException: Broker response returned error: Unable to perform cloud discovery

**Expected behavior**
This error should not come or any change which can prevent this error from coming.
**Actual behavior**
signin Failure with errorcode io_error

**Additional context/ Logs / Screenshots**
[O365MobileAppLog (99).txt](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/files/5400938/O365MobileAppLog.99.txt)
6ea02383-b134-4d84-bf7b-2da8f2c77c00 - correlation Id

**Comment by bgavrilMS** [comment]
@shristikatiyar - to me this looks like some network IO failure. But in any case, this is an Authenticator issue, please open ICM with these details for them. MSAL is only responsible for retrieving the underlying error. 

@henrik-me , @jmprieur - we should liase with MSAL.Android team so that they provide a list of possible broker errors. I assume scenarios like network being down are already documented.
