### ISSUE TITLE
[Bug] Interactive Brokered authentication with Android not working with versions 4.20.0 and above

### ISSUE THREAD

**Issue by bemartin** [AzureAD/microsoft-authentication-library-for-dotnet#2133]
**Which Version of MSAL are you using ?**
MSAL 4.20.0, MSAL 4.20.1, MSAL 4.21.0, MSAL 4.21.1

**Platform**
Xamarin Android

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

Other? - please describe;

**Is this a new or existing app?**
The app is in production, and I am working on upgrading to a new version of MSAL

**Repro**

```csharp
return await ClientApplication
    .AcquireTokenInteractive(scopes)
    .WithAuthority(authority)
    .ExecuteAsync();
```

**Expected behavior**
The broker is launched, the user selects the account to use, control is returned to the calling application

**Actual behavior**
Our application is sent to the background and nothing else happens

**Additional context/ Logs / Screenshots**
Without any changes to our code, this works fine with MSAL 4.19.0 but fails with any version after that. We are currently running 4.19.0 in production.

The last logs we are seeing from our app are:
```
10-23 14:47:09.358: MSAL 4.21.1.0 MSAL.Xamarin.Android 29 [10/23/2020 21:47:09] ****** Starting D:\a\1\s\src\client\Microsoft.Identity.Client\Platforms\Android\Broker\AndroidBrokerHelper:ValidateBrokerRedirectURI
10-23 14:47:09.373: MSAL 4.21.1.0 MSAL.Xamarin.Android 29 [10/23/2020 21:47:09] ****** Finished D:\a\1\s\src\client\Microsoft.Identity.Client\Platforms\Android\Broker\AndroidBrokerHelper:ValidateBrokerRedirectURI in 14 ms
10-23 14:47:09.532: MSAL 4.21.1.0 MSAL.Xamarin.Android 29 [10/23/2020 21:47:09] ****** Finished D:\a\1\s\src\client\Microsoft.Identity.Client\Platforms\Android\Broker\AndroidBroker:AcquireTokenInteractiveViaBrokerAsync in 246 ms
10-23 14:47:09.547: MSAL 4.21.1.0 MSAL.Xamarin.Android 29 [10/23/2020 21:47:09] ****** Starting waiting for broker response
```

Authenticator Incident ID: DRTADSE2

**Comment by trwalke** [comment]
@bemartin can you please provide the code for the broker logs?

**Comment by bemartin** [comment]
DRTADSE2

**Comment by tm-eq** [comment]
I'm having exactly the same issue on versions 4.20.0 onwards.

Log lines from the Authenticator app are as follows:

`10-24 11:40:48:694 UTC DEBUG/App: onPause MainActivity.onPause()@322 [main]
10-24 11:40:49:325 UTC DEBUG/App: onStop MainActivity.onStop()@331 [main]
10-24 11:40:49:325 UTC INFO/App: Clearing the dialog queue. DialogTaskQueue.clear()@138 [main]
10-24 11:40:58:321 UTC INFO/App: App restriction sharedDeviceMode: false LaunchActivity.queryIsSharedDeviceModeAppRestrictionSet()@57 [main]
10-24 11:40:58:345 UTC INFO/App: hasDosPreventer = false AccountStorageCustomQueries.hasMfaAccountsConfiguredForNotifications()@92 [main]
10-24 11:40:58:348 UTC INFO/App: Syncing broker accounts into accounts list SyncBrokerAccountsTask.doInBackground()@34 [AsyncTask #5]
10-24 11:40:58:354 UTC INFO/App: onResume MainActivity.onResume()@212 [main]
10-24 11:40:58:354 UTC INFO/App: Total number of received brokerAccounts: 0 SyncBrokerAccountsTask.doInBackground()@45 [AsyncTask #5]
10-24 11:40:58:355 UTC INFO/App: Total Number of AAD accounts: 0 SyncBrokerAccountsTask.doInBackground()@62 [AsyncTask #5]
10-24 11:40:58:355 UTC INFO/App: Total number of accounts to remove: 0 SyncBrokerAccountsTask.doInBackground()@86 [AsyncTask #5]
10-24 11:40:58:413 UTC INFO/App: Network Info: [type: MOBILE[LTE], state: CONNECTED/CONNECTED, reason: connected, extra: epc.tmobile.com, failover: false, available: true, roaming: false] Util$Companion.isConnected()@90 [main]
10-24 11:40:58:416 UTC INFO/App: Proxy Info is null for this connection Util$Companion.isConnected()@96 [main]
10-24 11:40:58:417 UTC INFO/App: Task CallbackDialogTask, id = MainActivityData PrivacyWe gather non-personally identifiable usage data to help us improve the app. You can turn this off in settings. Learn more in the FAQs available under the Help menu. has been put to the queue. DialogTaskQueue.enqueueTask()@58 [main]
10-24 11:40:58:417 UTC INFO/App: Proceed to showing: CallbackDialogTask, id = MainActivityData PrivacyWe gather non-personally identifiable usage data to help us improve the app. You can turn this off in settings. Learn more in the FAQs available under the Help menu. DialogTaskQueue.showTask()@86 [main]
10-24 11:40:58:622 UTC INFO/App: Show data privacy information AppDialogFragments$showDataPrivacyDialogIfNecessary$dataPrivacyDialogBuilder$2.onShow()@134 [main]
10-24 11:41:00:425 UTC INFO/App: DataPrivacyDialog button_ok was clicked AppDialogFragments$showDataPrivacyDialogIfNecessary$dataPrivacyDialogBuilder$1.onClick()@127 [main]
10-24 11:41:00:426 UTC INFO/App: Dialog task MainActivityData PrivacyWe gather non-personally identifiable usage data to help us improve the app. You can turn this off in settings. Learn more in the FAQs available under the Help menu. has finished. DialogTaskQueue.taskFinished()@123 [main]
10-24 11:41:05:940 UTC WARN/App: File not found: authenticator.txt.1 CollectLogsUtils.readFileFromInternalStorage()@100 [AsyncTask #6]
10-24 11:41:05:940 UTC WARN/App: File not found: broker.txt.1 CollectLogsUtils.readFileFromInternalStorage()@100 [AsyncTask #6]
10-24 11:41:05:943 UTC WARN/App: File not found: DID.txt.1 CollectLogsUtils.readFileFromInternalStorage()@100 [AsyncTask #6]
10-24 11:41:05:943 UTC WARN/App: File not found: brooklyn.txt.1 CollectLogsUtils.readFileFromInternalStorage()@100 [AsyncTask #6]
10-24 11:40:40:690 UTC INFO/Broker:  [2020-10-24 11:40:40 - {"thread_id":"2","correlation_id":"UNSET"}] KEY_MIGRATION_BROADCASTER_START| Called by: AUTHENTICATOR_APP_LAUNCH Android 29 Thread.run()@919 [pool-10-thread-1]
10-24 11:40:40:888 UTC INFO/Broker:  [2020-10-24 11:40:40 - {"thread_id":"1764","correlation_id":"UNSET"}] Creating BrokerClientApplication singleton instance Android 29 Thread.run()@919 [pool-10-thread-1]
10-24 11:40:40:889 UTC INFO/Broker:  [2020-10-24 11:40:40 - {"thread_id":"1764","correlation_id":"UNSET"}] Upgrade state [INCOMPLETE] Android 29 Thread.run()@919 [pool-10-thread-1]
10-24 11:40:40:890 UTC INFO/Broker:  [2020-10-24 11:40:40 - {"thread_id":"1764","correlation_id":"UNSET"}] Upgrade state [INCOMPLETE] Android 29 Thread.run()@919 [pool-10-thread-1]
10-24 11:40:40:891 UTC INFO/Broker:  [2020-10-24 11:40:40 - {"thread_id":"1764","correlation_id":"UNSET"}] Performing fallback cache migration. Android 29 Thread.run()@919 [pool-10-thread-1]
10-24 11:40:40:892 UTC INFO/Broker:  [2020-10-24 11:40:40 - {"thread_id":"1802","correlation_id":"UNSET"}] Performing cache upgrade... Android 29 Thread.run()@919 [pool-10-thread-1]
10-24 11:40:40:896 UTC INFO/Broker:  [2020-10-24 11:40:40 - {"thread_id":"1802","correlation_id":"UNSET"}] Found [0] accounts. Android 29 Thread.run()@919 [pool-10-thread-1]
10-24 11:40:40:900 UTC INFO/Broker:  [2020-10-24 11:40:40 - {"thread_id":"1802","correlation_id":"UNSET"}] Loading cloud metadata. Android 29 Thread.run()@919 [pool-10-thread-1]
10-24 11:40:40:904 UTC WARN/Broker:  [2020-10-24 11:40:40 - {"thread_id":"1802","correlation_id":"UNSET"}] Telemetry is disabled because the Telemetry context or configuration is null Android 29 Thread.run()@919 [pool-10-thread-1]
10-24 11:40:40:978 UTC DEBUG/WPJ: Connecting to WPJService to retrieve WPJ account name. WPJ(PRT) 3.3.8 WorkplaceJoinServiceProxy.getWorkplaceJoinedAccountName()@88 [pool-20-thread-1]
10-24 11:40:40:979 UTC DEBUG/WPJ: Binding to WPJService for caller uid: 10168 WPJ(PRT) 3.3.8 WorkplaceJoinServiceHandler.bindToWPJService()@150 [pool-20-thread-1]
10-24 11:40:40:983 UTC DEBUG/WPJ: The status for WorkplaceJoinService bindService call is: true WPJ(PRT) 3.3.8 WorkplaceJoinServiceHandler.bindToWPJService()@157 [pool-20-thread-1]
10-24 11:40:41:016 UTC INFO/Broker:  [2020-10-24 11:40:41 - {"thread_id":"2","correlation_id":"UNSET"}] KEY_MIGRATION_BROADCASTER| The other broker not found. Android 29 Thread.run()@919 [pool-10-thread-1]
10-24 11:40:41:018 UTC INFO/Broker:  [2020-10-24 11:40:41 - {"thread_id":"2","correlation_id":"UNSET"}] KEY_MIGRATION_BROADCASTER_END| The other broker doesn't support this operation, or there is no broker on the other side. Android 29 Thread.run()@919 [pool-10-thread-1]
10-24 11:40:41:070 UTC INFO/Broker:  [2020-10-24 11:40:41 - {"thread_id":"1764","correlation_id":"UNSET"}] No account matching broker account type exists. Android 29 Thread.run()@919 [pool-10-thread-1]
10-24 11:40:41:073 UTC INFO/Broker:  [2020-10-24 11:40:41 - {"thread_id":"1768","correlation_id":"UNSET"}] No account matching broker account type exists. Android 29 Thread.run()@919 [pool-10-thread-1]
10-24 11:40:41:553 UTC INFO/Broker:  [2020-10-24 11:40:41 - {"thread_id":"2","correlation_id":"UNSET"}] KEY_MIGRATION_BROADCASTER| New key generated. Android 29 Thread.run()@919 [pool-10-thread-1]
10-24 11:40:41:726 UTC INFO/Broker:  [2020-10-24 11:40:41 - {"thread_id":"1764","correlation_id":"UNSET"}] No account matching broker account type exists. Android 29 Thread.run()@919 [pool-10-thread-1]
10-24 11:40:41:814 UTC DEBUG/WPJ: WPJ Service is connected. WPJ(PRT) 3.3.8 WorkplaceJoinServiceHandler$WorkplaceJoinServiceConnection.onServiceConnected()@209 [main]
10-24 11:40:41:817 UTC DEBUG/WPJ: Retrieved account name from WPJ Service.  Account Name is null WPJ(PRT) 3.3.8 WorkplaceJoinServiceProxy.getWorkplaceJoinedAccountName()@90 [pool-20-thread-1]
10-24 11:40:41:818 UTC INFO/WPJ: WPJ account does not exist. WPJ(PRT) 3.3.8 WorkplaceJoinOperation.getAccount()@176 [pool-20-thread-1]
10-24 11:40:41:823 UTC DEBUG/WPJ: Device is not workplace joined. WPJ(PRT) 3.3.8 WorkplaceJoin$2.run()@259 [pool-20-thread-1]
10-24 11:40:44:878 UTC INFO/Broker:  [2020-10-24 11:40:44 - {"thread_id":"2","correlation_id":"UNSET"}] KEY_MIGRATION_BROADCASTER| Called by: AUTHENTICATOR_APP_LAUNCH | This broker already has a key. No need to migrate. Android 29 Thread.run()@919 [pool-10-thread-1]
10-24 11:40:44:883 UTC INFO/Broker:  [2020-10-24 11:40:44 - {"thread_id":"1768","correlation_id":"UNSET"}] No account matching broker account type exists. Android 29 Thread.run()@919 [pool-10-thread-1]
10-24 11:40:44:898 UTC INFO/Broker:  [2020-10-24 11:40:44 - {"thread_id":"1768","correlation_id":"UNSET"}] No account matching broker account type exists. Android 29 Thread.run()@919 [pool-10-thread-1]
10-24 11:40:44:911 UTC DEBUG/WPJ: Connecting to WPJService to retrieve WPJ account name. WPJ(PRT) 3.3.8 WorkplaceJoinServiceProxy.getWorkplaceJoinedAccountName()@88 [pool-20-thread-1]
10-24 11:40:44:912 UTC DEBUG/WPJ: Binding to WPJService for caller uid: 10168 WPJ(PRT) 3.3.8 WorkplaceJoinServiceHandler.bindToWPJService()@150 [pool-20-thread-1]
10-24 11:40:44:914 UTC DEBUG/WPJ: The status for WorkplaceJoinService bindService call is: true WPJ(PRT) 3.3.8 WorkplaceJoinServiceHandler.bindToWPJService()@157 [pool-20-thread-1]
10-24 11:40:44:997 UTC INFO/Broker:  [2020-10-24 11:40:44 - {"thread_id":"1768","correlation_id":"UNSET"}] No account matching broker account type exists. Android 29 Thread.run()@919 [pool-10-thread-1]
10-24 11:40:45:021 UTC DEBUG/WPJ: WPJ Service is connected. WPJ(PRT) 3.3.8 WorkplaceJoinServiceHandler$WorkplaceJoinServiceConnection.onServiceConnected()@209 [main]
10-24 11:40:45:024 UTC DEBUG/WPJ: Retrieved account name from WPJ Service.  Account Name is null WPJ(PRT) 3.3.8 WorkplaceJoinServiceProxy.getWorkplaceJoinedAccountName()@90 [pool-20-thread-1]
10-24 11:40:45:026 UTC INFO/WPJ: WPJ account does not exist. WPJ(PRT) 3.3.8 WorkplaceJoinOperation.getAccount()@176 [pool-20-thread-1]
10-24 11:40:45:026 UTC DEBUG/WPJ: Device is not workplace joined. WPJ(PRT) 3.3.8 WorkplaceJoin$2.run()@259 [pool-20-thread-1]
10-24 11:40:54:320 UTC DEBUG/WPJ: AuthenticationService created. Authenticator package:com.azure.authenticator this:10168 WPJ(PRT) 3.3.8 AuthenticatorService.onCreate()@64 [main]
10-24 11:40:54:602 UTC DEBUG/WPJ: No WPJ account found. WPJ(PRT) 3.3.8 BrokerUtility.initializeDeviceCertProxy()@107 [main]
10-24 11:40:54:603 UTC DEBUG/WPJ: Broker AuthenticatorService onBind. Binder calling uid: 10168 WPJ(PRT) 3.3.8 AuthenticatorService.onBind()@79 [main]
10-24 11:40:54:607 UTC DEBUG/WPJ: addAccount called  with arguments accountType:com.microsoft.workaccount package:com.azure.authenticator pid:7945 uid:7945 WPJ(PRT) 3.3.8 Authenticator.addAccount()@147 [Binder:8632_2]
10-24 11:40:54:615 UTC INFO/Broker:  [2020-10-24 11:40:54 - {"thread_id":"1751","correlation_id":"UNSET"}] MicrosoftAuthService starts to hello for package name: com.android.dynsystem Android 29 Thread.run()@919 [pool-1-thread-1]
10-24 11:40:54:616 UTC INFO/Broker:  [2020-10-24 11:40:54 - {"thread_id":"1751","correlation_id":"UNSET"}] Calling app broker protocol version: 3.0
Calling app required broker protocol version: 2.0
Broker app protocol version: 5.0 Android 29 Thread.run()@919 [pool-1-thread-1]
10-24 11:40:54:619 UTC INFO/Broker:  [2020-10-24 11:40:54 - {"thread_id":"1751","correlation_id":"UNSET"}] Connection OK
Common protocol version: 3.0 Android 29 Thread.run()@919 [pool-1-thread-1]
10-24 11:40:54:629 UTC DEBUG/WPJ: Unbinding Authenticatior service. WPJ(PRT) 3.3.8 AuthenticatorService.onUnbind()@86 [main]
10-24 11:40:54:629 UTC DEBUG/WPJ: Broker AuthenticationService onDestroy. WPJ(PRT) 3.3.8 AuthenticatorService.onDestroy()@93 [main]
10-24 11:40:54:638 UTC DEBUG/WPJ: AuthenticationService created. Authenticator package:com.azure.authenticator this:10168 WPJ(PRT) 3.3.8 AuthenticatorService.onCreate()@64 [main]
10-24 11:40:54:642 UTC WARN/Broker:  [2020-10-24 11:40:54 - {"thread_id":"2","correlation_id":"UNSET"}] WebView is already initialized. IllegalStateException is expected when setDataDirectorySuffix() is invoked Android 29 Thread.run()@919 [pool-1-thread-1]
10-24 11:40:54:643 UTC DEBUG/WPJ: No WPJ account found. WPJ(PRT) 3.3.8 BrokerUtility.initializeDeviceCertProxy()@107 [main]
10-24 11:40:54:644 UTC DEBUG/WPJ: Broker AuthenticatorService onBind. Binder calling uid: 10168 WPJ(PRT) 3.3.8 AuthenticatorService.onBind()@79 [main]
10-24 11:40:54:647 UTC DEBUG/WPJ: addAccount called  with arguments accountType:com.microsoft.workaccount package:com.azure.authenticator pid:7945 uid:7945 WPJ(PRT) 3.3.8 Authenticator.addAccount()@147 [Binder:8632_3]
10-24 11:40:54:649 UTC INFO/Broker:  [2020-10-24 11:40:54 - {"thread_id":"1752","correlation_id":"UNSET"}] MicrosoftAuthService starts to Interactive request for package name: com.android.dynsystem Android 29 Thread.run()@919 [pool-1-thread-1]
10-24 11:40:54:659 UTC DEBUG/WPJ: No WPJ account found. WPJ(PRT) 3.3.8 BrokerUtility.initializeDeviceCertProxy()@107 [Binder:8632_3]
10-24 11:40:54:661 UTC INFO/Broker:  [2020-10-24 11:40:54 - {"thread_id":"1752","correlation_id":"UNSET"}] Returning the intent for launching interactive request from MicrosoftAuthService. Android 29 Thread.run()@919 [pool-1-thread-1]
10-24 11:40:54:672 UTC DEBUG/WPJ: Unbinding Authenticatior service. WPJ(PRT) 3.3.8 AuthenticatorService.onUnbind()@86 [main]
10-24 11:40:54:672 UTC DEBUG/WPJ: Broker AuthenticationService onDestroy. WPJ(PRT) 3.3.8 AuthenticatorService.onDestroy()@93 [main]
10-24 11:40:54:708 UTC INFO/WPJ: AccountChooserActivity.onCreate is invoked. WPJ(PRT) 3.3.8 AccountChooserActivity.onCreate()@90 [main]
10-24 11:40:54:734 UTC INFO/Broker:  [2020-10-24 11:40:54 - {"thread_id":"2","correlation_id":"UNSET"}] Request from MSAL, returning MsalBrokerRequestAdapter Android 29 Thread.run()@919 [pool-1-thread-1]
10-24 11:40:54:736 UTC INFO/Broker:  [2020-10-24 11:40:54 - {"thread_id":"2","correlation_id":"UNSET"}] Constructing BrokerAcquireTokenOperationParameters from calling activity Android 29 Thread.run()@919 [pool-1-thread-1]
10-24 11:40:54:745 UTC INFO/Broker:  [2020-10-24 11:40:54 - {"thread_id":"2","correlation_id":"UNSET"}] Authorization agent passed in by MSAL: null Android 29 Thread.run()@919 [pool-1-thread-1]
10-24 11:40:58:353 UTC INFO/Broker:  [2020-10-24 11:40:58 - {"thread_id":"1833","correlation_id":"UNSET"}] No account matching broker account type exists. Android 29 Thread.run()@919 [pool-10-thread-1]
10-24 11:40:58:425 UTC DEBUG/WPJ: Connecting to WPJService to retrieve WPJ account name. WPJ(PRT) 3.3.8 WorkplaceJoinServiceProxy.getWorkplaceJoinedAccountName()@88 [pool-20-thread-1]
10-24 11:40:58:425 UTC DEBUG/WPJ: Binding to WPJService for caller uid: 10168 WPJ(PRT) 3.3.8 WorkplaceJoinServiceHandler.bindToWPJService()@150 [pool-20-thread-1]
10-24 11:40:58:428 UTC DEBUG/WPJ: The status for WorkplaceJoinService bindService call is: true WPJ(PRT) 3.3.8 WorkplaceJoinServiceHandler.bindToWPJService()@157 [pool-20-thread-1]
10-24 11:40:58:640 UTC DEBUG/WPJ: WPJ Service is connected. WPJ(PRT) 3.3.8 WorkplaceJoinServiceHandler$WorkplaceJoinServiceConnection.onServiceConnected()@209 [main]
10-24 11:40:58:641 UTC DEBUG/WPJ: Retrieved account name from WPJ Service.  Account Name is null WPJ(PRT) 3.3.8 WorkplaceJoinServiceProxy.getWorkplaceJoinedAccountName()@90 [pool-20-thread-1]
10-24 11:40:58:641 UTC INFO/WPJ: WPJ account does not exist. WPJ(PRT) 3.3.8 WorkplaceJoinOperation.getAccount()@176 [pool-20-thread-1]
10-24 11:40:58:641 UTC DEBUG/WPJ: Device is not workplace joined. WPJ(PRT) 3.3.8 WorkplaceJoin$2.run()@259 [pool-20-thread-1]`

**Comment by trwalke** [comment]
I think I may have found an issue with how we send the default prompt value to the broker which can cause this issue to occur. Will provide more details after additional testing.

**Comment by trwalke** [comment]
Fix has been identified, will be in the next release
