### ISSUE TITLE
EnablePrivateNetwork registry key

### ISSUE THREAD

**Issue by leemorris** [AzureAD/microsoft-authentication-library-for-dotnet#2162]
We have developed a UWP application that is used in an enterprise environment. Our application uses MSAL for authentication to Azure AD. The application was working fine until the recent round of security patches was applied. I found the Troubleshooting  section of your GitHub Wiki  [here](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/UWP-specifics#troubleshooting)

`HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\authhost.exe\EnablePrivateNetwork = 00000001`

The registry setting has resolved our issue, but since a UWP app can’t update the registry, we need to have it done via group policy.
Do you know of any documentation that would help convince me that there are no unintended consequences of making this change?

**Comment by jmprieur** [comment]
@leemorris : this is documentation related to WAB.
See https://docs.microsoft.com/en-us/windows/uwp/security/web-authentication-broker#debugging

**Comment by bgavrilMS** [comment]
@leemorris - the setting that you are talking about affects the WAB broker (i.e. the browser popup). WAB is a Windows Component. Since WAB runs in its own app context, you are enabling "private network" capability for it, similar to how you enable the capability for your own app, except that you don't have the ability to modify WAB's manifest. 

Please note that on UWP we have added support for WAM (Web Auth Manager), which is also a broker app. Unlike WAB, WAM is not deprecated and has a lot of benefits such as integration with Windows Hello, support for device related conditional access etc - https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/wam

If you have time to try it out, please let us know what you think about the experience. WAM will become the default auth method on Windows 10 in the future.
