### ISSUE TITLE
Update POP samples

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#2163]
- Remove the PublicClient Pop sample from the Web API incremental tutorial [native-aspnetcore-v2/4.-Console-app-calls-web-API-with-PoP](https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/tree/master/4.-Console-app-calls-web-API-with-PoP) but ...
- ... add it to the [daemon calls its own web api](https://github.com/azure-samples/active-directory-dotnetcore-daemon-v2) sample tutorial (with the Pop Wilson integration which currently in the Web API tutorial)

See integration tests for an example on how to use X509Cert as a key provider.

**Comment by jmprieur** [comment]
@bgavrilMS @trwalke @henrik-me:
Do we want to have Microsoft.Identity.Web support acquisition of Pop tokens? 
cc: @jennyf19

**Comment by jmprieur** [comment]
Marking as P1 as Pop is being removed from the public API, and this was the only sample exposing PoP Wilson.

**Comment by jennyf19** [comment]
@bgavrilMS I don't see PoP available in public client? is that correct?

**Comment by trwalke** [comment]
@jennyf19  yes. Pop is now limited to only confidential clients

**Comment by jmprieur** [comment]
@neha-bhargava : we want to add a **new folder** to the daemon sample. This new folder would be pretty much like `https://github.com/Azure-Samples/active-directory-dotnetcore-daemon-v2/tree/master/2-Call-OwnApi`, but:
- we'd call **4-Call-OwnApi-Pop**
- The service would be the same as the following: https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/tree/master/4.-Console-app-calls-web-API-with-PoP, but using App roles instead of scopes (this is a bit involved BTW)
- I propose that the client is the same as for `https://github.com/Azure-Samples/active-directory-dotnetcore-daemon-v2/tree/master/2-Call-OwnApi`, but uses Pop instead of bearer.

Why daemon? because it's easier to have a console app with confidential clients. 
We could also have a web app, but this will require feature work in MIcrosoft.Identity.Web

I'd expect this sample to be a bit complex to do. Whoever does it, don't hesitate to ping me. I think I've a pretty good idea of what needs to be done;

**Comment by jmprieur** [comment]
Proposal: 

In the https://github.com/azure-samples/active-directory-dotnetcore-daemon-v2 (.NET Core daemon) sample repo:

1. Create a new sub-folder **4-Call-OwnApi-Pop**
2. In this new folder:
   1. Copy the content of the [2-Call-OwnApi](https://github.com/Azure-Samples/active-directory-dotnetcore-daemon-v2/tree/master/2-Call-OwnApi) folder. It's a good basis for this sample. We'll modify it later
   1. copy the [Microsoft.Identity.Web.Future](https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/tree/master/4.-Console-app-calls-web-API-with-PoP/Microsoft.Identity.Web.Future) from the https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2 sample. It's the implementation of Pop for the service.

In this new **4-Call-OwnApi-Pop** folder:
3. Update the TodoList-WebApi service so that it accepts Pop tokens for this:
   3.1. reference the Microsoft.Identity.Web.Future project
   3.2. add a line `services.AddProofOfPosession(Configuration);` in the Startup.cs ConfigureServices method. See [services.AddProofOfPosession(Configuration)](https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/blob/6ec842cf05fe2245bd7ba4e32a9734b01d49dd38/4.-Console-app-calls-web-API-with-PoP/TodoListService/Startup.cs#L29) for an example of what was done in the ASP.NET Core web api sample. BTW, we might want to fix the spelling typo :)

4. Update the client to use the new Pop API instead of the bearer token 

5. Update the README.md **About the code** section. For instance in the **2-Call-OwnApi** folder the section is [About the code] (https://github.com/Azure-Samples/active-directory-dotnetcore-daemon-v2/blob/master/2-Call-OwnApi/README.md#about-the-code). Also update the [About the alternate code](https://github.com/Azure-Samples/active-directory-dotnetcore-daemon-v2/blob/master/2-Call-OwnApi/README.md#about-the-alternate-code) section of the Readme in the new folder

6. When this sample is committed and published, we'll need to update the [https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/tree/master/4.-Console-app-calls-web-API-with-PoP](https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/tree/master/4.-Console-app-calls-web-API-with-PoP) sample/folder:
- delete its content
- Have the README telling that Pop is no longer exposed in public client application, and that the new sample showing the usage of Pop is https://github.com/Azure-Samples/active-directory-dotnetcore-daemon-v2/blob/master/4-Call-OwnApi-Pop (when it exists)

7. Plan to add an issue in Microsoft.Identity.Web to also support Pop in ITokenAcquisition, or most probably better in IDownstreamApi.

**Comment by jennyf19** [comment]
@jmprieur 
[PR](https://github.com/Azure-Samples/active-directory-dotnetcore-daemon-v2/pull/100) for daemon sample - i need to test still
[PR](https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/pull/180) to remove pop sample

Related [issue in id web](https://github.com/AzureAD/microsoft-identity-web/issues/110) to add pop support

**Comment by jennyf19** [comment]
@jmprieur also, not sure about step 5, and need to test the new sample. eta 1 more day.

**Comment by jennyf19** [comment]
closing as fixed.
