### ISSUE TITLE
How to handle service down case is Azure AD B2c.

### ISSUE THREAD

**Issue by stezma** [AzureAD/microsoft-authentication-library-for-dotnet#2168]
Hi,
I am using **Microsoft.Identity.Client** version **4.22.0** in my Xamarin Forms application for Authentication. I have two questions related to handling of "The webpage is not available". case.

Qn1 : Is there any way I can retry the login request if the service / B2c is down, after a specific time interval?
Qn2: How I can comeback to the calling method if the service is down? So that I can provide a readable method to the user other than failed sign-in url.

I am calling the below methods for login and revalidating the existing token.

       
```
   var result = await _authenticationClient.AcquireTokenInteractive(_settings.Scopes)
            .WithParentActivityOrWindow(ParentActivityOrWindow)
           .WithPrompt(Prompt.ForceLogin)
           .WithUseEmbeddedWebView(true)
           .WithExtraQueryParameters(AppIdentifier)
           .ExecuteAsync();

```

```
   var accounts = await _authenticationClient.GetAccountsAsync();
                var authResult = await _authenticationClient.AcquireTokenSilent(_settings.Scopes, GetAccountByPolicy(accounts, _settings.SignInPolicy))
                 .ExecuteAsync();
```

And this is the situation I am trying to tackle.

![image](https://user-images.githubusercontent.com/38653526/98515057-c318eb00-226a-11eb-9377-f17b785f20c5.png)

Please help.

**Comment by bgavrilMS** [comment]
Hi @stezma - 

I don't think we have a good solution for this yet. The main mitigation developers use today is to [detect if the network is down ](https://docs.microsoft.com/en-us/xamarin/essentials/connectivity?tabs=android) PRIOR to making a token request.
 
Generally [timeouts in .NET ](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/cancel-async-tasks-after-a-period-of-time) world are done using the cancellation mechanism. Notice that `ExecuteAsync` accept a token. 
That said the library does not necessarily need to obey your cancellation request, either because it cannot or because the execution has reached a point where it's too late to cancel. 

I think currently we do  not react to cancellation in this case, but we probably should, by throwing an `OperationCancelledException`. Would this help?

**Comment by stezma** [comment]
Network checking will only help us to track the network outage. That we are checking already. Our main issue is B2c itself is down that case how we will handle the situation.

Could you pleas elaborate with the point `OperationCancelledException`.  Is it a new change you are proposing to  SDK or a workaround I can make on my client / xamarin code?

**Comment by bgavrilMS** [comment]
The more I think about this, I realize that maybe this should be handled on B2C server side. If they encounter a network error downstream, they can signal the error back to the app - which would close the browser and return back control to you. MSAL would throw some `MsalServerException` with `errorCode= network_down` or whatever error code B2C sends. @jennyf19 - thoughts? Could we involve our B2C friends for an opinion?

Purely on the client side, I was suggesting that all MSAL APIs have built in cancellation and timeout mechanism, it would be smth like: 

```csharp

            var cts = new CancellationTokenSource(30*1000); //30s timeout

  var result = await _authenticationClient.AcquireTokenInteractive(_settings.Scopes)
            .WithStuff(stuff)
           .ExecuteAsync(cts.Token);
```
I am not sure if this would help though in this scenario.

**Comment by bgavrilMS** [comment]
I think this is the best we can do for now. We will take this ask to B2C (@jennyf19 - can we add this to our list?)

**Comment by jennyf19** [comment]
@bgavrilMS yes, i think this is on our list of asks w/b2c. i'll mark this as external.
