### ISSUE TITLE
[Feature Request] Add telemetry on power optimization on/off/na information

### ISSUE THREAD

**Issue by jennyf19** [AzureAD/microsoft-authentication-library-for-dotnet#2277]
related to this [issue](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2144)

**Comment by bgavrilMS** [comment]
My understanding is that Content Provider mechanism does not have power optimisation issues? @trwalke to confirm.

Is this really necessary? All the workarounds and protection around power optimizations seem to amount to 2 weeks of work, which would otherwise be required to move to Content Provider mechanism, which would also improve customer behaviour. 

Also, we keep adding to telemetry, but we have no way of knowing if this is actually actionable. 

Thirdly, if we add these values to telemetry, they be will become obsolete soon (i.e. power optimization issue can be fixed with content provider or by other means). Do we have a plan to evolve telemetry to remove obsolete values? I have suggested versioning, but perhaps telemetry is already versioned with the MSAL version number. Needs confirmation on the data side.

**Comment by bgavrilMS** [comment]
Please, let's not add more to telemetry until we have dashboards etc.

**Comment by bgavrilMS** [comment]
I am also opposed to telemetry for very narrow scenarios. Telemetry is sent via headers and makes confidential client scenarios slower.
