### ISSUE TITLE
[Fundamentals] Ensure all tests runs on a release build including the UI tests

### ISSUE THREAD

**Issue by jennyf19** [AzureAD/microsoft-authentication-library-for-dotnet#2278]
**Goal:** It must be simple to answer the question, which tests have run as part of the bits we are shipping, and are the tests passing. Additionally it must be easy to detect if any tests which is supposed to run as part of the test sheet was run or not.

- [ ] Add unit test/integration tests to release yaml. 
- [ ] Ensure the UI tests are started with a release build
- [ ] Document which tests have been ignored 
- [ ] For a release ensure that it's easy to point to the overview of all test runs in the test sheet (new row added to the test sheet)

**Comment by bgavrilMS** [comment]
I removed the unit tests and integration tests from the release build, because we already run them as part of CI build and they take a long time and are flaky. I've also noticed that sometimes we include some tests in CI build but forget to include them in the Release build (i.e. need to refactor the templates etc.), for example the cache compat tests never ran on release builds.

I'm ok with running tests on the Release build, but I argue this is not a P1. Today, a release build must be associated with a passing CI build.

**Comment by trwalke** [comment]
I know I have needed to run a quick release build in the past to create a preview package for a customer so it is nice to have the build be quick. I think the best of both worlds is to have the release build trigger a set of test runs from our CI and UI Auto pipelines.

**Comment by henrik-me** [comment]
It's was not easy to validate that all tests had run. These tests needs to run as part of the release build. Happy to get more details on what is flaky. Moving back to P1. It took me almost 2 hours to get the information I needed before being able to give sign-off and still I wasn't sure everything had run on the actual bits we shipped.

**Comment by jmprieur** [comment]
We could also have an environment variable (settable in the build properties) to skip the test in case you want to have  a quick build?, but the tests would run by default?

**Comment by bgavrilMS** [comment]
A setting (not necessarily env variable) would be my preference as well. We also to reorganize the existing templates a bit to ensure all tests run on both builds with minimal yaml duplication.

**Comment by pmaytak** [comment]
This is included in [MSAL 4.25.0 release](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.25.0).
