### ISSUE TITLE
Login page unresponsive after cancelling iOS sign in

### ISSUE THREAD

**Issue by c-mckeown** [AzureAD/microsoft-authentication-library-for-dotnet#2296]
Hello,
I have found an issue where the buttons on our B2C login page can become unresponsive. Using the following steps:
-	Open login page 
-	Tap on sign in with Apple (using iOS device with iOS > 13
-	Cancel the login
-	App returns to login screen, but all other buttons are not clickable now
-	Only option for the user is to cancel at the top of the screen to go back to start page of app.
(Video displaying this - [RPReplay_Final1607677676.zip](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/files/5678265/RPReplay_Final1607677676.zip))
The in-app browser is using the embedded WebView.

**Which Version of MSAL are you using ?**
Microsoft.Identity.Client 4.23.0

**Platform**
Xamarin.Forms Xamarin.iOS 13.10.0.17

**What authentication flow has the issue?**
* Desktop / Mobile
    * [X] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)

**Is this a new or existing app?**
The app is in production, I haven't upgraded MSAL, but started seeing this issue

**Expected behavior**
-	Open login page 
-	Tap on sign in with Apple (using iOS device with iOS > 13
-	Cancel the login
-	App returns to login screen
-	User is able to interact with the login screen

**Actual behavior**
-	Open login page 
-	Tap on sign in with Apple (using iOS device with iOS > 13
-	Cancel the login
-	App returns to login screen, but all other buttons are not clickable now
-	Only option for the user is to cancel at the top of the screen to go back to start page of app.

**Comment by jennyf19** [comment]
@c-mckeown does this happen w/any other log in providers or just w/Apple?

**Comment by neha-bhargava** [comment]
@c-mckeown are you using system browser or embedded webview? Can you please share how are you creating your app?

**Comment by WilliamWatterson86** [comment]
@jennyf19 @neha-bhargava @c-mckeown 
This only seems to happen with Apple provider - other login providers launch their own web page, can cancelling the webpage seems to be ok..  It only happens when the apple login popup is cancelled on iOS - if we are using a version of iOS < 13 then the apple webpage comes up, and cancelling that is ok.  

It happens in system and embedded webview.  

@jennyf19 I have your email from the last time I had issues with iOS login.  I will send a sample app showing the issue.  @neha-bhargava if you provide your email I can send you the sample too.  If you run the sample on an iOS device > 13, then tap on the login button our login page will appear.  Then you can tap on "Sign in with Apple".  This will show the Apple system popup for login.  When you press cancel on that one it will go back to the login page, but all buttons don't work after that.  

I seen someone posted this issue on stack overflow as well - but im not sure how I would go about setting the agent for the webview you are launching?  Maybe you can help here?
https://stackoverflow.com/questions/64194788/wkwebview-buttons-dont-work-after-apple-login-session


Apple have started rejecting our apps because of this issue - so really need a work around or solution for this one.

**Comment by jennyf19** [comment]
@WilliamWatterson86 what's the status on this, was it resolved w/B2C?

**Comment by WilliamWatterson86** [comment]
@jennyf19 the issue is still being worked on. The latest I have from Namrata is 

“We are actively working on fixing this issue. We will have an ETA for this fix by next week.”

**Comment by jennyf19** [comment]
ok...thanks for the update @WilliamWatterson86

**Comment by stevenxzhou** [comment]
This is Fixed in IEF policy will be available next week for Basic policies.

**Comment by WilliamWatterson86** [comment]
@stevenxzhou will this just be a matter or updating the version number in the custom policy for unified and selfasserted?

**Comment by stevenxzhou** [comment]
Yes. That is correct.

**Comment by WilliamWatterson86** [comment]
Great! Thanks for your help on this

**Comment by williamwatterson** [comment]
@jennyf19 @jmprieur - I can confirm the issue is fixed and updating the version of the template in my custom policy works well.

The only extra thing I needed to add was the highlighted line in the image attached.  Without this line when Apple login was cancelled the "create account" link threw an error.

![image](https://user-images.githubusercontent.com/22791828/109972167-ee7a8680-7cee-11eb-94fc-be38e43d7c26.png)

Happy enough to close this one if you are.

Thanks again for your help :)

**Comment by jmprieur** [comment]
Thanks for the update, @williamwatterson and for sharing the fix
Closing as you proposed
