### ISSUE TITLE
[Feature Request] Add token cache encryption mechanism

### ISSUE THREAD

**Issue by yohanb** [AzureAD/microsoft-authentication-library-for-dotnet#2364]
Since bearer tokens are usable by anyone who can get their hands on them, wouldn't it be a good idea to add an encryption mechanism to the token cache or at least provide some guidance?  I've seen some "built-in" ways to add security, such as Proof-of-Possession, but that doesn't seem like a mature feature yet.

What do you think?
Thanks.

**Comment by bgavrilMS** [comment]
Hi @yohanb - are you looking for a solution for Public Client scenarios or Confidential Client Scenarios? 
For Public Client, we have published a project that encrypts the token cache using DP-API on Windows, KeyChain on Mac and KeyRing on Linux. https://github.com/AzureAD/microsoft-authentication-extensions-for-dotnet

PoP tokens are being discussed, we currently support PoP tokens only on Confidential Client scenarios and you have to bring your own key (e.g. deploy a cert). We can only do Access Token PoP at the moment, the Refresh Token remains Bearer. Still, for confidential_client grant (i.e. app to app) this is ok (as there is not refresh token).

**Comment by yohanb** [comment]
@bgavrilMS for Confidential Client Scenarios, app tokens and user tokens.  I'm thinking a scenario where you have a multi-tenant app and need to keep tokens in a distributed token cache.

**Comment by bgavrilMS** [comment]
For user tokens, I'm afraid we don't yet have a solution because while the access token would be bound to a cert, the refresh token is not bound, i.e. it's a "bearer" refresh token. So it's pretty much pointless from a security perspective to bind just access tokens but not refresh tokens. 

For app 2 app flows, there is no refresh token involved, and MSAL.NET supports PoP today. See details here: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Proof-Of-Possession-(PoP)-tokens

Very interested in your feedback.

**Comment by yohanb** [comment]
interesting, thanks.  Do you have any guidance around security/encryption with user tokens for the time being?

**Comment by bgavrilMS** [comment]
Well, since these are confidential client scenarios, only the server side machines touch the tokens. If you serialize your token cache somewhere like Redis, then just make sure that instance of Redis is secure. If you use in-memory serialization, again, this is a back-end system so it should be fairly secure. By the way, for ASP.NET Core we have written a higher level API which comes with some serialization mechanisms https://github.com/AzureAD/microsoft-identity-web

But I agree that for the future, we should bind the access tokens and the refresh tokens to some key material. Today, we only support access token binding.
