### ISSUE TITLE
SSO state loss in iOS version

### ISSUE THREAD

**Issue by dear-abhi** [AzureAD/microsoft-authentication-library-for-dotnet#2424]
We have implemented the MSAL library in our Xamarin forms application. We are able to login successfully in android and iOS apps.
In iOS version of the application we are facing an issue while trying to edit the user profile.
We logged in to the application successfully, then trying to edit the profile. At that time we had to enter user name and password. Ideally it should not ask for user credentials as the user is already logged in. This issue is happening only in iOS version of application.
In iOS 13 we were able to edit the profile with out entering the user credentials again while using browser. If we are using webview we are getting this issue in iOS 13 and 14.
We are using,
1. Visual studio 2019
2. Xamarin forms version 4.8
3. Microsoft identity client 4.27

Any help is much appreciated.

**Comment by jmprieur** [comment]
@jennyf19 @trwalke : do you have any idea?

**Comment by XDarinor** [comment]
We have similar issue. If we login with the applicazione, we can use the JWT token to access the first scope requested. In we need another scope, the AcquireTokenSilent fails because GetAccountsAsync returns null, even if the MSAL library verbose log say it finds one account. This behaviour triggers the interactive login.

**Comment by bgavrilMS** [comment]
We need to investigate this, multiple hits.

**Comment by bgavrilMS** [comment]
We will not fix this in Xamarin as it is on its way out. Please move to Maui.
