### ISSUE TITLE
RemoveAsync not working after caching tokens from OBO flow [Bug] 

### ISSUE THREAD

**Issue by SirElTomato** [AzureAD/microsoft-authentication-library-for-dotnet#2447]
Logs and Network traces
Without logs or traces, it is unlikely that the team can investigate your issue. Capturing logs and network traces is described at https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging

Which Version of MSAL are you using ?
Microsoft.Identity.Client 4.25.0

Platform
.Net Framework 4.7.2

What authentication flow has the issue?

Desktop / Mobile
 Interactive
 Integrated Windows Auth
 Username Password
 Device code flow (browserless)
Web App
 Authorization code
 OBO
Daemon App
 Service to Service calls
Other? - please describe;

This is when adding msal to an existing app. Msal is not in production on the app currently.

**Repro**

```csharp
var your = (code) => here;
```

**Expected behavior**
When calling ConfidentialClientApplication.RemoveAsync, the tokens should be removed from the cache

**Actual behavior**
If I pass the IAccount as below I get the following error

```
var authResult = await AquireTokenOnBehalfOf(scopes, jwt);

await ConfidentialClientApplication.RemoveAsync(authResult.Account);
```

'Response status code does not indicate success: NotFound (404); Substatus: 0; ActivityId: 65f56124-de0e-47d8-8150-0a530559e161; Reason: ({ "Errors": [ "Resource Not Found. Learn more: https://aka.ms/cosmosdb-tsg-not-found" ] });'

**Possible Solution**

**Additional context/ Logs / Screenshots**
Using CosmosCache
More context from my previous issue [here](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2432)

**Comment by jmprieur** [comment]
@SirElTomato 
Why do you want to remove the account in a web API?
I understand in a web app (to sign-out), but in a web API ? what is the scenario?

**Comment by SirElTomato** [comment]
@jmprieur 
The user signs in from the mobile app and gives permission to read emails. 
From our webapi, we use OBO to cache the tokens so that we can perform a long running scan of the users inbox, and repeat these scans at any point the user wants. 
We want to give the user the option to remove the access they have given us at any point.

**Comment by jmprieur** [comment]
Thanks for the explanation, @SirElTomato 
So I understand that you'd want RemoveAccount to remove all the tokens related to the user, not the token issused from the token used to call your web API.

@henrik-me @jennyf19 @bgavrilMS interesting scenario which affects the partition algorithm used for the cache.

**Comment by jmprieur** [comment]
The constraints we have are:
- the CA policies related to devices/network should be respected (the web API with an incoming token from a device on corporate network should be able to call a downstream API, but a token from a device in a cafe shouldn't). This was the decision behind having the cache key for OBO being the hash of the token, as it summarizes all the aspects, including CA claims
- RemoveAccount should work in Web APIs (they do work well in web apps and public client applications)

The token cache serializers could, in the case of OBO, write another blob key-ed by "obo_tokens_{AccountId}", of the incoming token hashes (the suggested cache keys) associated with the AccountId. This way when removing the account ID, they would be able to get the OBO token cache keys, and iterate throught them to remove the corresponding token cache blobs.

this might also be an opportunity to add a new parameter to AcquireTokenOnBehalfOf which would be the expiry of the incoming token, and that would be passed-in to the Token cache serialization args, so that:
- the token cache sets the expiry of each blob when the cache implementation knows how to handle it
- this expiry is aval

**Comment by jennyf19** [comment]
@SirElTomato 

Please see this page on [handling distributed cache eviction](https://github.com/AzureAD/microsoft-identity-web/wiki/Handle-L2-cache-eviction). Until there is a better solution from MSAL.NET, we recommend setting the `DistributedCacheEntryOptions`, specifically `SlidingExpiration`. 

in your above example, once the user signs-out or removed their account, the user account is deleted from the cache, but, as you point out, the OBO tokens are still in the cache. If you set the `SlidingExpiration`, once those tokens are no longer used by the web API and reach the expiration time you've specified, they will be removed from the cache. It's the best "solution" we can offer at the moment until we have a way to surface the needed elements from MSAL.NET.

**Comment by bgavrilMS** [comment]
This is by design, it is suggested to add an eviction policy. I added a few more comments our wiki related to this: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/on-behalf-of#cache-eviction-for-long-running-obo-processes:

```
Cache eviction for long-running OBO processes
It is strongly recommended to use a distributed persisted cache in a web api scenario. Since these APIs store the refresh token, MSAL will not suggest an expiration, as they can be used over and over again.

It is recommended that you set L1 and L2 eviction policies manually, for example a max size for the L1 cache and a sliding expiration for the L2.

Removing accounts
MSAL cannot perform account removal for OBO when using L2 caches. It is recommended to use eviction policies. If immediate removal is needed, delete the L2 cache node associated with the sessionKey.
```

CC @jmprieur for a quick review.
