### ISSUE TITLE
[Documentation] Should we use single ConfidentialClientApplication instance to acquire token for multiple users in web api?

### ISSUE THREAD

**Issue by blackchoey** [AzureAD/microsoft-authentication-library-for-dotnet#2455]
### Documentation Related To Component:
MSAL SDK

### Please check those that apply

- [ ] typo
- [x] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

### Description Of The Issue
A web api will handle requests from multiple users. In this case, should we have one single `ConfidentialClientApplication` instance to acquire tokens for different users, or we should initialize a new `ConfidentialClientApplication` for each user? The functions provided by `ConfidentialClientApplication` can handle multiple users, but I would like to learn what's the best practice. Thank you!

**Comment by jmprieur** [comment]
@blackchoey we recommend that you use one ConfidentialClientApplication by request. This is what Microsoft.Identity.Web does. The guidance is to use one cache per user any way.

**Comment by blackchoey** [comment]
Thank you very much @jmprieur , the reason of "use one ConfidentialClientApplication by request" is satisfy the "one cache per user" guidance, am I understanding correctly? And can you explain a bit more or share some document about the definition of `one cache` in the "one cache per user" guidance? For example, it seems the SQL database distributed cache in Microsoft.Identity.Web will save all the data to same table, which I'm not sure how "one cache per user" works.

To provide some background: I'm trying to use the built-in in memory cache provided by MSAL, and wants to make sure the cache is still available when same user makes another request to the API (unless the server restarts). Unfortunately, I'm not able to use Microsoft.Identity.Web. Understanding the guidance will be very helpful to the implementation.

**Comment by jmprieur** [comment]
Hello @blackchoey

By default MSAL's cache has all the accounts with their tokens in memory. By using token cache serializers you partition the token caches depending on the cache key that is used because the cache is swapped between the storage (which can be memory) and MSAL memory each time it's needed, and this means MSAL.NET only has very small caches at once in its memory. This is safer (you can only access what you need to access), and more performant. Talking of partition, MSAL.NET now provides a good default for the SuggestedCacheKey (in TokenSerializationArgs)

![image](https://user-images.githubusercontent.com/13203188/110296678-e2ded680-7ff2-11eb-9712-103d6b5b4ddb.png)

You can definitively use Microsoft.Identity.Web as it's also available for non-web apps, non-web APIS. See:
- this sample (which is a console app): https://github.com/Azure-Samples/active-directory-dotnet-v1-to-v2/blob/master/ConfidentialClientTokenCache/Program.cs
- This doc: https://github.com/AzureAD/microsoft-identity-web/wiki/asp-net

**Comment by jmprieur** [comment]
@blackchoey : are you happy with closing this issue?

**Comment by blackchoey** [comment]
@jmprieur Thanks for the great explanations. Feel free to close this issue.

**Comment by dhmahidawork** [comment]
is there way to handle this without upgrading to .net core or .net 4.7.2 ?

**Comment by jmprieur** [comment]
@dhmahidawork : which version of .NET do yo need?
