### ISSUE TITLE
[Feature Request] Is it possible to get the assembly to no longer rely on WinRT in the .NET 5.0 WPF

### ISSUE THREAD

**Issue by SundayRX** [AzureAD/microsoft-authentication-library-for-dotnet#2488]
**Is your feature request related to a problem? Please describe.**
Prior to version 4.28, login authentication using an embedded browser on.NET 5.0 WPF relied on WinRT.
But the WinRT dynamic link library file is a little bit big. 
**Describe the solution you'd like**
Does this mean that the assembly can be changed to run away from WinRT？
**Describe alternatives you've considered**
I mentioned it before. You said that because the embedded browser has to implement some functions of WinRT, it cannot run without WinRT
In version 4.28 I noticed the use of WebView2 as the carrier for the embedded browser rendering.
**Additional context**
The use of WBEView2 is not user-friendly, especially for applications that do not require installation.
But I've also noticed that WebView2 is struggling to be integrated into applications.
I don't want the program to contain both the WinRT component library and the WBEView2 component library, so the program is really too big.

**Comment by bgavrilMS** [comment]
Thank you for your feedback @SundayRX , this is very useful. I agree that WebView2 is hard to use because of the installation experience. 

For the size of the runtime, I can offer an workaround where you target MSAL .net core 2.1 version instead on MSAL .net5-windows version. This should be possible if your app targets .net5 or .net5-windows instead of .net5-windows10.0.17763.0, or with some msbuild magic. You will not be able to use the Windows Broker or to use WebView2, but your runtime will be smaller. You'll have to explicitly set `.WithUseEmbeddedWebView(false)`

The WinRT component is indeed quite big, but I do not see a way around it. WAM (broker) auth is the preffered auth mechanism and will future proof your application. WebView2 ... we could probably put it in a separate package.

**Comment by SundayRX** [comment]
Thank you very much for your patience！！！ I will choose a more suitable solution by myself, and I am looking forward to having WBEView2 embedded in the application！
