### ISSUE TITLE
[Documentation] Clarification for "redirect URL is pre-proposed"  (transfer)

### ISSUE THREAD

**Issue by jsquire** [AzureAD/microsoft-authentication-library-for-dotnet#2553]
# Issue Transfer

### Please be aware that @sabuncu is the reporter of this issue and include them on any response.

---
Under the remarks section, it says:

The redirect URL is **pre-proposed** by the library. It does not need to be passed in the constructor

What's this mean?  Does it mean the redirect URL is set to a default value?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc4b80d8-15c7-2854-8123-5d0550989dd5
* Version Independent ID: 9eacf25f-2f23-268a-7a2a-b48ed5e9d498
* Content: [PublicClientApplication Class (Microsoft.Identity.Client) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identity.client.publicclientapplication?view=azure-dotnet)
* Content Source: [xml/Microsoft.Identity.Client/PublicClientApplication.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Identity.Client/PublicClientApplication.xml)
* Service: **active-directory**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

---
This issue was transferred form the Azure SDK for .NET repository _([#19882](https://github.com/Azure/azure-sdk-for-net/issues/19882))_.

**Comment by bgavrilMS** [comment]
Strangely I am not able to edit this doc, but just to answer you @jsquire -

The redirect URI is needed for interactive authentication, so that the browser (webview) can return control to the app, and also to pass the authentication code to the app. Each webview (embedded, system) and broker (e.g. Win10's Web Authentication Manager or Authenticator apps on mobile) use a different strategy for getting back from the browser to the app, and as such, there are many redirect URIs formats. MSAL samples for each app type will showcase the redirect URIs. Redirect URIs must always be configured in the AAD portal.

**Comment by jsquire** [comment]
Hi @bgavrilMS.   Thanks for your assistance, but please be aware that I'm just triaging the issue from the Azure SDK repository.   @sabuncu is the author of the original issue;  we'll want to be sure to include them in any activity.

**Comment by bgavrilMS** [comment]
Sounds good. @sabuncu please let me know if you have trouble configuring a redirect uri. The error message from AAD should be very clear if you don't get it right, but they will not give too many details (e.g. what the app redirect URI you used, why it didn't match etc.) for security reasons.

**Comment by sabuncu** [comment]
Thank you @bgavrilMS and @jsquire, much appreciated.

**Comment by bgavrilMS** [comment]
@localden - feel free to pick this one as well
