### ISSUE TITLE
[Bug] Authorization code is truncated causing error AADB2C90090: The provided JWE is not a valid 5 segment token.

### ISSUE THREAD

**Issue by NickVandewalle** [AzureAD/microsoft-authentication-library-for-dotnet#2607]
**Which Version of MSAL are you using ?**
4.30.1

**Platform**
.NET Framework 4.7.2

**What authentication flow has the issue?**
Desktop / Mobile
    Interactive

**Is this a new or existing app?**
An existing app with a new implementation of B2C.

**Repro**
* Create a custom B2C policy that enriches the JWT with application-specific claims.
* Acquire a token via AcquireTokenInteractive with the nativeclient redirect uri.
* The redirect uri + authorization code exceed 2084 characters.
* The code at [WindowsFormsWebAuthenticationDialogBase](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/36c1113dc4154a2a74d53ebb575d82da39630e6d/src/client/Microsoft.Identity.Client/Platforms/Features/WinFormsLegacyWebUi/WindowsFormsWebAuthenticationDialogBase.cs#L199) can only read the truncated code instead of the full authorization code.
* When exchanging the authorization code for a token the application throws the titular exception.

**Expected behavior**
A large set of claims should not cause an exception to occur.

**Actual behavior**
The authorization code gets truncated whenever the claims cause the authorization code to exceed a certain size.

**Additional context/ Logs / Screenshots**
[AAD90090_Logging.txt](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/files/6435155/AAD90090_Logging.txt)

This issue is very similar to #2515 so it could be that this is a duplicate.

**Comment by NickVandewalle** [comment]
@jmprieur Yes, Indeed.

**Comment by jennyf19** [comment]
@NickVandewalle do you have a repro you can share?

**Comment by jennyf19** [comment]
@NickVandewalle have opened an ICM on B2C, as per direction from their team.

**Comment by jennyf19** [comment]
thanks @NickVandewalle, i passed this info on to the B2C side.

**Comment by jennyf19** [comment]
@NickVandewalle B2C is having difficulties getting a repro on this...is it still an issue?

**Comment by NickVandewalle** [comment]
@jennyf19 Yes, still an issue.

I have just now successfully reproduced this via the attached repro case.
Is the B2C team not able to simulate the exception via the repro case? Or do they have issues getting the solution to run in general (Because I also had to restore the nugets manually and reopen visual studio for some reason)?

**Comment by jennyf19** [comment]
@NickVandewalle can you send me an email and I'll get you in touch w/the b2c side working on this. they need more specific info, if that's okay with you. jeferrie@microsoft.com

**Comment by pmaytak** [comment]
Hi @NickVandewalle 
Please see my investigation in https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2743#issuecomment-877583645
Could you try some of these workarounds?
- Use default system browser instead of the embedded ones [System browser wiki](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/System-Browser-on-.Net-Core#how-to-use-the-system-browser-ie-the-default-browser-of-the-os)
- Use WebView2 embedded browser [WebView2 wiki](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/WebView2#changes-to-call-pattern)
  - WebView2 works better on .NET Core, so it would be better if you can upgrade.
  - Otherwise, if you run into WebView2 related issue in Net Fx, there's a workaround in https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2482#issuecomment-878619630
