### ISSUE TITLE
documentation connecting ws2019 onprem adfs with msal

### ISSUE THREAD

**Issue by karezza** [AzureAD/microsoft-authentication-library-for-dotnet#2625]
**Is your feature request related to a problem? Please describe.**
Yes, there appears to be a total focus on working with azure rather than onprem adfs, which is ok and I understand that.

**Describe the solution you'd like**
A documentation page with onprem adfs & msal focus.  Lots of searching has revealed many pages which say 2016 is not supported with MSAL, upgrade to 2019 and msal will work, and that's about it.

**Describe alternatives you've considered**
I've tried to use the existing documentation, but it appears to be missing some key steps, or it may be a bug in msal, there is another ticket to investigate that.

**Additional context**
Notable issues to cover:
- With onprem ADFS it appears to be a requirement that the 'resource' parameter must be specified.  I learned this in the past and it may no longer be relevant; such a documentation page could answer this, by simply saying it is required or not mentioning it and then we know its no longer still a requirement.  ([this posting ](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1678) may be saying it is no longer a requirement?)
- Whether 'offline_access' scope needs to be added somehow, this was mentioned in other postings as something that MSAL requires yet it is not available in my Windows Server 2019 AD FS installation.  Do I need to add it for MSAL to work?
- Since my existing setup works via IdentityModel libraries via c#, powershell, and via an android mobile app, it would seem that it would work with MSAL, however, if there are additional requirement setup steps to perform state those.
- An example program.  I've found both documentation to adding application groups to adfs & sample msal code to work on an onprem environment.  This step may be as simple as linking to these other pages.  Having them linked though would help with troubleshooting to know the code is valid for an onprem adfs setup and not just for something using azure.
- Though I am currently happy with onprem adfs, perhaps such a documentation page could be a good starting point to tempt users on additional benefits they'd get by adding in azure adfs... such as, if you were to add azure adfs (link) you can additional get mfa (link), and such and such (link), and such and such (link) ....

Onprem ADFS is a perfectly functional product and very welcome solution which comes with the possibility of later easily allowing code to be moved to new environments with even more methods of providing authentication and authorization, using MSAL comes with this promise and a documentation page dedicated to connecting the two would be good to move users in the direction of MSAL which itself creates momentum towards azure.

**Comment by jmprieur** [comment]
@trwalke : can you please address these.
I suggest updarting https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/ADFS-support

**Comment by nick-work** [comment]
It would be great if the documentation could continue to support on-premises ADFS and some of the demo test projects using ADFS as the authority.

**Comment by WongResearch** [comment]
It would be great if the documentation could continue to support on-premises ADFS and extending to some of the demo test projects using ADFS as the authority.

**Comment by bgavrilMS** [comment]
To answer some of the questions here: 

1. MSAL's design is to fetch access tokens. It was not designed to fetch only id tokens. So, we recommend that you always specify a scope. If you do not need a scope, just register a dummy scope and use that one.

2. MSAL always adds `profile`, `openid` and `offline_access` to user token requests, because MSAL needs id tokens and refresh tokens for caching purposes.

3. You only need to point MSAL at the adfs authority - e.g. `https://fs.msidlab8.com/adfs`

4. You can move to use AAD, for example by establishing federation between your on-prem ADFS and AAD. This allows apps to call AAD, but you ADFS server is responsible for showing the authorization UX, user management etc. See https://learn.microsoft.com/en-us/azure/active-directory/hybrid/whatis-fed - this way existing apps don't need to be changed but new apps can target AAD. As far as I know, Microsoft's offerings in AAD are much more complex, for example you can set conditional access policies banning ppl from logging in from unsecure devices etc. I believe SSO - the ability for users to login without re-typing their credentials - is better with AAD as well, because AAD has extra protocols that enable SSO.
