### ISSUE TITLE
[Bug] Incorrect suggestedCache key for removeAsync(account) in confidential client apps

### ISSUE THREAD

**Issue by abhidnya13** [AzureAD/microsoft-authentication-library-for-dotnet#2643]
`RemoveAsync(account)` in confidential client apps returns an empty cache key.

The cache key, I think should be `home_accout_id`

Reference:
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/master/src/client/Microsoft.Identity.Client/Cache/SuggestedWebCacheKeyFactory.cs#L23-L26

**Comment by jennyf19** [comment]
closing as [duplicate](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2447)

**Comment by bgavrilMS** [comment]
Not sure if it is a duplicate. When a call to `RemoveAccount` is made, MSAL does not generate any `suggested_cacke_key` so we're unable to load the cache at all. So this affects Web app scenarios, not just web api calls downstream web api.

In any case, the fix is trivial, the key is account.HomeAccountId

**Comment by jennyf19** [comment]
@abhidnya13 and I synced off-line on this. It's not an exact duplicate but related.

**Comment by bgavrilMS** [comment]
Thx @jennyf19  - I'm a bit surprised that nobody using M.I.W. didn't complain about this, since `TokenAcquisition.RemoveAccountAsync` is broken. I guess ppl don't call this too often since it doesn't affect cookie state?

https://github.com/AzureAD/microsoft-identity-web/blob/b106d9a9250522d0bf9ed0e78e0e3dbd376d8170/src/Microsoft.Identity.Web/TokenAcquisition.cs#L514

**Comment by jennyf19** [comment]
@bgavrilMS It does work. We get the account info from the [httpContext](https://github.com/AzureAD/microsoft-identity-web/blob/b106d9a9250522d0bf9ed0e78e0e3dbd376d8170/src/Microsoft.Identity.Web/ClaimsPrincipalExtensions.cs#L19) for the currently signed-in user. @abhidnya13 and i were discussing the OBO use case, which doesn't remove an account because we don't have a cache key, but rather rely on eviction policies from the cache itself. 

How does oid_tid get into the httpContext? It's because we call the user info endpoint, which gives that info, which is needed for guest scenarios.
