### ISSUE TITLE
[Feature Request] Use response_mode=form_post for B2C requests

### ISSUE THREAD

**Issue by jennyf19** [AzureAD/microsoft-authentication-library-for-dotnet#2743]
Investigate if MSAL.NET can/should use a response mode of form_post with system browser for B2C when sending a request. This is so the auth code will not be part of the URL, causing limit exceeding. MSAL is doing response_mode=query.

Related issues:
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2607
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2515
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2749

**Comment by pmaytak** [comment]
Findings:
- I was able to repro this only on **embedded legacy** browser (not system browser). Since legacy browser is based on Internet Explorer, it also has a max URL length of 2083 characters. So longer URLs get cut off and result in parsing errors.
- Embedded WebView2 works because it's based on Microsoft Edge, which has a longer URL limit. 
- System MS Edge also works for the above reason.
- System Internet Explorer also works. Interestingly, in IE browser address bar, the URL is cut off at 2083 characters. But it works because, my guess, is in MSAL we use `HttpListener`, which intercepts the full correct URL.

Workaround:
- A possible workaround is to use embedded WebView2 or system browsers instead legacy embedded browser. However, there is an issue with embedded WebView2 browser not working properly on NET Fx sometimes.

Solution:
- Send `response_mode=form_post` query parameter.
- Issue: in the embedded legacy browser code, we deal with URLs; so far wasn't able to find a way to get the request body to get the auth code.

**Comment by bgavrilMS** [comment]
Is there a reason to do this only for B2C? We could do this for AAD and ADFS as well, to have simpler logic in the lib, unless you can think of any issues with using POST ...

**Comment by bgavrilMS** [comment]
@pmaytak - please ask the affected customers to see if they can move to .NET Core and to use WebView2 - I think it's stable there. 

You can have a look to see how the WebBrowser can be modified to parse a POST response, I think the relevant code is here: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/0d53f3e80e29f9c6d172e069c10e02d71e24f65e/src/client/Microsoft.Identity.Client/Platforms/Features/WinFormsLegacyWebUi/WindowsFormsWebAuthenticationDialogBase.cs#L191

**Comment by bgavrilMS** [comment]
Will will fix this in MSAL 4.35, please ignore the workaround.
