### ISSUE TITLE
[Documentation] How to acquire only an id token

### ISSUE THREAD

**Issue by chwarr** [AzureAD/microsoft-authentication-library-for-dotnet#2813]
**Documentation related to component**
"Acquiring Tokens"

**Please check those that apply**

- [ ] typo
- [x] documentation doesn't exist
- [x] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

**Description of the issue**

Sometimes, a public client app only needs an id token--and not an access token. (If you need even more details about this, please find me in the Microsoft directory and send me an email. I have a more detailed scenario that I can share internally.)

As far as I understand, there is no `AcquireIdToken` family of APIs. I _believe_ the way to get an id token from MSAL.NET is, essentially, to request a token for just the scope "openid". (Optionally, either or both of the "profile" and "email" scope can be requested to have the returned id token include [additional claims](https://docs.microsoft.com/en-us/azure/active-directory/develop/id-tokens)).

If this is the case, it would be nice to have this behavior documented somewhere. If this is not the right way to acquire only an id token, please document how one would do that.

If this behavior is not part of MSAL.NET's contract and is incidental behavior, let me know, and I'll turn this into a feature request instead.

**Comment by rayluo** [comment]
> As far as I understand, there is no `AcquireIdToken` family of APIs. I _believe_ the way to get an id token from MSAL.NET is, essentially, to request a token for just the scope "openid". (Optionally, either or both of the "profile" and "email" scope can be requested to have the returned id token include [additional claims](https://docs.microsoft.com/en-us/azure/active-directory/develop/id-tokens)).
> 
> If this is the case, it would be nice to have this behavior documented somewhere. If this is not the right way to acquire only an id token, please document how one would do that.
> 
> If this behavior is not part of MSAL.NET's contract and is incidental behavior, let me know, and I'll turn this into a feature request instead.

It is unlikely that any MSAL would introduce a (family of!) `AcquireIdToken` APIs, because that would be confusing for 2 reasons:

1. Semantically, all MSAL's `AcquireTokenByXyz(..., scopes, ...)` APIs mean to acquire access token;
2. And most `AcquireTokenByXyz(...)` APIs would already acquire ID token during the access token acquisition, for free.

What you want is the sign-in only behavior. With the current MSAL's API surface, it *could* be solved by either existing APIs accept an empty scopes parameter (some MSAL may support that), or, there is nothing prevent you from using scope like "email" to mimic the Sign-In only behavior because it is a standard behavior.

Lastly, even when (an MSAL allows you to) send out an "openid"-only request, the response would counter-intuitively still contain an access token, which can be used to access the user_info endpoint, and sometimes more.

```json
DEBUG:msal.token_cache:event={
    "client_id": "289a413d-284b-****",
    "data": {
        "claims": null,
        "client_id": "289a413d-284b-****",
        "code": "0.AgAAkq1F****",
        "code_verifier": "VpkezBM*******",
        "redirect_uri": "http://localhost:46179",
        "scope": [
            "openid"
        ]
    },
    "environment": "login.microsoftonline.com",
    "grant_type": "authorization_code",
    "params": null,
    "response": {
        "access_token": "********",
        "expires_in": 3599,
        "ext_expires_in": 3599,
        "id_token": "********",
        "scope": "email openid profile Calendars.Read User.Read User.ReadBasic.All",
        "token_type": "Bearer"
    },
    "scope": [
        "email",
        "openid",
        "profile",
        "Calendars.Read",
        "User.Read",
        "User.ReadBasic.All"
    ],
    "token_endpoint": "https://login.microsoftonline.com/common/oauth2/v2.0/token"
}
```

**Comment by bgavrilMS** [comment]
As Ray mentioned, you should be able to do `AcquireToken***(null)` - i.e. request no scopes. In this case, MSAL will make a request for `openid`, `profile` and `offline_access`.  The 3 scopes are required for MSAL's internal use, so we can't skip them otherwise there's no token caching. 

AAD optimizes the response and may choose to send your app an access token containing scopes for which the user has already consented. The hope is that this will avoid you from having to re-request a token.

**Comment by chwarr** [comment]
Thanks for confirming!

After re-reading the [Microsoft identity platform ID tokens](https://docs.microsoft.com/en-us/azure/active-directory/develop/id-tokens) documentation and the [Microsoft Graph permissions reference](https://docs.microsoft.com/en-us/graph/permissions-reference#openid-permissions), I see now that requesting an access token for the OpenID Connect scopes from the v2 endpoint is a documented way to get the Microsoft Identity Platform to return an id token. That I also happen to get back an access token for the Microsoft Graph is something I can ignore.

For MSAL.NET 4.35.1, all of the following `IEnumerable<string>?` values for the `scope` parameter of `AcquireTokenInteractive` parameter allow me to get an id token, as you mentioned:

* `null`
* empty `string[]`
* `new[] { "openid" }`
* `new[] { "openid", "email" }`
* `new[] { "openid", "profile" }`
* `new[] { "openid", "email", "profile" }`
