### ISSUE TITLE
[Feature Request] Better default HTTPClient on .NET Core

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#2867]
MSAL's default HttpClient does not handle DNS changes. 

**Proposal**: use `System.Net.Http.SocketsHttpHandler` on confidential client flows

The configuration should be similar to
```csharp
#if NETCOREAPP2_1_OR_GREATER
            // Starting with netcore2.1 and .NET5+, HttpClient maintains long lived socket connections and as a result does
            // not respect DNS.  This enforces a reconnect and as a result a DNS update.
            var handler = new SocketsHttpHandler { PooledConnectionLifetime = TimeSpan.FromMinutes(15) };
            HttpClient = new HttpClient(handler) { Timeout = timeout, MaxResponseContentBufferSize = maxResponseDataSize };
#else
            HttpClient = new HttpClient() { Timeout = timeout, MaxResponseContentBufferSize = maxResponseDataSize };
#endif
```

**Comment by bgavrilMS** [comment]
@pmaytak - based on error telemetry, is this worth doing?

**Comment by pmaytak** [comment]
Based on the error telemetry - no, low ROI because errors are only a tiny amount of total requests. They do say there's [perf improvement](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.socketshttphandler?view=net-5.0#remarks), so I would do it for general perf improvements. Maybe a P3?

**Comment by bgavrilMS** [comment]
HttpClientHandler uses SocketClientHandler, so it's all good.
