### ISSUE TITLE
[Bug] using app Id URI instead of client_id in web API, results in bad token for OBO RT redemption.

### ISSUE THREAD

**Issue by jennyf19** [AzureAD/microsoft-authentication-library-for-dotnet#2880]
1.16.1

ResponseBody: {"error":"invalid_grant","error_description":"AADSTS70000: Provided grant is invalid or malformed.\r\nTrace ID: 7c2d5c69-da2d-4b9a-969b-3770520f0d01\r\nCorrelation ID: eb26b440-88f2-405f-be22-4d389627372b\r\nTimestamp: 2021-09-08 14:51:19Z","error_codes":[70000],"timestamp":"2021-09-08 14:51:19Z","trace_id":"7c2d5c69-da2d-4b9a-969b-3770520f0d01","correlation_id":"eb26b440-88f2-405f-be22-4d389627372b","error_uri":"https://login.microsoftonline.com/error?code=70000","suberror":"bad_token"}

I added this in the appSettings.json in the web API:

"ClientId": "api://a4c2469b-cf84-4145-8f5f-cb7bacf814bc",
"Audience": "api://a4c2469b-cf84-4145-8f5f-cb7bacf814bc",

This apparently did not work for v1 either.

Repro:
1. Perform AcquireTokenOnBehalfOf for a user with confidential client app.
2. Perform AcquireTokenOnBehalfOf again but this time with WithForceRefresh() enabled
3. The token endpoint will return error "AADSTS70000: Provided grant is invalid or malformed"

Possible fix:
- Only acquire an OBO RT when initiating a long running process

**Comment by jmprieur** [comment]
I agree with @jennyf19's proposal:
- `AcquireTokenOnBehalfOf`: no longer acquires the OBO RT. This will have the advantage that, for customers who don't want long running processes, the cache will expire (the SuggestedExpiry property of the TokenAcquisitionArgs will have a value). Then if the developer tries to call `AcquireTokenOnBehalfOf` with an expired user assertion, MSAL.NET would throw with a meaningful message with aka.ms, telling them, that, if they want to have long running process, they need to call `InitiateLongRunningProcessInWebApi` instead of `AcquireTokenOnBehalfOf` (when https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/2820/files is merged)
- InitiateLongRunningProcessInWebApi` would get the OBO refresh token.

**Comment by jmprieur** [comment]
See also https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/2820

**Comment by pmaytak** [comment]
@trwalke @jmprieur Was this ever fixed? I faintly remember we added some sort of check if client ID is URI?

**Comment by bgavrilMS** [comment]
@jennyf19 @jmprieur - is this still a problem? We've split OBO into 2 parts. Closing for now, please feel free to re-open with more details if needed.
