### ISSUE TITLE
[Feature Request] Edge System browser support for Linux Broker

### ISSUE THREAD

**Issue by maliksahil** [AzureAD/microsoft-authentication-library-for-dotnet#3051]
**Is your feature request related to a problem? Please describe.**
Customers wish to integrate with Linux Broker. A short term win may be to use system browser to offer integration with linux broker.

**Describe the solution you'd like**
Allow the developer to specify a specific browser (edge) when operating on Linux. The .WithBroker() call could then use edge to integrate with linux broker.

**Describe alternatives you've considered**
Wrapping OneAuthMSAL would be a great alternative, but is probably higher effort/down the road.

**Additional context**

- [ ] Figure out if we can detect if Edge is installed (see Ray's comments below)
- [ ] Figure out if there is way to start Edge on Linux instead of the regular "xdg-open"
- [ ] If all of this is possible, start Edge if it is installed and WithBroker is set to true
- [ ] If not possible, contact Edge team and ask for guidance

**Comment by bgavrilMS** [comment]
@rayluo - did you say you were working on this for msal.py? Is there a way to start edge on Linux and to check that is successful?

**Comment by rayluo** [comment]
> @rayluo - did you say you were working on this for msal.py?

Regarding launching a *standard Edge*, that part has already been finished, tested, and shipped in msal python. We are just recently discussing about the end-to-end test since the *broker-enabled Edge-dev* becomes available.

> Is there a way to start edge on Linux and to check that Edge exists?

MSAL Python detects Edge's existence by using its default installation path that we observed: `/usr/bin/microsoft-edge`. Python language happens to provide a built-in module to launch a specific browser, I believe it is essentially spawning a process to run the browser executable file with a given url.

**Comment by neha-bhargava** [comment]
@bgavrilMS @maliksahil In case edge is unavailable do we throw an exception or just open the browser using xdg-open?

**Comment by bgavrilMS** [comment]
Yes, the logic should be: 

- if the broker is enabled then try to use Edge, but if not found, use any browser (xdg-open)

**Comment by gladjohn** [comment]
This has been fixed in [MSAL 4.41.0](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.41.0)
