### ISSUE TITLE
[Bug] Is it normal that a B2C AD with one user takes 6 seconds to login on Android?

### ISSUE THREAD

**Issue by MhAllan** [AzureAD/microsoft-authentication-library-for-dotnet#3080]
Msal is too slow on Android!

I am using login by username and password, so no UI involved, and returning like 4 properties out of 10 in the token. yet that login takes 6-10 seconds!!

**Comment by bgavrilMS** [comment]
AcquireTokenByUsernamePassword is not recommended. We only keep it around so that folks can write integration tests. The correct mechanism is to display UI `AcquireTokenInteractive` and display a browser ONCE. Then `AcquireTokenSilent` will manage the token refresh silently. Our samples showcase this.

`AcquireTokenByUsernamePassword` can take a long time if the Identity Provider is not AAD but you are using some kind of federation (ADFS, Ping federate etc.).

**Comment by MhAllan** [comment]
@bgavrilMS Thanks for your quick reply, I know it is not recommended, but there is no docs say it is for testing and going to be slow. my app users won't sign in with external providers and I don't want to customize html page for my native app so I want to sign in by username and password. no solution except the UI?

**Comment by bgavrilMS** [comment]
Even if you use AcquireTokenByUsernamePassword and it takes a long time due to HTTP, I expect that the other calls are fast. Do you use the pattern

```
try 
  var account = await app.GetAccountsAsync(policy);
  result = await app.AcquireTokenSilent(acc, scopes).ExecuteAsync();
catch MsalUiRequiredException
  result = await app.AcquireTokenByUsernamePassword
```

This ensures for a given user, you'll only call `AcquireTokenByUsernamePassword` once.

**Comment by MhAllan** [comment]
Thanks a lot @bgavrilMS I will do that.
