### ISSUE TITLE
[Bug] long SystemWebViewOptions HtmlMessageSuccess sometimes fail with ERR_CONNECTION_RESET

### ISSUE THREAD

**Issue by jayars** [AzureAD/microsoft-authentication-library-for-dotnet#3146]
**Logs and network traces**

[success-page-not-shown.log](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/files/8020968/success-page-not-shown.log)

**Which version of MSAL.NET are you using?**

4.40.0

**Platform**

NET 4.8

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Interactive
    * [ ] Integrated Windows Authentication
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web app 
    * [ ] Authorization code
    * [ ] On-Behalf-Of
* Daemon app 
    * [ ] Service to Service calls

Other?

When the `SystemWebViewOptions.HtmlMessageSuccess` is long (~4000 chars), the page sometime fails to load, with the error `ERR_CONNECTION_RESET`

**Is this a new or existing app?**

This is a new app

**Repro**

```csharp
var client = PublicClientApplicationBuilder.Create(clientId)
    .WithRedirectUri("http://localhost")
    .WithLogging((level, message, _) =>
    {
        messages.Add(message);

        // When uncommented, it seems to work
        // File.AppendAllText("logs.log", message+"\n");

        // Alternatively, if I use Thread.Sleep it seems to work too
        // Thread.Sleep(1);
    }, LogLevel.Verbose)
    .WithB2CAuthority(authority)
    .Build();

// If the html is long (~4000 characters), then the problem starts to appear 
var html = "<!DOCTYPE html> <html> <head>   <meta charset=\"utf-8\">   <meta name=\"viewport\" content=\"width=device-width\">   <title>Sign in success</title>   <style>     html {       font-family: 'Segoe UI', 'Roboto', verdana, arial, sans-serif;     html, body {       margin: 0;       padding: 0.5rem;       background-color: #ffffff;     h2, p {       font-weight: normal;       text-align: center;     h2 {       color: #08911f;     p {       margin-top: 1rem;       color: #243342;     svg {       height: 30px;       display: block;       margin: 1rem auto;   </style> </head> <body>     <h2>Sign in success!</h2>     <p>You can close this browser tab now and return to the application.</p>     <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tenetur, nemo. Architecto, quia voluptates labore unde doloribus velit doloremque excepturi vero inventore impedit totam maiores reiciendis, suscipit animi tempore explicabo fugiat facilis nam nihil quibusdam. Iure sapiente odio, ea nostrum perspiciatis, nesciunt voluptas, labore quibusdam doloremque temporibus suscipit tempore. Inventore in et officiis eos cumque tenetur dignissimos atque. Molestias illum vero provident maiores, dolorum atque nostrum. Eveniet dolores iusto omnis blanditiis quasi fuga odit culpa veritatis, deleniti officia magni. Vero et, quidem accusamus sint, totam neque, recusandae ducimus quia impedit iste veritatis! Aliquid delectus nihil incidunt soluta, recusandae ullam commodi voluptates.</p>     <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tenetur, nemo. Architecto, quia voluptates labore unde doloribus velit doloremque excepturi vero inventore impedit totam maiores reiciendis, suscipit animi tempore explicabo fugiat facilis nam nihil quibusdam. Iure sapiente odio, ea nostrum perspiciatis, nesciunt voluptas, labore quibusdam doloremque temporibus suscipit tempore. Inventore in et officiis eos cumque tenetur dignissimos atque. Molestias illum vero provident maiores, dolorum atque nostrum. Eveniet dolores iusto omnis blanditiis quasi fuga odit culpa veritatis, deleniti officia magni. Vero et, quidem accusamus sint, totam neque, recusandae ducimus quia impedit iste veritatis! Aliquid delectus nihil incidunt soluta, recusandae ullam commodi voluptates.</p>     <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tenetur, nemo. Architecto, quia voluptates labore unde doloribus velit doloremque excepturi vero inventore impedit totam maiores reiciendis, suscipit animi tempore explicabo fugiat facilis nam nihil quibusdam. Iure sapiente odio, ea nostrum perspiciatis, nesciunt voluptas, labore quibusdam doloremque temporibus suscipit tempore. Inventore in et officiis eos cumque tenetur dignissimos atque. Molestias illum vero provident maiores, dolorum atque nostrum. Eveniet dolores iusto omnis blanditiis quasi fuga odit culpa veritatis, deleniti officia magni. Vero et, quidem accusamus sint, totam neque, recusandae ducimus quia impedit iste veritatis! Aliquid delectus nihil incidunt soluta, recusandae ullam commodi voluptates.</p>     <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tenetur, nemo. Architecto, quia voluptates labore unde doloribus velit doloremque excepturi vero inventore impedit totam maiores reiciendis, suscipit animi tempore explicabo fugiat facilis nam nihil quibusdam. Iure sapiente odio, ea nostrum perspiciatis, nesciunt voluptas, labore quibusdam doloremque temporibus suscipit tempore. Inventore in et officiis eos cumque tenetur dignissimos atque. Molestias illum vero provident maiores, dolorum atque nostrum. Eveniet dolores iusto omnis blanditiis quasi fuga odit culpa veritatis, deleniti officia magni. Vero et, quidem accusamus sint, totam neque, recusandae ducimus quia impedit iste veritatis! Aliquid delectus nihil incidunt soluta, recusandae ullam commodi voluptates.</p>     <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tenetur, nemo. Architecto, quia voluptates labore unde doloribus velit doloremque excepturi vero inventore impedit totam maiores reiciendis, suscipit animi tempore explicabo fugiat facilis nam nihil quibusdam. Iure sapiente odio, ea nostrum perspiciatis, nesciunt voluptas, labore quibusdam doloremque temporibus suscipit tempore. Inventore in et officiis eos cumque tenetur dignissimos atque. Molestias illum vero provident maiores, dolorum atque nostrum. Eveniet dolores iusto omnis blanditiis quasi fuga odit culpa veritatis, deleniti officia magni. Vero et, quidem accusamus sint, totam neque, recusandae ducimus quia impedit iste veritatis! Aliquid delectus nihil incidunt soluta, recusandae ullam commodi voluptates.</p> </body> </html>";
var result = await client.AcquireTokenInteractive(scopes)
    .WithPrompt(Prompt.NoPrompt)
    .WithUseEmbeddedWebView(false)
    .WithSystemWebViewOptions(new SystemWebViewOptions
    {
        HtmlMessageSuccess = html,
        HtmlMessageError = "<h1>Error!</h1><p>{0}<p><p>More details: {1}</p>"
    })
    .ExecuteAsync();
File.WriteAllLines("logs.log", messages);
```

**Expected behavior**
After the sign in is successful, the user should be shown the success page (`HtmlMessageSuccess`)

**Actual behavior**
After the sign in is successful, the browser sometimes fail to show the success page.

Instead, we get `ERR_CONNECTION_RESET` (see screenshots below)

**Additional notes**

When running on systems with antiviruses, this problem occurs more frequently with shorter html content.

Experienced this with **Avast** and **ESET**

**Possible solution**

Not a suggestion, but a workaround.

If I enable logging, and perform something that takes time (ie, IO, or a simple `Thread.Sleep(1)`), then the success page appears to be displayed as expected

**Additional context / logs / screenshots / links to code**

<img width="1003" alt="image" src="https://user-images.githubusercontent.com/28939507/152921009-036e357c-5391-46b1-addd-f0709765bea8.png">

![image](https://user-images.githubusercontent.com/28939507/152921045-6f2bdd9d-bc9c-4891-b031-482946d3ec14.png)

**Comment by bgavrilMS** [comment]
Hmm, it's probably a timing issue with the socket server. Can you use the redirect system webview option instead?

**Comment by jayars** [comment]
Did you mean [BrowserRedirectSuccess](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identity.client.systemwebviewoptions.browserredirectsuccess?view=azure-dotnet) and [BrowserRedirectError](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identity.client.systemwebviewoptions.browserredirecterror?view=azure-dotnet)?

These are working for me. And from what I remember, these always work.

I would use redirects, but `BrowserRedirectError` is just a simple redirect
And I lose the `{0}` and `{1}` placeholders.

So for our current development, we have opted to use `HtmlMessageSuccess` and `HtmlMessageError`

**Comment by bgavrilMS** [comment]
Looks like a limitation of system browser + antivirus. On Windows, please use WAM instead - https://aka.ms/msal-net-wam 
For Mac and Linux, we are working on bringing broker support and embedded browswer support, but I do not have an ETA for this.

**Comment by jeneum** [comment]
Could this issue be reconsidered/reopened? We reproduced the same symptom with **Microsoft.Identity.Client 4.88.0**, **.NET Framework 4.8**, Windows build **26200**, and Microsoft Edge **153.0.4234.48**.

Interactive system-browser authentication succeeds, but the final `http://localhost:<ephemeral-port>/` page intermittently remains blank. This occurred both at initial application launch and after logout/login.

### Isolated evidence

A diagnostic harness invoked the actual 4.88.0 loopback listener and response producer with a synthetic form POST containing dummy code/state values. It made no authorization-server or token requests. With a 35,827-byte response made entirely of generated placeholder HTML, the callback completed successfully in **2/2 runs**, but Edge rendered the completion page in **0/2 runs**. The browser used isolated profiles in headless mode. These tests reproduce the transport failure; they are not real authentication tests.

Both generated-dummy-HTML traces showed HTTP 200 with `Content-Length: 35827`, only **3,986 response-body bytes received**, then `net::ERR_CONNECTION_RESET` (-101). 3,986 is an observed partial-read size, **not a demonstrated safe limit**. No raw logs or application content are attached.

In an equivalent one-request .NET Framework `HttpListener` harness, retaining the write/close/abort sequence but setting **`response.KeepAlive = false`** delivered and rendered the generated 35,827-byte page in **3/3 runs**. Prior controlled runs with a different HTML payload also favored this change (11/11 rendered versus 0/2 for the baseline). These are small, single-machine samples, not proof of a universal fix. Replacing listener Abort with Close alone did not solve the earlier tests.

### Dummy HTML for reproduction

This is newly written generic example code, not application source. Configure an ordinary public-client system-browser interactive request with this `HtmlMessageSuccess` and your own test registration/scopes:

```csharp
string prefix = "<!doctype html><html><head><title>Loopback test</title></head><body><!--";
string suffix = "--><h1 id='completion-heading'>Sign-in complete</h1><p>You can close this browser window.</p></body></html>";
string html = prefix + new string('x', 35827 - prefix.Length - suffix.Length) + suffix;

var result = await publicClient.AcquireTokenInteractive(testScopes)
    .WithUseEmbeddedWebView(false)
    .WithSystemWebViewOptions(new SystemWebViewOptions { HtmlMessageSuccess = html })
    .ExecuteAsync();
```

The public-client registration must permit a localhost redirect; use `WithRedirectUri("http://localhost")` when building it. Repeat sign-ins and compare successful authentication with whether the browser receives/renders the whole response. The exact dummy HTML above was tested in the isolated callback harness; this public-API example is provided as a normal sign-in setup rather than a claim that it reproduces on every machine.

### Possible transport issue to investigate

In the [4.88.0 HttpListenerInterceptor source](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/4.88.0/src/client/Microsoft.Identity.Client/Platforms/Features/DefaultOSBrowser/HttpListenerInterceptor.cs), the response body is written, the response is closed, and the listener is aborted in cleanup. The response retains the default persistent-connection behavior. Our evidence is consistent with a response-delivery/connection-teardown race, but does not establish the complete root cause or rule out environmental factors.

Please consider testing an explicit `context.Response.KeepAlive = false` before sending this one-shot response. Setting `ContentType = "text/html; charset=utf-8"` for HTML responses may also be appropriate; that property alone helped in two earlier trials, so MIME sniffing/timing deserves investigation too. No modified MSAL binary was deployed.

Our temporary mitigation is a completion response below 500 UTF-8 bytes plus returning focus to the desktop application after interactive authentication completes. That rendered in 10/10 local callback tests, but is a mitigation rather than a guaranteed size-based fix. A library-level regression test for complete delivery of a larger HTML response before listener teardown would be valuable.
