### ISSUE TITLE
[Bug] AcquireTokenSilent(scopes, login_hint) is not valid on CCA

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#3403]
msal 4.45, web site scenario

`AcquireTokenSilent(scopes, login_hint)` is a convenience API on PCA only. Internally it does a "GetAccounts" operation, which is banned on CCA, because it does not enforce caching. 

Solution: 

- hard deprecate this method on CCA
- deprecation message should ask customers to use `AcquireTokenSilent(scopes, account)`

**Comment by pmaytak** [comment]
@bgavrilMS For [GetAccountsAsync in CCA](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/7fff414e166d6e10eb68b44802830749a91841fb/src/client/Microsoft.Identity.Client/IConfidentialClientApplication.cs#L95-L97) we obsoleted with warning and hid from editor because back then we had the same discussion and decided that obsoleting with error is breaking change. In this case this ATS could technically work in a singleton app (although highly not recommended). I'm just thinking of DevEx, if we hard deprecate, how easy it would be for users to switch to use the other ATS overload.
Just thoughts.

**Comment by bgavrilMS** [comment]
You are right @pmaytak, let's use the same trick as for `GetAccountsAsync`

**Comment by pmaytak** [comment]
[Released in 4.46.0](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.46.0)
