### ISSUE TITLE
[Bug] Can't build in .NET6.0 WPF

### ISSUE THREAD

**Issue by 1357310795** [AzureAD/microsoft-authentication-library-for-dotnet#3476]
**Build Error**
Error	NETSDK1149	Microsoft.Identity.Client.Desktop.dll cannot be referenced because it uses built-in support for WinRT, which is no longer supported in .NET 5 and higher.  An updated version of the component supporting .NET 5 is needed. For more information, see https://aka.ms/netsdk1149	TodoSynchronizer	C:\Program Files\dotnet\sdk\6.0.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets	1007	

**Which version of MSAL.NET are you using?**
![image](https://user-images.githubusercontent.com/35869804/178950742-83bc0be5-288d-4bc3-abb6-a95ed5fd8f51.png)

**Platform**
.NET 6.0 WPF

I'm not so familiar with MSAL.NET, is it because MSAL.NET doesn't support .NET 6.0?

**Comment by 1357310795** [comment]
Thanks! Options one works for me.☺

**Comment by ward-horsfall** [comment]
Hi bgavrilMS,

Thanks for your comment. Just to elaborate on what you said.

1. To use new implementation I assume to do the following to install:
Install-Package Microsoft.Identity.Client -Version 4.46.0-preview2 

So it is fixed in 4.46?

2. Can you clarify exactly where to make the change when you say:

you need to target net6.0-windows10.0.19041.0

Thanks,

Ward
