### ISSUE TITLE
[Bug] Refresh Token not being stored in Token Cache

### ISSUE THREAD

**Issue by luismanez** [AzureAD/microsoft-authentication-library-for-dotnet#3616]
**Which version of MSAL.NET are you using?**
4.42.0

**Platform**
.NET 6 (Net Core 6)

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [ ] Integrated Windows Authentication
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web app 
    * [ ] Authorization code
    * [X ] On-Behalf-Of
* Daemon app 
    * [ ] Service to Service calls

**Repro**

Please, see this issue opened in Microsoft Identity Web repository: https://github.com/AzureAD/microsoft-identity-web/issues/1846

**Expected behavior**
The refresh token is also stored in the TokenCache, as the access token is.

**Actual behavior**
Refresh token appears empty

**Possible solution**
Downgrade to MS identity web 1.20.0 (which also downgrades MS Identity Client)

**Comment by jennyf19** [comment]
@luismanez If you need the RT in the OBO scenario, then you would fall into the long running process category, which is [described here](https://github.com/AzureAD/microsoft-identity-web/wiki/get-token-in-event-handler#how-to-get-an-obo-token-in-an-event-handler-or-a-long-running-process). This is by design and the change was intended (security).
