### ISSUE TITLE
[Feature Request] [Question] Doc with recommended approach for OBO L2 Cache eviction

### ISSUE THREAD

**Issue by luismanez** [AzureAD/microsoft-authentication-library-for-dotnet#3631]
I´d like to have a document from MSAL, explaining the recommended approach to deal with L2 Cache eviction, for OBO flow. I´ve been reading some issues/spikes where @bgavrilMS gives some clues, but is not clear enough to me.

These are my questions:

- My scenario is a Web API in the middle, that calls Graph API (it´s consumed by a SharePoint SPFx webpart, but can be whatever, i.e: I use Postman when developing). Just meaning I´m using OBO flow with a L2 distributed cache using Azure Redis Cache
- First, why is a problem to store the refresh token in cache? (I know we still have the long running process approach, but I´d like to understand what´s the problem). With no RefreshToken, the cache entry is only valid for 1 hour (access token lifetime).
- Why the Cache Key is "_the hash of the original token for AcquireTokenOnBehalfOf_"? Why not something like: ```hash(tenantId_userId_audience_requestedScopes)```? I´m asking cos I don´t know how to clean expired cache entries. This is what I´m seeing: My SPFx webpart calls my API, so an entry is cached hashing the token from SPFx. 2 hours later, SPFx webpart calls my API again, the previous access token sent from SPFx, is not valid anymore, and my API is called with a new AccessToken, meaning a new entry is added to the Cache. I don´t know how to remove the previous entry, so my Redis is growing and growing. The only option I see is having some background process that either clean all MSAL cache entries, or loop all the entries, get the value, and check if the __AccessToken.expires_on__ value is expired. If the cache key is built like ```hash(tenantId_userId_audience_requestedScopes)``` when SPFx calls my API with a different AccessToken, when my API is about to call Graph with the same scopes, MSAL would be able to find an entry in token cache, and use that access token, or get a new one from refresh token (or even remove the entry if the refresh token is expired or not valid anymore)

Many thanks for your help.

**Comment by luismanez** [comment]
sorry. I´ve found this: https://github.com/AzureAD/microsoft-identity-web/wiki/Handle-L2-cache-eviction so my point about the cache growing and growing is not true. This is only true for Long running process scenarios, and there, I understand I´m responsible for removing the Cache item once the long running process is done. I´m leaving the issue open for a ocuple of days, in case someone want to add something (specially about why not using a different Key and why the refresh token is not stored in OBO by dessign)

**Comment by bgavrilMS** [comment]
To answer some of your questions. 

1. Why the Cache Key is "the hash of the original token for AcquireTokenOnBehalfOf"? 

The reason why caching OBO tokens is so complicated is to try to eliminate a security flaw in the system. Assume the following setup: 

`[Client] -> [Web API] -> [Graph]`

So, the client gets a token for the `Web Api` and the  `Web Api` then exchanges it for a token for Graph via OBO. A simplistic caching algorithm would work like this: 

a.  `Web Api` looks in the cache for an access token for Graph, for the user 
b. If not found or expired,  `Web Api` looks in the cache for a refresh token for the user and uses the `refresh_token` flow 
c. If not found, `Web Api` takes the incoming assertion (the token from the Client) and performs OBO 

The problem with a. and b. is that it assumes that all clients are the same. But they are not. Assume that the tenant admin has a conditional access policies preventing access to Graph from unmanaged devices. You can imagine a scenario where a user accesses Graph using a managed device, and tokens get cached in `Web API` in the process. Then the user switches to an unmanaged device and gets a token for Web API. Now, Web API has a cached token for Graph and this gets used. So, at this point, you've gained access to Graph from an unmanaged device.

There are of course ways around this, for example the tenant admin can secure access to the Web API itself, but we cannot enforce or check this. 

So, the solution is to consider that OBO tokens are tied to session, not to the user. But the concept of "session" is somewhat ambiguous, so the best proxy is the actual token from the client itself. This is why we use "hash(incomming_assertion)"  and the algorithm now is: 

a. Is there a access cached token for Graph associated with the obo key (hash of incomming assertion)? 
b. If not, is there a refresh token associated with the obo key? 
c. If not, use the incoming assertion to get a new token


In the long running OBO APIs we do expose a way for you to provide a better session ID, and we recommend using the `sid` optional claim. 

Note: with obo, L2 cache key is the same as "obo key"

2. Why is it a problem to store the refresh token in cache? 

We want to optimize L2 eviction and refresh tokens are making it hard. Most ppl don't want need long running access in their APIs.

 If a cache node contains only access tokens, we will set the TTL for that node as `TTL = max(access tokens expiration in this cache node)` - which for OBO in most cases there is only 1 token. MSAL suggests this TTL and the cache from `Microsoft.Identiy.Web.TokenCache` sets it on IDistributedCache.

However, if there are refresh tokens in the node, we can't do this at all, because refresh tokens don't expire (well, they do, but it's an opaque process and the expiration is several months).

**Comment by luismanez** [comment]
👏👏👏👏👏👏👏 Great explanation! Thank you so much @bgavrilMS
