### ISSUE TITLE
[Bug] Azure B2C Password reset type is not showing on Xamarin.Forms UWP app

### ISSUE THREAD

**Issue by idenardi** [AzureAD/microsoft-authentication-library-for-dotnet#3812]
I have a Xamarin.Forms app using MSAL.NET + ADB2C. After I updated the Page Layout Version of the Forgot Password Page to the latest version (2.1.17), UWP stopped working and it only shows a blank Page when the user navigates to the Forget Password. Android and iOS are working as expected.

All platform is working when I use the Page Layout version 2.1.16

**Logs and network traces**

**Which version of MSAL.NET are you using?**
MSAL.NET 4.48.0

**Platform**
UWP (Xamarin.Forms)

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Interactive
    * [ ] Integrated Windows Authentication
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web app 
    * [ ] Authorization code
    * [ ] On-Behalf-Of
* Daemon app 
    * [ ] Service to Service calls

Other?

**Is this a new or existing app?**
The app is in production, I haven't upgraded MSAL, but started seeing this issue.

**Repro**
AcquireTokenInteractiveAsync passing a WithB2CAuthority type of Password reset (no custom page).

**Expected behavior**
Show the Password Reset Page

**Actual behavior**
It's showing a blank page.

**Possible solution**

**Additional context / logs / screenshots / links to code**
![image](https://user-images.githubusercontent.com/7188328/202572886-cbcf262d-9eca-412e-bd71-0ca148d953d3.png)

**Comment by bgavrilMS** [comment]
The webview used by UWP apps is very sensitive to any issue with the content of the pages in there. If there are any problems, such as an image being referenced by HTTP instead of HTTPS, the webview stops navigation and this all appears as having crashed. 

Ultimately it is a B2C service error, because they control the content of the webview. I recommend opening a ticket through the Azure Portal on the B2C side to report this issue.

**Comment by bgavrilMS** [comment]
We will not fix this. Please use WinUI.

**Comment by idenardi** [comment]
Hey @bgavrilMS, I understand that the only way to work with this layout version is to use WinUI. We are using Xamarin.Forms so only when we migrate to MAUI this will be possible. But I didn't understand one thing, is this a bug on Azure or on the MSAL library?

**Comment by bgavrilMS** [comment]
MSAL supports Maui, so that should be ok. 

There is probably a bug in 2 places: 

- UWP browser component is very strict
- Azure B2C probably updated their UI flows and introduced a component which breaks UWP browser

With WinUI you'll end up using WebView2 browser, which is more modern. 
Alternatively, please escalate this issue to Azure B2C folks via the Azure Portal.
