### ISSUE TITLE
Check for CNG Key if present

### ISSUE THREAD

**Issue by kpanwar** [AzureAD/microsoft-authentication-library-for-dotnet#383]
Check for CNG Key if present

**Comment by jmprieur** [comment]
- this is the .NET 4.7 fix made in ADAL. In MSAL, the problem is we are forced to support .NET 4.5. 
-Alternatively if we use Microsoft.IdentityModel.Token and we are willing to hit a big performance net in the case of .NET 4.5. We should wrap it up in IdentityModel.
cc: @brentschmaltz @lovemaths who have workitems to do the work in IdentityModel

**Comment by jmprieur** [comment]
@brentschmaltz then we/you should do it

**Comment by jmprieur** [comment]
On the backlog.

**Comment by brentschmaltz** [comment]
@jmprieur once we ship Wilson 5.2.5, we can start to think about this.
5.2.5 is about a week away.

**Comment by jmprieur** [comment]
@brentschmaltz @henrik-me is it something we'd like to do in Q2?

**Comment by henrik-me** [comment]
@jmprieur @brentschmaltz : why is this on the .net backlog? Is this a tacking item for replacing encryption in msal.net with Wilson? Can't we make a simpler fix in MSAL.NET for now?

**Comment by jmprieur** [comment]
@henrik-me what do we want to do with this? is it related to the bug than Vincent observed?

**Comment by henrik-me** [comment]
I don't think those things are related. Closing this one. When we get to change anything on Crypto we would have it in our backlog.
