### ISSUE TITLE
[Bug] Microsoft.Identity.Client AcquireTokenInteractive not support with two factor

### ISSUE THREAD

**Issue by joeyven** [AzureAD/microsoft-authentication-library-for-dotnet#3839]
We are using the AcquireTokenInteractive to login. This opens a webview to login. At this point the AD login will say there is more information required cause twofactor is not yet set. Then the next button is pressed to go to the screen where you can set the additional information for two factor. At this point this screen will be shown

![image](https://user-images.githubusercontent.com/94164451/205052208-0692e1a2-452c-4934-955f-2e5286746640.png)

This is done on the newest nuget package(4.48.1) with the newest version of .NET framework

**Comment by gladjohn** [comment]
Is this an embedded webview is based on old IE. 

There are 2 ways around this:

- Use WAM. See https://aka.ms/msal-net-wam (please use the new preview implementation). This will require small app changes and registering a new redirect uri
- Deploy a registry change to force the embedded webview to use Edge instead of IE

**See details here:**
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/troubleshooting#javascript-errors-in-the-embedded-browser

**Comment by bgavrilMS** [comment]
@joeyven - the embedded webview used by MSAL .NET on .NET Framework is quite old, it's based on IE7 and since you are using external MFA provider it fails. See @gladjohn 's suggestions
