### ISSUE TITLE
[Bug] Cannot build apps targeting net7.0-Windows10.0.x.x

### ISSUE THREAD

**Issue by baskren** [AzureAD/microsoft-authentication-library-for-dotnet#4023]
**Logs and network traces**
Without logs or traces, it is unlikely that the team can investigate your issue. Capturing logs and network traces is described in [Logging wiki](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging).

[BUILD LOG](https://raw.githubusercontent.com/baskren/WinuiMsalFail/main/REFERENCE%20FILES/BuildLog.txt)

**Which version of MSAL.NET are you using?**

Issue applies from versions 4.25.0 to 4.51.0
```
<PackageReference Include="Microsoft.Identity.Client" Version="4.51.0" />
```

**Platform**
- net7.0_windows10.0.18362 
- net6.0_windows10.0.18362 + Microsoft.WindowsAppSDK, version 1.1.3

**What authentication flow has the issue?**
WINDOWS DESKTOP (never get to the point where any of the following applies)
    * [ ] Interactive
    * [ ] Integrated Windows Authentication
    * [ ] Username Password
    * [ ] Device code flow (browserless)

Other?
The following may or may not be related but the symptoms are different.
- https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2673
- https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3236
- https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3583
- https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3941\
- https://github.com/microsoft/microsoft-ui-xaml/issues/5143

However, the symptoms are the same as: https://github.com/dotnet/maui/issues/6052

**Is this a new or existing app?**
App is being ported from UWP

**Repro**
https://github.com/baskren/WinuiMsalFail

**Expected behavior**
When MSAL library is added to a Windows 10+ project, the app is expected to be able to build

**Actual behavior**
Build process fails due to the following errors:
```
C:\Program Files\dotnet\sdk\7.0.300-preview.23122.5\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(448,5): error NETSDK1082: There was no runtime pack for Microsoft.WindowsDesktop.App.WindowsForms available for the specified RuntimeIdentifier 'win10-arm'.
C:\Program Files\dotnet\sdk\7.0.300-preview.23122.5\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(448,5): error NETSDK1082: There was no runtime pack for Microsoft.WindowsDesktop.App.WindowsForms available for the specified RuntimeIdentifier 'win10-arm-aot'.
```

**Possible solution**
PLEASE LET ME KNOW IF THERE IS ONE!

**Additional context / logs / screenshots / links to code**

**Comment by SameerK-MSFT** [comment]
Did it start failing after adding Microsoft.Identity.Client SDK? Does it fail to compile without it?

**Comment by baskren** [comment]
Fails ONLY with Microsoft.Identity.Client NuGet added to the project.

**Comment by SameerK-MSFT** [comment]
We do not support win10-arm and win10-arm-aot. Also note that if the package is added to pure Win3UI app, it has no issues. cc: @bgavrilMS

**Comment by baskren** [comment]
1.  Who said anything about this being a win10-arm or win10-arm-aot app? 
2. This is a pure winui3 application!

Please look at the demo app - you will see that the above is true.

3.  So if MSAL can't target arm, how are we supposed to create WinUI3 apps for Microsoft Surface Pro devices?

**Comment by bgavrilMS** [comment]
We are going to make some changes so that MSAL no longer references Windows SDK in the next version (out in a few days) - 4.52.0. It might solve this issue.

**Comment by pmaytak** [comment]
This behavior still exists with 4.53.0. MSAL net6.0-windows TFM [does include Windows Forms](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/da1371c9bfb9f42e988cf766c9eb764ed9438ed6/src/client/Microsoft.Identity.Client/Microsoft.Identity.Client.csproj#L204) because it's needed for the embedded browser.

**The repro**
- Create a new net7 console app.
- This should be the proj file, include reference to MSAL and Microsoft.WindowsAppSDK:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0-windows10.0.19041.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>11.0</LangVersion>
    <Platform>x64</Platform>
    <RuntimeIdentifiers>win10-x64</RuntimeIdentifiers>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Identity.Client" Version="4.53.0" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.3.230331000" />
  </ItemGroup>
  
</Project>
```

**The fix**
This issue describes the same error and the fix: https://github.com/microsoft/WindowsAppSDK/issues/3336
Specify `arm64` explicitly.
```xml
<RuntimeIdentifiers>win10-x64;win10-x86;win10-arm64</RuntimeIdentifiers>
```

**Why**
Microsoft.WindowsAppSDK [does have TFMs](https://www.nuget.org/packages/Microsoft.WindowsAppSDK#supportedframeworks-body-tab) for `net6.0-windows10.0.17763`, `net6.0-windows10.0.18362` which I would assume would be picked up and since the app specifies that it runs on Windows only, ARM shouldn't be built.
[This comment](https://github.com/microsoft/WindowsAppSDK/issues/2280#issuecomment-1075997143) probably alludes that the installer is trying restore all framework for which specified one is applicable to.

**Comment by pmaytak** [comment]
Closing as external. WindowsAppSDK repo would be more appropriate for clarifying that library's behavior.
