### ISSUE TITLE
[Feature Request] Expose CorrelationId from MsalException 

### ISSUE THREAD

**Issue by KurzyukovAndrey** [AzureAD/microsoft-authentication-library-for-dotnet#4187]
**Problem**
We need to meter `CorrelationId` in case of acquiring a token. However, we cannot retrieve `CorrelationId` from [MsalException](https://learn.microsoft.com/en-us/dotnet/api/microsoft.identity.client.msalexception?view=msal-dotnet-latest). 

**Use case**
The simplified code of usage is shown below: 

	public async Task<AuthenticationResult> AcquireTokenForClientAsync(
		IEnumerable<string> scopes, 
		Action<AcquireTokenForClientParameterBuilder>? configuration, 
		CancellationToken cancellationToken)
	{
		var acquireTokenBuilder = _confidentialClientApplication.AcquireTokenForClient(scopes);

		// WithCorrelationId might be called here.
		configuration?.Invoke(acquireTokenBuilder);

		try
		{
			var authenticationResult = await acquireTokenBuilder
				.ExecuteAsync(cancellationToken)
				.ConfigureAwait(false);

			// authenticationResult exposes correlationId.
		}
		catch (MsalException ex)
		{
			// MsalException does not expose correlationId. 
			// Cannot use correlationId for metering.
		}
	}

Our consumers call [WithCorrelationId](https://learn.microsoft.com/en-us/dotnet/api/microsoft.identity.client.baseabstractacquiretokenparameterbuilder-1.withcorrelationid?view=msal-dotnet-latest#microsoft-identity-client-baseabstractacquiretokenparameterbuilder-1-withcorrelationid(system-guid)) using configuration parameter. Then, we acquire a token. In case of success, we can retrieve `CorrelationId` from [AuthenticationResult.CorrelationId](https://learn.microsoft.com/en-us/dotnet/api/microsoft.identity.client.authenticationresult.correlationid?view=msal-dotnet-latest#microsoft-identity-client-authenticationresult-correlationid). But we cannot retrieve it from [MsalException](https://learn.microsoft.com/en-us/dotnet/api/microsoft.identity.client.msalexception?view=msal-dotnet-latest).

**Proposal**
Expose `CorrelationId` for all exceptions.

**Additional context**
Based on [Exceptions in MSAL.NET](https://learn.microsoft.com/en-us/entra/msal/dotnet/advanced/exceptions/), there are 4 exceptions. [MsalServiceException](https://learn.microsoft.com/en-us/dotnet/api/microsoft.identity.client.msalserviceexception?view=msal-dotnet-latest) and [MsalUiRequiredException](https://learn.microsoft.com/en-us/dotnet/api/microsoft.identity.client.msaluirequiredexception?view=msal-dotnet-latest) expose CorrelationId, but the rest do not.

**Comment by trwalke** [comment]
Hi @KurzyukovAndrey, there shouldnt be any scenarios where we throw a `MsalException` it is a base class that the other exceptions derive from. You should rely on the correlation id in the [MsalServiceException](https://learn.microsoft.com/en-us/dotnet/api/microsoft.identity.client.msalserviceexception?view=msal-dotnet-latest) and [MsalUiRequiredException](https://learn.microsoft.com/en-us/dotnet/api/microsoft.identity.client.msaluirequiredexception?view=msal-dotnet-latest) since they can occur after a request is sent to the auth endpoint. 
Also, typically the `MsalClientException` occurs in the client before a correlationd Id is sent to the endpoint so there would be no correlation id to look up in the telemetry anyway.

**Comment by KurzyukovAndrey** [comment]
Hi @trwalke, thank you for your response!

**Comment by neha-bhargava** [comment]
Fixed in [MSAL.Net 4.60.0 release](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.60.0)
