### ISSUE TITLE
TokenCache is sealed.  Reason for this?

### ISSUE THREAD

**Issue by Kressilac** [AzureAD/microsoft-authentication-library-for-dotnet#423]
The example project: https://developer.microsoft.com/en-us/graph/docs/concepts/aspnetmvc

This example project uses a derived SessionTokenCache yet when you try to implement this in an actual project, the TokenCache class is sealed and you cannot inherit from it.  Is this by design?  Seems like a bug.

**Comment by Kressilac** [comment]
The change happened between the latest 1.0.3 version and 1.1.0-preview.  I've had to revert back to 1.0.3 in order to create my own implementation of TokenCache for ASP.Net applications.  We had to do this with ADAL so the change to a sealed class is questionable and breaking at the same time.

**Comment by Kressilac** [comment]
I've seen this behavior when someone uses ReSharper against a codebase.  ReSharper will often flag infrastructure level classes as not having a reference within the code and will suggest to the developer that the class can be sealed or internal.

**Comment by kpanwar** [comment]
Token cache is sealed by design. The documentation link is going to update soon. Token cache provides methods for setting delegates for beforeaccess, afteraccess and beforewrite. Same thing was being achieved by using inheritance. We want to move forward to provide a single way of doing things. You can refer to https://github.com/Azure-Samples/active-directory-dotnet-webapp-openidconnect-v2/blob/master/WebApp/Models/MSALSessionCache.cs as an example of how new cache will be used.

**Comment by Kressilac** [comment]
Thank you.  After updating, code broke and I could not find a reason why other than to think it was a bug,  I appreciate the update and will look into the link you suggested.
