### ISSUE TITLE
[Bug] MsalUiRequiredException is thrown on unrecoverable exception (resource not available)

### ISSUE THREAD

**Issue by MZOLN** [AzureAD/microsoft-authentication-library-for-dotnet#4562]
### Library version used

MSAL Desktop 4.57.0

### .NET version

NA

### Scenario

PublicClient - desktop app

### Is this a new or an existing app?

The app is in production, and I have upgraded to a new version of MSAL

### Issue description and reproduction steps

MSAL throws and UI exception in a non-recoverable situation.

Microsoft.Identity.Client.MsalUiRequiredException: AADSTS5000224: We are sorry, this resource is not available. If you are seeing this message by mistake, please contact Microsoft support. Trace ID: 69677fd1-2d39-4cdf-883c-cba89e913000 Correlation ID: 97801ea5-ff3b-4f89-8094-7cf343be3880 Timestamp: 2024-01-21 11:35:08Z

The resource was disabled and there was no user action that could have fixed it.

### Expected behavior

A non-ui exception is thrown?

### Identity provider

Microsoft Entra ID (Work and School accounts and Personal Microsoft accounts)

**Comment by gladjohn** [comment]
Upon investigation, the error code returned from the service is `NotAllowedTenantBlockedTenantFraud`. This could be indicative of several issues, including but not limited to:

- The tenant being blocked due to suspected fraudulent activity.
- Changes in the tenant's security policies, such as newly enforced Multi-Factor Authentication (MFA).

**Recommendations :** 

- Verify if there have been recent changes to the tenant's security policies, particularly around MFA requirements.
- Attempt to log into the tenant directly to check for any prompts or additional information that could clarify the situation.
- Consider reaching out to Microsoft support for further clarification, given the suggestion in the error message.

**Comment by keegan-caruso** [comment]
@gladjohn I think the question is if this should be surfaced as a MsalServiceException or a MsalUiRequiredException

**Comment by bgavrilMS** [comment]
This was a temporary measure introduced by the STS. The error code is probably not correct, but it no longer matters, this should not occur anymore.
