### ISSUE TITLE
Does MSAL work for authentication and authorization against an Azure Mobile App Service?

### ISSUE THREAD

**Issue by JPhilC** [AzureAD/microsoft-authentication-library-for-dotnet#466]
As of now, 6th August 2017, does MSAL work for authentication and authorization with Azure Mobile App Services? I haven't seen anywhere the says definitively yes or no.  I have followed the examples I have found for calling the graph API but I have not been able to get it to work.

I have configured my mobile app service as a native application at apps.dev.microsoft.com. I have entered the client id and secret on the authentication/authorization blade in the Azure portal. I have the following code flow in my desktop app (not UWP).

```
// The following line is in my app.xaml.cs file.
public static PublicClientApplication PublicClientApp = new PublicClientApplication(Constants.MSALClientId);

// The remainder is in LoginProvider class.
public async Task LoginAsync(MobileServiceClient client, MobileServiceAuthenticationProvider authenticationProvider)
      {
         string accessToken = null;
         JObject zumoPayload = null;
         switch (authenticationProvider) {
            case MobileServiceAuthenticationProvider.Facebook:
               accessToken = await LoginFacebookAsync();
               break;
            case MobileServiceAuthenticationProvider.MicrosoftAccount:
               accessToken = await LoginMSALAsync();
               break;
            default:
               throw new ArgumentException(string.Format("The authentication provider {0} is not supported in the Desktop client.", authenticationProvider));
         }
         if (!String.IsNullOrWhiteSpace(accessToken)) {
            zumoPayload = new JObject() {
               ["access_token"] = accessToken
            };
            await client.LoginAsync(authenticationProvider, zumoPayload);
         }
      }

public async Task<string> LoginMSALAsync()
      {
         string[] scopes = new string[] { "User.Read" };
         try {
            authResult = await App.PublicClientApp.AcquireTokenSilentAsync(scopes, App.PublicClientApp.Users.FirstOrDefault());
         }
         catch (MsalUiRequiredException ex) {
            // A MsalUiRequiredException happened on AcquireTokenSilentAsync. This indicates you need to call AcquireTokenAsync to acquire a token
            System.Diagnostics.Debug.WriteLine($"MsalUiRequiredException: {ex.Message}");

            try {
               authResult = await App.PublicClientApp.AcquireTokenAsync(scopes);
            }
            catch (MsalException msalex) {
               System.Diagnostics.Debug.WriteLine($"Error Acquiring Token:{System.Environment.NewLine}{msalex}");
               return "";
            }
         }
         catch (Exception ex) {
            System.Diagnostics.Debug.WriteLine($"Error Acquiring Token Silently:{System.Environment.NewLine}{ex}");
            return "";
         }

         if (authResult != null) {
            return authResult.AccessToken;
         }
         return "";
      }

```
When run, this correctly displays the Microsoft login page letting me log in and accept permissions etc but then when the `client.LoginAsync(authenticationProvider, zumoPayload);` call is made it throws an exception with the message "You do not have permission to view this directory or page.".

Am I missing a step or is is just that MSAL does not work with Azure mobile app services?

**Comment by jmprieur** [comment]
@jmprieur to answer
could be lack of permissions (access to the service), policy, ...

**Comment by JPhilC** [comment]
@jmprieur Thanks for the update. I had forgotten I had posted this. In the end I switched to using Azure Active Directory B2C and Microsoft.Identity.Client on the front end.

**Comment by Mephisztoe** [comment]
Now this is funny. Just in case, anyone else stumbles accross this post as I did yesterday: If you are searching for a way to use **MSAL** for the sole purpose of authentication and **Microsoft.Azure.Mobile.Client** for working with your Azure App Service hosted Api or Tables, then _this_ is the solution.

Now image this scenario: 
So that you are able to implement a simple user management, you decide to integrate **Azure Active Directory B2C** as @JPhilC did. Then you will most certainly configure your Azure App Service to enable Authorization and select Active Directory as the only option. This way you can integrate the server workflow into your client apps, for instance the Signin/Signup Workflow. If you are using MSAL and AcquireToken then you will receive an AccessToken that you cannot use with Microsoft.Azure.Mobile.Client directly.

Instead you can create a payload as @JPhilC did above containing the AccessToken and call MobileServiceClient.LoginAsync with _MobileServiceAuthenticationProvider.WindowsAzureActiveDirectory_. What it does, is calling the **.auth/login/aad** endpoint which in return responds with an AuthenticationToken. It populates the MobileServiceUser with an Id it got from your AccessToken and the mentioned AuthenticationToken and now you can easily use Microsoft.Azure.Mobile.Client for anything it might be useful for you for. 

I really wonder why this method isn't mentioned anywere...
