### ISSUE TITLE
[Bug] When will Proof of Possession be released?

### ISSUE THREAD

**Issue by sameerkapps** [AzureAD/microsoft-authentication-library-for-dotnet#4665]
### Library version used

4.54.0

### .NET version

N/A

### Scenario

ConfidentialClient - service to service (AcquireTokenForClient)

### Is this a new or an existing app?

None

### Issue description and reproduction steps

[Doc](https://learn.microsoft.com/en-us/entra/msal/dotnet/advanced/proof-of-possession-tokens#proof-of-possession-for-confidential-clients) says that Pop token is experimental for confidential clients. Is the doc correct? If so, is when do you plan to remove it as experimental feature?

### Identity provider

Microsoft Entra ID (Work and School accounts and Personal Microsoft accounts)

**Comment by bgavrilMS** [comment]
Hi @sameerkapps - long time :)

We are looking into a different approach for POP for confidential client, based on MTLS, because it's faster.

I think the version of POP that is already out there as experimental is ok from security perspective and we will keep it (maybe we'll rename the API at some point).

**Comment by sameerkapps** [comment]
Thanks. We cannot use experimental api in the production code. So we will use the non-pop token. But still using the product. 😀
