### ISSUE TITLE
TouchID with Azure authentication.

### ISSUE THREAD

**Issue by rajamaheshwarsingh** [AzureAD/microsoft-authentication-library-for-dotnet#488]
How to use TouchID with MSAL B2C directory?

**Comment by maddentist** [comment]
Might also be interesting to use Windows Hello... on Windows but also biometrics on Android. Is it even possible ?

**Comment by jmprieur** [comment]
@kpanwar would using WAM do it for Windows Hello on Windows?

**Comment by kpanwar** [comment]
Windows Hello uses identity primitives implemented in AAD for authentication. To be able to support the same in iOS and Android, it would require the OS to support AAD specific features or have AAD support biometric as an authentication proof. There are no plans to support this in AAD for now. I am going to close this issue because it is not actionable for us.
