### ISSUE TITLE
Authenticate to Dynamics 365 API

### ISSUE THREAD

**Issue by P4trik** [AzureAD/microsoft-authentication-library-for-dotnet#497]
Since the ADAL.js library is quite "buggy", I want to ask if it's possible to authenticate with the MSAL to the Dynamics 365 endpoint. 
In my case, I'm developing an Outlook 365 Add'in as SPA and need to CRUD some data of Dynamics 365 with current users context. What type of "scope" do I have to use to get a valid token to access the Dyn API?

**Comment by jmprieur** [comment]
@P4trik : this is the issue list MSAL.NET (not for JavaScript). 
Since your question involves knowledge beyond the auth libraries, I'd suggest you ask it on Stack Overflow: https://stackoverflow.com/questions/tagged/msal. More people would be able to answer.

I'm closing it for now (please add the link to Stack overflow in this thread when you have asked your question there)
