### ISSUE TITLE
Make browser popup full screen - with no top bar

### ISSUE THREAD

**Issue by WilliamWatterson86** [AzureAD/microsoft-authentication-library-for-dotnet#525]
Hi, I have added the dlls and got my profiles up and running how i would like.  The browser window opens - and it is obvious that the user has left my app and this is a web login.  Is there any way to make the browser appear full screen?  Ideally i want it to look like it is part of my app.  Please help. 

![image](https://user-images.githubusercontent.com/32571925/35578990-78ac56ee-05dd-11e8-9ce4-203374a9c816.png)

**Comment by brandwe** [comment]
Hello @WilliamWatterson86 - at the moment we don't have a way of changing the default of your app from using the System Browser. For MSAL Preview we switched to the System Browser to follow along with the rest of the industry in leveraging the better security of using the System Browser for sign-in. [Google has a good write-up on the issue here](https://developers.googleblog.com/2016/08/modernizing-oauth-interactions-in-native-apps.html).

However, this does cause developers that are using our B2C service to reveal they are using Microsoft for their login service. That is not ideal. 

For that reason in our next release we plan to allow developers to select if they want to continue to use embedded Webviews (which allow you to display the embedded web view full screen) or the more secure System Browser. We currently don't have an external date for that next release, however.

**Comment by WilliamWatterson86** [comment]
Thanks for your quick response. I will continue to use it as is and hopefully in the next release we can hide this.
