### ISSUE TITLE
MSAL doesn't work with combined consent 

### ISSUE THREAD

**Issue by HadeelElbitar** [AzureAD/microsoft-authentication-library-for-dotnet#528]
Try authenticating with two resources (scope=User.Read https://myresource/access_as_user) for example, you will get through login and consent just fine, but then MSAL will send all scopes to token endpoint along with the multi-resources acquired authCode, which will fail by design. 

The token endpoint need to specify only one resource scope since access tokens can't be issued for multiple resources.

**Comment by jmprieur** [comment]
Hello @HadeelElbitar 
Indeed, this works fine for MSGraph scopes (since they all are of the same resource), but not for different resources. We need to document that better. I wonder if we could even detect that there are several resources?

As a workaround: did you try to use one of the overrides of AcquireTokenAsync which has a extraScopesToConsent parameter?
![image](https://user-images.githubusercontent.com/13203188/35681537-fc6ca872-075d-11e8-8f49-304a6dd14054.png)

you could use the scopes for only one of the resources (for instance https://myresource/access_as_user) in the **scopes** parameter, and "User.Read" in the **extraScopesToConsent** ?

**Comment by HadeelElbitar** [comment]
Works!

**Comment by jmprieur** [comment]
Thanks for confirming @HadeelElbitar
