### ISSUE TITLE
AcquireTokenAsync throws NotImplemented on netcoreapp2.0

### ISSUE THREAD

**Issue by phatcher** [AzureAD/microsoft-authentication-library-for-dotnet#609]
I'm trying to convert an app to netcore2.0 and one of its libraries uses Microsoft.IdentityModel.Clients.ActiveDirectory to acquire tokens.

Unfortunately AcquireTokenAsync throws a NotImplemented exception - is there anyway around this?

**Comment by bgavrilMS** [comment]
Hi @phatcher - currently we do not support interactive flows (i.e. showing the browser) in netcoreapp. This is because netcore does not provide such APIs. We do not have a workaround for this, expect to use a non-interactive authentication flow such as username/password or Win Integrated Auth see https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/AcquireTokenSilentAsync-using-Integrated-authentication-on-Windows-(Kerberos)

CC @jmprieur for awareness in prioritizing the feature.

**Comment by phatcher** [comment]
@bgavrilMS Thanks for the clarification._
