### ISSUE TITLE
Persistent sign-in MicrosoftGraph

### ISSUE THREAD

**Issue by Mohsens22** [AzureAD/microsoft-authentication-library-for-dotnet#616]
**Which Version of MSAL are you using ?**
MSAL 2.0.1-preview
**Which platform has the issue?**
Net46 console app

--------

Hey,
I'm using MSAL with MSGraph, it seems that there is no way for me to save `TokenCache` in a file system to have a persistent sign in experience.

Take a look at https://stackoverflow.com/questions/52394383/persist-sign-in-microsoft-graph-c-sharp-sdk for details.

**Comment by bgavrilMS** [comment]
Hi @Mohsens22 - apologies for not replying earlier, we have to get better at monitoring SO. I replied on stackoverflow where you added more details about the problem. I'm adding my answer here as well: 


I will try to clarify the issues here: 

1. MSAL .net is build for different platforms - .net desktop, .net core, UWP, xamarin android and xamarin iOS. On some of these platforms (UWP and xamarin) we persist the token cache for you. On the others, we expect you to persist the cache. The reason is that we cannot provide token serialization logic that works well for all scenarios (e.g. ASP.NET server farms), so we expect you to do it. We provide samples and guidance around it this. Details and some reference implementations on the [MSAL wiki][1]: 


2. The sample code provided by @Michael is ok for MSAL v1. In MSAL v2 the things are a bit different and you can find the pattern of calling is also on the [MSAL wiki][2]: 


3. We request and store the refresh token (RT). If the auth token (AT) is expired, we will request a new one based on the RT - this will happen without user interaction. This should all be transparent to you, i.e. it should just work :). Make sure that your token cache serialization works, i.e. you get an account when performing 



    // perform an interactive login first 
    // otherwise there will be no AT / RT in the store
    var accounts = await app.GetAccountsAsync();
    // there should be an account that you can use

Also check out @Daniel Dobalian's answer for default expiration of AT and RT: 
https://stackoverflow.com/questions/44518731/msal-token-expires-after-1-hour


  [1]: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/token-cache-serialization
  [2]: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/AcquireTokenSilentAsync-using-a-cached-token
