### ISSUE TITLE
AcquireTokenAsync() call does not return when continuation is set with some B2C local accounts

### ISSUE THREAD

**Issue by taimila** [AzureAD/microsoft-authentication-library-for-dotnet#655]
---
name: AcquireTokenAsync() call does not return when continuation is set

about: 
Authentication with Azure B2C AD seems to work fine and control returns to `MainActivity. OnActivityResult()` where I call `AuthenticationContinuationHelper.SetAuthenticationContinuationEventArgs(requestCode, resultCode, data);` in order to communicate MSAL that it's time to move on. This works almost always without issues, but I have few Azure B2C accounts created with email addresses that seem to cause issues. With those accounts `AuthenticationContinuationHelper.SetAuthenticationContinuationEventArgs()`call has no effect and therefore `AcquireTokenAsync()` does not return until timeout is reached.

I can't figure out anything special about those accounts. Even if remove them from AD and recreate the accounts with same email addresses, they keep failing. Azure AD B2C portal shows successfull logins as one would expect since execution returns to app after login.

I know this is far from perfect bug report, but I'm getting desperate.

---

**Which Version of MSAL are you using ?**
MSAL 2.3.0-preview

**Which platform has the issue?**
xamarin android, xamarin iOS

**What authentication flow has the issue?**
* Mobile
    * [ ] Xamarin.iOS
    * [X ] Xamarin.Android
    * [ ] UWP

**What is the identity provider ?**
* [ ] Azure AD
* [X] Azure AD B2C

**If B2C, what social identity did you use?**
Email (no social identity)

**Repro**
Sorry, but can't provide.

**Expected behavior**
`await adClient.AcquireTokenAsync(Settings.Scopes, await GetCurrentAccount(), uiParent);` should return when `AuthenticationContinuationHelper.SetAuthenticationContinuationEventArgs(requestCode, resultCode, data);` is called from `OnActivityResult` of `MainActivity`.

**Actual behavior**
Method does not return, but gets stuck until timeout exception gets thrown.

**Comment by jmprieur** [comment]
@taimila : do I understand that those failing identities are local B2C identities?

**Comment by taimila** [comment]
I was able to reproduce this issue with [sample application](https://github.com/Azure-Samples/active-directory-xamarin-native-v2) by modifying it to point to our Azure AD B2C tenant. Logging in with most accounts works fine, but with few accounts it gets stuck and timesout eventually. I wonder is there some Azure AD B2C configuration that could cause this. 🤔

**Comment by jmprieur** [comment]
@parakhj @valnav do you have any idea?

**Comment by valnav** [comment]
I am looking at it @taimila - are there any specific errors you got.

**Comment by taimila** [comment]
Unfortunately, no. `AuthenticationContinuationHelper.SetAuthenticationContinuationEventArgs(...)` returns normally without errors.

**Comment by valnav** [comment]
@taimila - I have tried to recreate the problem, but unable to do it. Have you made sure that you've followed the steps for Android. For example there is the androidmanifest.xml which you need to update the **AppId/ClientId** 
`<data android:scheme="msal[`**clientId**`]" android:host="auth" />`

**Comment by taimila** [comment]
> @taimila - I have tried to recreate the problem, but unable to do it. Have you made sure that you've followed the steps for Android.
I have and it does work **most** of the time just fine. I've been able to replicate the issue with [sample app](https://github.com/Azure-Samples/active-directory-xamarin-native-v2) built by Microsoft, just by changing the configuration to point to our Azure AD B2C tenant.

**Comment by jennyf19** [comment]
@taimila Are you still have the issue with the latest release of [MSALv2.5.0-preview](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/releases/tag/MSAL-v2.5.0)? If so, you can you email me the [logs](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging#sample-for-logging-in-msal-2x) and we'll check with B2C and see what they're seeing on their end? jeferrie@microsoft.com

**Comment by chixlol** [comment]
I have the same issue, but can't give you steps to reproduce it either.

Sometimes it works, and I receive an AuthenticationResult from AcquireTokenAsync within a few seconds.

But sometimes it just gets "stuck" and AcquireTokenAsync does not return until a timeout exceptions gets thrown.
The strange thing is, that this only happens when the App build was done from the build pipeline in debug mode. In Release mode, everything works fine and with local deployment directly from visual studio to my android phone i couldn't reproduce this problem either.

I use Xamarin Forms with MSAL v2.5 pre and run it on android

**Comment by taimila** [comment]
The problem has disappeared from my app and I still don't understand at all why. :( On Xamarin.iOS project I use old `1.1.2-preview0008` version of the Nuget and on Xamarin.Android I have a version `2.4.0-preview`. The issue doesn't seem to be version specific, since it did fail with these specific versions. 

I have done other seemingly unrelated changes to the app, but can't understand how those could have any effect. It looked like a threading issue, but then again, it consistently happened with specific email addresses and never with others, which makes me think could it be something with token cache.

I'm afraid to do any changes to the app now that it works, but I might give a try with new version soon.

**Comment by jennyf19** [comment]
@taimila @chixlol If either of you manage to get logs from a failed acquire token call, that would be really helpful.

**Comment by chixlol** [comment]
@jennyf19 From my side, I am not able to give you logs from a failed acquire token call, because there is no failed call!? In adb2c and my app everything seems to work fine, except that the function does not return until an exceptions gets thrown.

The interesting thing is, that that three different exceptions get thrown when i try to log in several times. It seems to be completely random what exceptions gets thrown, but the timeoutexception appears most of the time.

The exceptions are:

- Socket.EndReceive (System.IAsyncResult asyncResult) - System.Net.Http.HttpRequestException: Connection reset by peer 

- HttpWebRequest+<RunWithTimeoutWorker>d__241`1[T].MoveNext () System.Net.Http.HttpRequestException: The operation has timed out.

- askAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) Microsoft.Identity.Client.MsalServiceException: A task was canceled.


As i already mentioned, this only happens with a DevOps CI build. Our workaround for now is, to generate an apk/ipa local in VS and then upload it to appcenter.

Let me know if you need the stack traces. Luckily the exceptions where catched by appcenter sometimes

**Comment by jennyf19** [comment]
@chixlol And this is only with b2c local accounts? Do you see the same w/FB or Google accounts? Stack traces would be interesting to see. Could you also get logs when these exceptions are thrown? You can email them if you want: jeferrie@microsoft.com

**Comment by chixlol** [comment]
@jennyf19 Hello and sorry for not answering your message from 7 jan.

I can't tell you if this issue is still present, since it only appeared when I did build with the devops ci build.
Due to issue 852 we are currently not able to run the CI build and dont have this issue any more.

**Comment by jennyf19** [comment]
@chixlol Thanks for the udpate. 

@jmprieur - not sure if we want to leave this open or close?

**Comment by jmprieur** [comment]
proposing to close, and @chixlol, feel free to reopen if this repros when you are able to run the CI build?
