### ISSUE TITLE
Enabling authentication on devices with-out mouse and keyboard for UWP/IoT (was: MSAL Refresh Token?)

### ISSUE THREAD

**Issue by toddsharpe** [AzureAD/microsoft-authentication-library-for-dotnet#667]
---
name: MSAL Refresh Token?
about: Refresh token not a part of AuthenticationResult

---

**Which Version of MSAL are you using ?**
Note that to get help, you need to run the latest preview or non-preview version
For ADAL, please log issues to https://github.com/AzureAD/azure-activedirectory-library-for-dotnet
MSAL 2.3.1-preview

**Which platform has the issue?**
UWP

**What authentication flow has the issue?**
* Desktop 
    * [ ] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username / Password
    * [ ] Device code flow (browserless)
* Mobile
    * [ ] Xamarin.iOS
    * [ ] Xamarin.Android
    * [ ] UWP
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO
* Daemon App
    * [x] Client credentials
    
Other? - please describe;

**What is the identity provider ?**
* [ ] Azure AD
* [ ] Azure AD B2C

If B2C, what social identity did you use?

**Repro**

```csharp
AuthenticationResult authResult = await IdentityClientApp.AcquireTokenAsync(scopesArray).ConfigureAwait(false);
```

**Expected behavior**
AuthenticationResult has RefreshToken OR TokenCache has a way to extract it

**Actual behavior**
RefreshToken is omitted

**Possible Solution**

**Additional context/ Logs / Screenshots**
The scenario is an IOT device without a keyboard and mouse that needs access to Graph API. UWP on desktop authenticates for user and needs to send both token and refresh token to IOT device to enable long term authentication.

**Comment by jmprieur** [comment]
Thanks for sharing your scenario., this is very useful to find the best solution.

Can you consider your iOT device as a confidential client (can keep a secret or certificate ?). If that's the case you could use the [On-behalf-of flow](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/on-behalf-of) on the iOT. This way the iOT would receive the access token from the UWP application for the iOT, and request a token for itself in the name of the user to call a downstream service (using `AcquireTokenOnBehalfOfAsync` passing a user assertion which is the access token it receives.

**Comment by toddsharpe** [comment]
Thank you for the reply! I was taking a look at that flow but I couldn't find the method AcquireTokenOnBehalfOfAsync like you specified. ConfidentialClientApplication doesn't exist. To clarify, the IOT device is running a UWP (its Windows IOT). I am using the NuGet package "Microsoft.Identity.Client". Am I missing something?

Thanks!

**Comment by henrik-me** [comment]
@toddsharpe : We are currently not including the ConfidencialClient in the uap10.0 target, however it is in netstandard and netcore. 

@jmprieur @bgavrilMS : I currently see no reason why we should not be able to include it, thoughts?

**Comment by toddsharpe** [comment]
Thanks @henrik-me. UWP supports .net standard 2.0 if I'm not mistaken, I'll try extracting this logic into a .net standard dll and trying to invoke it that way.

If there was a way to serialize the TokenCache, transport it, and Deserialize it on the IOT UWP that would also work. I see TokenCache has the serialize/deserialization methods in ADAL but not MSAL, is this correct?

**Comment by bgavrilMS** [comment]
@henrik-me - the Confidential Client assumes there is a secure connection between the "server" and the IdP. There is no way to deploy a secret to a client app (UWP, Android, iOS) to ensure this secure connection. I believe @jmprieur described this here: https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Right-usage-of-confidential-client-flows

@toddsharpe - we do have extensibilty for the MSAL cache, pretty much the same way as we had in ADAL. This is disabled by default in UWP (and Android and iOS) because ADAL / MSAL can provide a secure and performant way for storing tokens. This assumes only PublicClient is used. This being said, the netstandard version of the app should have the extensibility. https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/token-cache-serialization

I would recommend the approach described by @jmprieur though - use the UWP to get a token, then pass it to IoT app (netcore probably) and have this app use the OBO flow, which essentially says "I have this token from the user, give me a token on his behalf".

**Comment by toddsharpe** [comment]
@bgavrilMS Thank you for the reply.

Keeping with the original architecture of the IOT device running UWP, what is the recommended way to solve this scenario if both MSAL cache extensions and OBO require .net standard?

I tried to build a .net standard 2.0 library and reference it from my UWP project (min ver: 16299, Target: 17134) but had runtime errors.

**Comment by bgavrilMS** [comment]
The way .net multi-targetting works is that at edit time, you are coding against the .net standard library. At runtime, the UWP library is used. So trying to use OBO will result in a MissingMethodException. 

I agree that MissingMethodExceptions are poor and we need to do better, i.e. throw a PlatformNotSupported("OBO is not supported in UWP").

I was not aware of the UWP + IoT scenario. If there is a way to securely deploy a secret to your IoT device, then we should allow ConfidentialClient flows. @henrik-me, @jmprieur - it should be easy to enable these on UWP, just include the flows + some testing. 

@toddsharpe  - I wonder if we detect between IoT UWP and non-IoT UWP so that we can throw an exception in the non-IoT case?

**Comment by toddsharpe** [comment]
@bgavrilMS Due to the nature of IOT, I don't think a client secret would be the best idea.
1. The IOT UWP is different than the non-IOT UWP. The non-IOT UWP is fine doing interactive authentication so it can pass the token to the IOT-UWP

2. For IOT UWP there doesn't seem to be a way to extract these tokens. Is there? All I really need is the refresh token.

What I'm trying to avoid is taking the credentials directly and doing the HTTP requests manually, which would give me both the tokens I need.

**Comment by toddsharpe** [comment]
Just wondering the status on this. I'm confused how to move forward with this scenario, besides downloading the MSAL on github and hacking in refresh token support

**Comment by jmprieur** [comment]
@toddsharpe : is the Client ID of both apps the same? (this is possible with MSAL)

@bgavrilMS @henrik-me 
I think we should expose the custom serialization (as an option ) in UWP in the same way it's available in .NET Framework and .NET Core?

**Comment by toddsharpe** [comment]
@jmprieur Correct both Client IDs are the same

**Comment by henrik-me** [comment]
@jmprieur : I believe we can mark that as a feature request as we have been discussing previously (already done).

**Comment by bgavrilMS** [comment]
We have disccussed this and we are rejecting it. Certificates must not be deployed on UWP apps.
