### ISSUE TITLE
MSAL is difficult to test because AuthenticationResult is not mockable

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#682]
MSAL is not easily mockable because the AuthenticationResult is an immutable sealed class with no public constructors. 

There has been an attempt to correct this in MSAL 1.x by adding an IAuthenticationResult interface, but this seems that it did not make it into MSAL 2.x 

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/253/files

This is related to issue https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/679

@dansiegel - I'd propose to add IAuthenticationResult interface back for testability, what do you think?

**Comment by dansiegel** [comment]
@bgavrilMS basing it on IAuthenticationResult would be great actually... from what I've had to do to try to test with AuthenticationResult, there's a little bit of a rabbit hole of currently internal classes that make this work.

**Comment by bgavrilMS** [comment]
Thinking a bit more about - if we introduce this interface and have all AcquireToken* methods return IAuthenticationResult - it will be a breaking change. 

If I just introduce the interface, but keep returning AuthenticationResult, the classes will not be mockable. 

I think we are ok with taking some breaking changes while in Preview (we'd still bump the major version of course). Alternatively we could add setters, since this is more of data class and the current constructor is more of an adapter from token cache items (an internal concept).

I am tempted to go more for the second variant. Thoughts?

**Comment by dansiegel** [comment]
@bgavrilMS I would tend to say that while this is a breaking change it should be low enough impact that I wouldn't worry about bumping to v3, particularly since there has never been a "stable" release for MSAL.

That said if you instead simply introduced a factory method on AuthenticationResult that could create an AuthenticationResult from a Jwt that could work too. It would certainly have the benefit of providing a way to test without creating a break. I would also note that since we're talking about an API that strictly should be used for testing I would add an EditorBrowsable Attribute and set it to Never be browsable. That would keep it as an API that you could find in source or through the docs on how to test.

**Comment by erdmenchen** [comment]
@dansiegel Can you provide a sample about how you are mocking the AuthenticationResult currently via Reflection in your unit tests? I am in the same situation and just want to mock the AuthenticationResult for my unit tests.

**Comment by jennyf19** [comment]
Fixed in [MSALv2.5.0-preview](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/releases/tag/MSAL-v2.5.0)
