### ISSUE TITLE
AcquireTokenSilentAsync ignores AccessToken and refreshes it by RefreshToken on each call when requesting certain scopes and account is MSA

### ISSUE THREAD

**Issue by 23W** [AzureAD/microsoft-authentication-library-for-dotnet#743]
**Which Version of ADAL are you using ?**
Note that to get help, you need to run the latest preview or non-preview version
For MSAL, please log issues to https://github.com/AzureAD/microsoft-authentication-library-for-dotnet
v2.6.2-preview

**Which platform has the issue?**
net45

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

Other? - please describe;

**What is the identity provider ?**
* [x] Azure AD
* [ ] Azure AD B2C

**Repro**

```csharp
string AppId = "...";

string[] AppScopes =
{
    // Users' scopes
    "User.ReadBasic.All",
    "User.Read",

    // Files' scopes
    "Files.ReadWrite",
    "Files.ReadWrite.All",
};

byte[] tokensStream = null;

var tokenCache = new TokenCache();
tokenCache.SetAfterAccess((TokenCacheNotificationArgs args) =>
{
    if (args.TokenCache.HasStateChanged)
    {
        lock (locker)
        {
            tokensStream = args.TokenCache.Serialize();
        }
    }
});

tokenCache.SetBeforeAccess((TokenCacheNotificationArgs args) =>
{
    lock (locker)
    {
        args.TokenCache.Deserialize(tokensStream);
    }
});

const string DefaultAuthority = "https://login.microsoftonline.com/common/";
var App = new PublicClientApplication(AppId, DefaultAuthority, tokenCache);

var account = await App.GetAccountsAsync().FirstOrDefault();

public async Task<string> GetToken(IAccount account)
{
var accessToken = string.Empty;
{
    result = await Application.AcquireTokenSilentAsync(AppScopes, account).ConfigureAwait(false);
    accessToken = result.AccessToken;
}
catch (MsalUiRequiredException)
{
    result = await Application.AcquireTokenAsync(AppScopes, string.Empty, UIBehavior.ForceLogin, string.Empty).ConfigureAwait(false);
    accessToken = result.AccessToken;
}
catch (Exception ex)
{
    MessageBox.Show(ex.Message, "Failed to get token", MessageBoxButtons.OK, MessageBoxIcon.Error);
}

return accessToken;
}
```

**Expected behavior**
`AcquireTokenSilentAsync` should refresh access token only when it is expired.

**Actual behavior**
`AcquireTokenSilentAsync` refreshes access token on each call.
This occurs when user is logged on by Personal\Live Account (non School\Organization). And looks like it tied with "User.ReadBasic.All" permission. Without this permission in app scopes everything works fine, but this permission is required by MSGraph to receive information about owners of files in OneDrive.

**Possible Solution**
Looks likes this permission is essential for Organization Account only, but I'm not sure.
Is there way how to define real permission allowed for account (returned by Authorization server for account) so I can use them in call of `AcquireTokenSilentAsync` ? 
Or maybe `TokenCache` can save requested permissions and use it (instead of returned by server) in `TokenCache.FindAccessTokenCommon` methods when it compares requested scopes with item scopes from cache:

```csharp
IEnumerable<MsalAccessTokenCacheItem> filteredItems =
                    tokenCacheItems.Where(item => ScopeHelper.ScopeContains(item.ScopeSet, requestParams.Scope));
```

**Additional context/ Logs / Screenshots**

**Comment by henrik-me** [comment]
Moving back to 4.2. Really would like to have this investigated. It's an important part of our performance an reliability work. This has been open for a very long time.

**Comment by bgavrilMS** [comment]
ACK, I can repro this.

**Comment by bgavrilMS** [comment]
So it looks like the scopes that are sent are not identical to the scopes that are sent. In particular, we send these to the token endpoint:

Files.ReadWrite Files.ReadWrite.All offline_access openid profile User.Read **User.ReadBasic.All**

and we get back: 

Files.ReadWrite Files.ReadWrite.All openid profile User.Read **User.ReadWrite**

We store the AT along with the scopes that we receive from the server, not we the scopes in the request. So when we try to look for an AT, we can't find one that uses all our scopes. 

To follow up: 
 - workaround would be to use User.ReadWrite instead of User.ReadWriteBasic
- will discuss with the Graph and MSA folks about why this is happening. 
- I wonder if MSAL should be more aggressive with this type of inconsistency, i.e. if the scopes in the request != scopes in the response, fail fast? CC @jmprieur

**Comment by jmprieur** [comment]
@bgavrilMS : I think that this is what Dejan proposed. There is an aPI review about this problem.
@psignoret : do you have an explanation for the scopes?

**Comment by bgavrilMS** [comment]
Note that this only happens with an MSA account. AAD accounts return User.ReadBasic.All

**Comment by bgavrilMS** [comment]
So the root cause for this seems to be an incorrectly configured app. The scope `User.ReadBasic.All` is an Application scope, so it cannot be returned in the context of a user. The scope `User.ReadWrite` is returned because it has been provisioned in the app registartion - AAD will create tokens that can be used with all provisioned APIs. 

Solution: Stop requesting `User.ReadBasic.All` - this is an app scope and can be requested using a Confidential Flow, on behalf of an app, not on behalf of a user: 

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Client-credential-flows
