### ISSUE TITLE
Implement the Deserialize methods when the merge parameters is true

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-authentication-library-for-dotnet#916]
**Is your feature request related to a problem? Please describe.**
See [How to maintain SSO with apps written with ADAL v3, ADAL v4, MSAL.NET v2](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/MSAL.NET-3-released#how-to-maintain-sso-with-apps-written-with-adal-v3-adal-v4-msalnet-v2)

Note that on the `ITokenCache` `Deserialize`*XXXX* methods take a `merge` parameter

```CSharp
public interface ITokenCache
{
 void DeserializeMsalV2(byte[] msalV2State, bool merge);   // MSAL V2.0 format (was Deserialize() in MSAL 2.x)
format
 void DeserializeMsalV3(byte[] bytes, bool merge);         // New: MSAL V3.0 unified cache format
 void DeserializeAdalV3(byte[] bytes, bool merge);         // New ADAL V3.0 format only with merge
}   
```

However it's not supported today (only `merge`=`false` is supported)

**Describe the solution you'd like**
`merge`=`true` is supported

**Comment by jmprieur** [comment]
@MarkZuber @henrik-me @jennyf19 @bgavrilMS @trwalke 
FYI

**Comment by MarkZuber** [comment]
After further discussion with @henrik-me we need more discussion here.

For MSAL (v2/v3) cache formats, the dev3x preview and current state is that we already just do the merge.  Given our north-star of getting to per-item cache persistence across the board (e.g. in alignment with xplat c++/macos objc) I think having any case where we kill the entire cache is dangerous.  

I propose we update this API back to NOT having the merge flag and update the documentation to state that it will merge in the contents.

The only case where this won't be true is ADAL legacy cache since that's just written as a bag of bytes so it's more difficult to do the merge there.

**Comment by MarkZuber** [comment]
We are removing the merge flag as discussed, so I'm closing this out.
