### ISSUE TITLE
How to avoid including the scopes "profile" and "offline_access" when using GetAuthorizationRequestUrlAsync

### ISSUE THREAD

**Issue by titobf** [AzureAD/microsoft-authentication-library-for-dotnet#93]
From this documentation [well-known-scopes](https://azure.microsoft.com/en-us/documentation/articles/active-directory-v2-compare/#well-known-scopes) it seems that the scopes "email" and "profile" are optional when using the "openid" scope. Also, the "offline_access" seems to be optional.

I'm looking for a way to avoid including the scopes "profile" and "offline_access" when using the GetAuthorizationRequestUrlAsync method.

**Comment by kpanwar** [comment]
Both profile and offline_access are required scopes for the library to be able to provide an optimized cache lookup.

**Comment by htuomola** [comment]
We have a SPA frontend and a web API and I'd like to do requests from the backend during user's session. So I don't need the "offline_access" functionality but would still like to use this library on server side to do on-behalf-of authentication. Isn't this a use case you are targeting?
For anyone else having problems with this, implementing the on-behalf-of flow manually is luckily just one simple request: [docs](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-v2-protocols-oauth-on-behalf-of#service-to-service-access-token-request).

**Comment by htuomola** [comment]
@kpanwar I've been looking at the code some more and it seems that at least much of it would seem to handle the absence of a refresh token (what offline_access basically changes, AFAIK) rather gracefully. With that, couldn't we make the offline_access as an optional scope to be used for optimal caching effectiveness.

**Comment by kpanwar** [comment]
We don't plan on changing the default scopes because it pushes the churn on the service to reauthenticate the user or the client application. there is code for fallback protection, but that does not mean that we make it optional altogether. Refresh token exists to ensure that the creds are not sent over the wire again and again.

what I don't understand is, why is you SPA using msal.net? you should be using MSAL.js instead for SPA

**Comment by kpanwar** [comment]
We don't plan on changing the default scopes because it pushes the churn on the service to reauthenticate the user or the client application. there is code for fallback protection, but that does not mean that we make it optional altogether. Refresh token exists to ensure that the creds are not sent over the wire again and again.

what I don't understand is, why is you SPA using msal.net? you should be using MSAL.js instead for SPA

**Comment by htuomola** [comment]
@kpanwar we are also using msal.js on the client side but there are cases in backend where it also has to talk to Azure AD, using the on-behalf-of flow. One reason is that the tokens issued by v2.0 endpoint do not contain any group claims so to get user's groups app has to do a call to AD (Microsoft Graph). That call can't be made from JS as we can't trust the browser to tell backend what groups user belongs to. Unless we decide to accept the "Access your info anytime" (we're building a SaaS and not sure if customers would accept that) we are forced to re-implement the whole authentication and token caching without Msal. Well, at least it's open source so we might be better off forking this rather than building one from scratch.

**Comment by janireu** [comment]
We would also like to avoid requesting the "offline_access" scope. Our sessions are very short (less than 5 min) so we don't need long term access, we just read the user profile once. 

Our main problem is the permission prompt for the users that looks invasive and we don't really need :

> XXX will be able to see and update your information, even when you are not using this application.

Are there any plans now to make this scope optional?

**Comment by janireu** [comment]
@jmprieur Thanks for answering so quickly 

Right now, we are 
1. calling GetAuthorizationRequestUrlAsync, which I believe always includes scopes "profile, openId, offline_access". 
2. calling AcquireTokenByAuthorizationCodeAsync that apart from the provided scopes, checks if the default ones have been granted (I've checked calling this method without the offline_access scope granted and I get an error)
3. passing that token to the Grapth client to get the user's profile

All the above happens in less than 5 min, so we don't need refresh tokens. We can implement all this manually, but we really like the idea of using the library.

**Comment by jmprieur** [comment]
@janireu. Are you doing this from a Web application? maybe an ASP.NET or ASP.NET core web app?

**Comment by janireu** [comment]
Yes, it's a web application but I'm not using Microsoft to hold the session, just to record some information.
